export type CreditCardSeed = {
  slug: string;
  name: string;
  nameBn: string;
  network: "VISA" | "MASTERCARD" | "AMEX" | "UNIONPAY";
  tier: "CLASSIC" | "GOLD" | "PLATINUM" | "SIGNATURE" | "TITANIUM" | "WORLD";
  annualFee: number;
  feeWaiverCondition?: string;
  feeWaiverConditionBn?: string;
  interestRateMonthly?: number;
  interestRateAnnual?: number;
  interestFreeDays?: number;
  minIncome: number;
  isDualCurrency?: boolean;
  airportLoungeAccess?: boolean;
  loungeDetails?: string;
  loungeDetailsBn?: string;
  rewardType?: "CASHBACK" | "REWARDS" | "MILES";
  rewardSummary?: string;
  rewardSummaryBn?: string;
  zeroPctEmiAvailable?: boolean;
  maxEmiMonths?: number;
  contactless?: boolean;
  isShariah?: boolean;
  cardColor?: string;
  features: string[];
  featuresBn: string[];
  popularity?: number;
};

export type LoanSeed = {
  slug: string;
  name: string;
  nameBn: string;
  loanType: "PERSONAL" | "HOME" | "AUTO" | "EDUCATION";
  interestRateMin: number;
  interestRateMax: number;
  minAmount: number;
  maxAmount: number;
  minTenureMonths: number;
  maxTenureMonths: number;
  processingFeePct?: number;
  minIncome: number;
  isShariah?: boolean;
  features: string[];
  featuresBn: string[];
  popularity?: number;
};

export const CREDIT_CARDS_DATA: { bankSlug: string; cards: CreditCardSeed[] }[] = [
  {
    bankSlug: "the-city-bank",
    cards: [
      {
        slug: "city-amex-platinum",
        name: "City Bank American Express Platinum Credit Card",
        nameBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "AMEX",
        tier: "PLATINUM",
        annualFee: 10000,
        feeWaiverCondition: "100% annual fee waiver on 18 transactions in a year",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেনে বার্ষিক ফি শতভাগ মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 100000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited complimentary access to Balaka Lounge + Priority Pass for 1400+ international lounges",
        loungeDetailsBn: "বলাকা লাউঞ্জে আনলিমিটেড ফ্রি প্রবেশ এবং ১৪০০+ আন্তর্জাতিক লাউঞ্জের জন্য প্রায়োরিটি পাস",
        rewardType: "REWARDS",
        rewardSummary: "10 Membership Rewards points per ৳100 spent at grocery stores, 1 point elsewhere",
        rewardSummaryBn: "মুদি দোকানে প্রতি ১০০ টাকায় ১০ রিওয়ার্ড পয়েন্ট এবং অন্যান্য স্থানে ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#334155",
        popularity: 98,
        features: [
          "Complimentary companion dining at 5-star hotels (BOGO)",
          "Access to City Bank Amex Lounge at Hazrat Shahjalal International Airport",
          "FlexiBuy 0% interest EMI up to 36 months",
          "Comprehensive overseas travel and medical insurance up to $100,000",
        ],
        featuresBn: [
          "পাঁচ তারকা হোটেলে 'বাই ওয়ান গেট ওয়ান' বুফে সুবিধা",
          "শাহজালাল বিমানবন্দরে সিটি ব্যাংক অ্যাম্পেক্স লাউঞ্জ ব্যবহারের সুযোগ",
          "৩৬ মাস পর্যন্ত ফ্ল্যাক্সিবাই শূন্য শতাংশ সুদে ইএমআই",
          "১ লাখ ডলার পর্যন্ত বিদেশ ভ্রমণ ও চিকিৎসা বীমা সুবিধা",
        ],
      },
      {
        slug: "city-amex-gold",
        name: "City Bank American Express Gold Credit Card",
        nameBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস গোল্ড ক্রেডিট কার্ড",
        network: "AMEX",
        tier: "GOLD",
        annualFee: 3500,
        feeWaiverCondition: "Annual fee waived with 15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 45000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to City Bank Amex Domestic & International Lounges (5 visits/year)",
        loungeDetailsBn: "সিটি ব্যাংক অ্যামেক্স লাউঞ্জে বছরে ৫ বার বিনামূল্যে প্রবেশের সুযোগ",
        rewardType: "REWARDS",
        rewardSummary: "5 Membership Rewards points per ৳100 at leading dining and lifestyle brands",
        rewardSummaryBn: "জনপ্রিয় ডাইনিং ও লাইফস্টাইল ব্র্যান্ডে ১০০ টাকায় ৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#b45309",
        popularity: 88,
        features: [
          "Buy-one-get-one dining privileges at top Dhaka & Chittagong hotels",
          "0% EMI at 800+ merchant outlets across Bangladesh",
          "Dual currency global usage with passport endorsement",
        ],
        featuresBn: [
          "ঢাকা ও চট্টগ্রামের শীর্ষ হোটেলে বুফেতে একটি কিনলে একটি ফ্রি",
          "৮০০+ পার্টনার মার্চেন্টে শূন্য শতাংশ ইএমআই সুবিধা",
          "পাসপোর্ট এনডোর্সমেন্ট সাপেক্ষে দ্বৈত মুদ্রা আন্তর্জাতিক ব্যবহার",
        ],
      },
      {
        slug: "city-visa-platinum",
        name: "City Bank Visa Platinum Credit Card",
        nameBn: "সিটি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 4000,
        feeWaiverCondition: "Waived with 14 POS/e-commerce transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি পিওএস বা ই-কমার্স লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 free visits to Balaka Executive Lounge per calendar year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা এক্সিকিউটিভ লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "CASHBACK",
        rewardSummary: "1% flat cashback on all online and pos shopping",
        rewardSummaryBn: "সকল অনলাইন ও পিওএস কেনাকাটায় ১% ফ্ল্যাট ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1e3a8a",
        popularity: 82,
        features: [
          "Accepted globally at over 30 million Visa merchants",
          "Up to 50 days interest-free grace period",
          "Emergency card replacement worldwide",
        ],
        featuresBn: [
          "বিশ্বব্যাপী ৩ কোটির বেশি ভিসা মার্চেন্টে গ্রহণযোগ্য",
          "৫০ দিন পর্যন্ত সুদবিহীন গ্রেস পিরিয়ড",
          "জরুরি পরিস্থিতিতে বিশ্বব্যাপী কার্ড প্রতিস্থাপন সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "brac-bank",
    cards: [
      {
        slug: "brac-visa-signature",
        name: "BRAC Bank Visa Signature Credit Card",
        nameBn: "ব্র্যাক ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 8000,
        feeWaiverCondition: "100% annual fee waiver on minimum 18 transactions annually",
        feeWaiverConditionBn: "বছরে ন্যূনতম ১৮টি লেনদেনে ১০০% বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 100000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited free access to Balaka Executive Lounge + 6 complimentary visits via LoungeKey",
        loungeDetailsBn: "বলাকা লাউঞ্জে আনলিমিটেড ফ্রি প্রবেশ এবং লাউঞ্জকির মাধ্যমে ৬টি আন্তর্জাতিক ভিজিট",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points for every ৳50 spent, redeemable against annual fees and cash vouchers",
        rewardSummaryBn: "প্রতি ৫০ টাকা খরচে ২ রিওয়ার্ড পয়েন্ট, যা ফি মওকুফ বা ভাউচারে রূপান্তরযোগ্য",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#0f172a",
        popularity: 96,
        features: [
          "BOGO buffet at Radisson, Westin, Le Meridien, InterContinental",
          "PayFlex 0% interest instalment facility up to 36 months",
          "Free supplementary card for spouse and immediate family",
          "Travel accident cover up to ৳10,00,000",
        ],
        featuresBn: [
          "র‌্যাডিসন, ওয়েস্টিন, লা মেরিডিয়ান ও ইন্টারকন্টিনেন্টালে একটির সাথে একটি ফ্রি বুফে",
          "৩৬ মাস পর্যন্ত পেফ্লেক্স শূন্য শতাংশ সুদে কিস্তি",
          "পরিবারের জন্য বিনামূল্যে সাপ্লিমেন্টারি কার্ড",
          "১০ লাখ টাকা পর্যন্ত ভ্রমণ দুর্ঘটনা সুরক্ষা",
        ],
      },
      {
        slug: "brac-mastercard-world",
        name: "BRAC Bank Mastercard World Credit Card",
        nameBn: "ব্র্যাক ব্যাংক মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 9000,
        feeWaiverCondition: "Annual fee 100% waived on 18 transactions per year",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেনে ১০০% বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 120000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Executive Lounge + Mastercard Airport Experiences provided by LoungeKey",
        loungeDetailsBn: "বলাকা লাউঞ্জে আনলিমিটেড প্রবেশ এবং লাউঞ্জকি এয়ারপোর্ট সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "Double reward points on international spending and airline ticket bookings",
        rewardSummaryBn: "আন্তর্জাতিক ব্যয় ও বিমান টিকিট ক্রয়ে দ্বিগুণ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#7c2d12",
        popularity: 90,
        features: [
          "Mastercard Global Concierge 24/7 service",
          "Complimentary green fee rounds at selected international golf clubs",
          "Fast-track airport security and meet-and-greet discounts",
        ],
        featuresBn: [
          "২৪/৭ মাস্টারকার্ড গ্লোবাল কনসিয়ার্জ সেবা",
          "নির্বাচিত আন্তর্জাতিক গলফ কোর্সে বিশেষ সুবিধা",
          "বিমানবন্দরে ফাস্ট ট্র্যাক নিরাপত্তা ও মিট-অ্যান্ড-গ্রিট ডিসকাউন্ট",
        ],
      },
      {
        slug: "brac-visa-platinum",
        name: "BRAC Bank Visa Platinum Credit Card",
        nameBn: "ব্র্যাক ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Waived with 15 transactions annually",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "6 free visits per year to Balaka Executive Lounge (Dhaka)",
        loungeDetailsBn: "ঢাকা হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের বলাকা লাউঞ্জে বছরে ৬ বার ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1 reward point per ৳50 spend",
        rewardSummaryBn: "প্রতি ৫০ টাকা খরচে ১ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1e293b",
        popularity: 85,
        features: [
          "PayFlex 0% interest EMI at 1,000+ top lifestyle, electronic & jewelry shops",
          "Up to 50 days free credit period",
          "Instantly convert big purchases to EMIs via Astha App",
        ],
        featuresBn: [
          "১,০০০+ দোকানে পেফ্লেক্স শূন্য শতাংশ ইএমআই সুবিধা",
          "৫০ দিন পর্যন্ত সুদবিহীন ঋণ সুবিধা",
          "আস্থা অ্যাপে এক ক্লিকে যেকোনো বড় কেনাকাটা কিস্তিতে রূপান্তর",
        ],
      },
    ],
  },
  {
    bankSlug: "eastern-bank",
    cards: [
      {
        slug: "ebl-visa-signature",
        name: "EBL Visa Signature Credit Card",
        nameBn: "ইবিএল ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 7500,
        feeWaiverCondition: "Fee waived with 18 transactions or ৳2,00,000 yearly spend",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেন বা ২ লাখ টাকা ব্যয়ে বার্ষিক ফি সম্পূর্ণ মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 80000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited access to EBL SkyLounge at Dhaka & Chittagong airports + Priority Pass card",
        loungeDetailsBn: "ঢাকা ও চট্টগ্রাম বিমানবন্দরে ইবিএল স্কাইলাউঞ্জে সীমাহীন প্রবেশ ও প্রায়োরিটি পাস",
        rewardType: "REWARDS",
        rewardSummary: "Triple reward points on travel and hotel reservations worldwide",
        rewardSummaryBn: "বিশ্বব্যাপী হোটেল ও বিমান টিকিট বুকিংয়ে ৩ গুণ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#1e1b4b",
        popularity: 94,
        features: [
          "EBL SkyLounge exclusive access with companion",
          "EBL ZIP 0% interest instalment facility up to 36 months",
          "Buy 1 Get 1 complimentary dining at 40+ five-star restaurants",
          "Complimentary insurance coverage up to ৳20,00,000",
        ],
        featuresBn: [
          "সঙ্গীসহ ইবিএল স্কাইলাউঞ্জে প্রিভিউ প্রবেশাধিকার",
          "৩৬ মাস পর্যন্ত ইবিএল জিপ শূন্য শতাংশ সুদের কিস্তি",
          "৪০+ পাঁচ তারকা রেস্তোরাঁয় বাই ১ গেট ১ বুফে",
          "২০ লাখ টাকা পর্যন্ত প্রশংসনীয় দুর্ঘটনা বীমা কাভারেজ",
        ],
      },
      {
        slug: "ebl-mastercard-titanium",
        name: "EBL Mastercard Titanium Credit Card",
        nameBn: "ইবিএল মাস্টারকার্ড টাইটানিয়াম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "TITANIUM",
        annualFee: 3000,
        feeWaiverCondition: "Waived with 14 POS/online transactions annually",
        feeWaiverConditionBn: "বছরে ১৪টি পিওএস বা অনলাইন লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to EBL SkyLounge (4 visits per year)",
        loungeDetailsBn: "ইবিএল স্কাইলাউঞ্জে বছরে ৪ বার বিনামূল্যে প্রবেশের সুযোগ",
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳50 spent across all merchant outlets",
        rewardSummaryBn: "সকল মার্চেন্টে প্রতি ৫০ টাকা খরচে ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#374151",
        popularity: 86,
        features: [
          "Zero-interest EMI under EBL ZIP at 600+ partner outlets",
          "Dual-currency functionality for global e-commerce and POS",
          "Online account monitoring via EBL Connect mobile app",
        ],
        featuresBn: [
          "৬০০+ দোকানে শূন্য শতাংশ সুদে কিস্তি সুবিধা",
          "আন্তর্জাতিক অনলাইন ও সরাসরি কেনাকাটায় দ্বৈত মুদ্রা ব্যবহার",
          "ইবিএল কানেক্ট অ্যাপে তাৎক্ষণিক লেনদেন পর্যবেক্ষণ ও বিল পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "dutch-bangla-bank",
    cards: [
      {
        slug: "dbbl-nexus-mastercard-titanium",
        name: "DBBL Nexus-Mastercard Titanium Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-মাস্টারকার্ড টাইটানিয়াম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "TITANIUM",
        annualFee: 2500,
        feeWaiverCondition: "Waived with 15 POS transactions in a year",
        feeWaiverConditionBn: "বছরে ১৫টি পিওএস লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "3 complimentary visits per year to Balaka Executive Lounge",
        loungeDetailsBn: "বলাকা লাউঞ্জে বছরে ৩ বার ফ্রি প্রবেশের সুযোগ",
        rewardType: "CASHBACK",
        rewardSummary: "Special discount deals and cashback at 500+ shopping outlets",
        rewardSummaryBn: "৫০০+ আউটলেটে বিশেষ মূল্যছাড় ও ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#065f46",
        popularity: 84,
        features: [
          "Accepted in both Dutch-Bangla Nexus network and Mastercard global network",
          "Access to the largest ATM & FastTrack network in Bangladesh (5,000+ ATMs)",
          "InstaPay 0% interest EMI facility",
        ],
        featuresBn: [
          "নেক্সাস নেটওয়ার্ক ও বিশ্বব্যাপী মাস্টারকার্ড উভয় নেটওয়ার্কে কার্যকর",
          "দেশের বৃহত্তম এটিএম ও ফাস্টট্র্যাক নেটওয়ার্কের সুবিধা (৫,০০০+ এটিএম)",
          "ইনস্টাপে শূন্য শতাংশ সুদে কিস্তির সুবিধা",
        ],
      },
      {
        slug: "dbbl-nexus-visa-platinum",
        name: "DBBL Nexus-Visa Platinum Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Annual fee waived on 15 POS transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি পিওএস লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 45000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "5 free visits per year to Balaka Executive Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে বলাকা লাউঞ্জে বছরে ৫ বার ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Reward points on all POS and international transactions",
        rewardSummaryBn: "সকল পিওএস এবং আন্তর্জাতিক কেনাকাটায় রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#111827",
        popularity: 80,
        features: [
          "Dual-network compatibility: DBBL Nexus domestic + Visa international",
          "Free bill pay at all DBBL branches, ATMs and Rocket mobile banking",
          "Zero liability on lost or stolen cards upon immediate notification",
        ],
        featuresBn: [
          "দেশীয় নেক্সাস ও আন্তর্জাতিক ভিসা উভয় সুবিধা সংবলিত",
          "শাখা, এটিএম ও রকেট মোবাইল ব্যাংকিংয়ের মাধ্যমে বিনামূল্যে বিল পরিশোধ",
          "কার্ড হারিয়ে গেলে দ্রুত জানালে সম্পূর্ণ দায়মুক্তি",
        ],
      },
    ],
  },
  {
    bankSlug: "standard-chartered-bangladesh",
    cards: [
      {
        slug: "scb-visa-signature",
        name: "Standard Chartered Visa Signature Credit Card",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 10000,
        feeWaiverCondition: "Waived on minimum annual spend of ৳3,00,000",
        feeWaiverConditionBn: "বছরে ন্যূনতম ৩ লাখ টাকা ব্যয়ে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 120000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited free access to SCB Executive Lounge at HSIA + Priority Pass membership with 4 free overseas visits",
        loungeDetailsBn: "শাহজালাল বিমানবন্দরে এসসিবি এক্সিকিউটিভ লাউঞ্জে সীমাহীন প্রবেশ ও ৪টি ফ্রি আন্তর্জাতিক লাউঞ্জ ভিজিট",
        rewardType: "REWARDS",
        rewardSummary: "360° Rewards points with 2x points on overseas transactions and dining",
        rewardSummaryBn: "৩৬০° রিওয়ার্ড পয়েন্ট; আন্তর্জাতিক খরচ ও রেস্তোরাঁয় দ্বিগুণ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#044e54",
        popularity: 92,
        features: [
          "The Good Life privileges across 1,000+ dining, lifestyle and shopping partners",
          "KuchBhi on EMI — convert transactions above ৳3,000 into affordable instalments",
          "Travel and medical insurance cover up to $150,000",
        ],
        featuresBn: [
          "'দ্য গুড লাইফ' সুবিধার আওতায় ১০০০+ পার্টনার প্রতিষ্ঠানে বিশেষ ছাড়",
          "কিছুভি ইএমআই: ৩,০০০ টাকার বেশি কেনাকাটায় সহজ কিস্তি সুবিধা",
          "দেড় লাখ মার্কিন ডলার পর্যন্ত ভ্রমণ ও স্বাস্থ্য বীমা সুবিধা",
        ],
      },
      {
        slug: "scb-saadiq-platinum",
        name: "Standard Chartered Saadiq Platinum Credit Card",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড সাদিক প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived with 18 transactions annually",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 60000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to SCB Executive Lounge at Dhaka Airport",
        loungeDetailsBn: "ঢাকা বিমানবন্দরে এসসিবি এক্সিকিউটিভ লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1 Reward point per ৳50 spend, compliant with Shariah screening",
        rewardSummaryBn: "শরিয়াহ যাচাইকৃত প্রতি ৫০ টাকা ব্যয়ে ১ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#064e3b",
        popularity: 88,
        features: [
          "100% Shariah-compliant Islamic credit card based on Ujrah contract",
          "No compounding interest or late payment penalty interest",
          "Automatic merchant filtering ensuring strictly Halal transactions",
        ],
        featuresBn: [
          "উজরহ চুক্তির ভিত্তিতে শতভাগ শরিয়াহসম্মত ইসলামী ক্রেডিট কার্ড",
          "কোনো চক্রবৃদ্ধি সুদ বা বিলম্বিত জরিমানার সুদ নেই",
          "হারাম ও নিষিদ্ধ মার্চেন্টে স্বয়ংক্রিয় ট্রানজাকশন ব্লক সুরক্ষা",
        ],
      },
    ],
  },
  {
    bankSlug: "islami-bank-bangladesh",
    cards: [
      {
        slug: "ibbl-khidmah-gold",
        name: "IBBL Khidmah Credit Card Gold",
        nameBn: "আইবিবিএল খিদমাহ ক্রেডিট কার্ড গোল্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "Waived with 14 Halal transactions in a calendar year",
        feeWaiverConditionBn: "বছরে ১৪টি হালাল লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "Halal rewards program with discounts at 300+ Islamic boutique & lifestyle outlets",
        rewardSummaryBn: "৩০০+ ইসলামি ব্র্যান্ড ও লাইফস্টাইল আউটলেটে বিশেষ ছাড় ও সুবিধা",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#065f46",
        popularity: 89,
        features: [
          "Fully Shariah-compliant credit facility with zero interest (Riba-free)",
          "Fixed monthly service charge (Ujrah) — no interest compounding ever",
          "Dual-currency facility with USD endorsement for Hajj, Umrah & overseas travels",
        ],
        featuresBn: [
          "সম্পূর্ণ সুদবিহীন (রিবা-মুক্ত) শতভাগ শরিয়াহসম্মত ক্রেডিট সেবা",
          "নির্দিষ্ট মাসিক সেবা মাশুল (উজরহ) — কখনোই চক্রবৃদ্ধি নয়",
          "হজ, ওমরাহ ও বিদেশ ভ্রমণের জন্য ডলার এনডোর্সমেন্ট সুবিধা",
        ],
      },
      {
        slug: "ibbl-khidmah-platinum",
        name: "IBBL Khidmah Credit Card Platinum",
        nameBn: "আইবিবিএল খিদমাহ ক্রেডিট কার্ড প্ল্যাটিনাম",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 4000,
        feeWaiverCondition: "Waived with 18 transactions annually",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেনে বার্ষিক ফি সম্পূর্ণ মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 60000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Executive Lounge (4 visits per year)",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে বলাকা লাউঞ্জে বছরে ৪ বার ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Khidmah privilege rewards points redeemable against card maintenance charges",
        rewardSummaryBn: "খিদমাহ প্রিভিলেজ পয়েন্ট, যা কার্ড সার্ভিস চার্জ পরিশোধে ব্যবহার্য",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#022c22",
        popularity: 91,
        features: [
          "Certified by IBBL Central Shariah Supervisory Board",
          "0% Bai-Murabaha instalment scheme with top electronics and healthcare vendors",
          "Complimentary Takaful (Islamic insurance) coverage",
        ],
        featuresBn: [
          "আইবিবিএল কেন্দ্রীয় শরীয়াহ বোর্ড কর্তৃক প্রত্যয়িত ও অনুমোদিত",
          "শীর্ষ ইলেকট্রনিক্স ও হাসপাতালে ০% বাই-মুরাবাহা কিস্তি সুবিধা",
          "বিনামূল্যে তাকাফুল (ইসলামি জীবন বীমা) কভারেজ",
        ],
      },
    ],
  },
  {
    bankSlug: "prime-bank",
    cards: [
      {
        slug: "prime-visa-platinum",
        name: "Prime Bank Platinum Visa Credit Card",
        nameBn: "প্রাইম ব্যাংক প্ল্যাটিনাম ভিসা ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Waived with 15 transactions annually",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 free visits per year to Balaka Executive Lounge",
        loungeDetailsBn: "বলাকা এক্সিকিউটিভ লাউঞ্জে বছরে ৪ বার ফ্রি প্রবেশের সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳50 spend, redeemable for vouchers and fee waivers",
        rewardSummaryBn: "প্রতি ৫০ টাকা খরচে ১ পয়েন্ট, যা ভাউচার ও ফি মওকুফে রূপান্তরযোগ্য",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1e3a8a",
        popularity: 81,
        features: [
          "Prime 0% EMI at 500+ merchant partners nationwide",
          "Complimentary 1st year annual fee waiver with 3 transactions in 30 days",
          "Instant card lock and limits adjustment via MyPrime mobile app",
        ],
        featuresBn: [
          "সারাদেশে ৫০০+ পার্টনার শপে প্রাইম ০% ইএমআই সুবিধা",
          "প্রথম ৩০ দিনে ৩টি লেনদেনে প্রথম বছরের ফি সম্পূর্ণ ফ্রি",
          "মাইপ্রাইম অ্যাপের মাধ্যমে তাৎক্ষণিক কার্ড লক ও লিমিট নিয়ন্ত্রণ",
        ],
      },
    ],
  },
  {
    bankSlug: "bank-asia",
    cards: [
      {
        slug: "bank-asia-mastercard-titanium",
        name: "Bank Asia Mastercard Titanium Credit Card",
        nameBn: "ব্যাংক এশিয়া মাস্টারকার্ড টাইটানিয়াম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "TITANIUM",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 14 POS/Online transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি পিওএস বা অনলাইন লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "2 complimentary visits per year to Balaka Executive Lounge",
        loungeDetailsBn: "বলাকা লাউঞ্জে বছরে ২ বার ফ্রি প্রবেশের সুযোগ",
        rewardType: "CASHBACK",
        rewardSummary: "Cashback offers at prominent supermarkets and e-commerce platforms",
        rewardSummaryBn: "সুপারমার্কেট ও অনলাইন প্ল্যাটফর্মে আকর্ষণীয় ক্যাশব্যাক অফার",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1f2937",
        popularity: 79,
        features: [
          "Fast Track Smart EMI with flexible repayment tenures",
          "Zero card lost liability upon immediate reporting",
          "Bill payment facility through Bank Asia Smart App & 5000+ Agent Outlets",
        ],
        featuresBn: [
          "সহজ কিস্তিতে কেনাকাটার জন্য স্মার্ট ইএমআই সুবিধা",
          "কার্ড হারানোর সাথে সাথে রিপোর্ট করলে শূন্য আর্থিক দায়",
          "স্মার্ট অ্যাপ ও ৫,০০০+ এজেন্ট ব্যাংকিং আউটলেটে সহজ বিল পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "pubali-bank",
    cards: [
      {
        slug: "pubali-visa-platinum",
        name: "Pubali Bank Visa Platinum Credit Card",
        nameBn: "পূবালী ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "Waived with 15 transactions in a year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "3 visits per year to Balaka Executive Lounge at HSIA",
        loungeDetailsBn: "শাহজালাল বিমানবন্দরে বলাকা লাউঞ্জে বছরে ৩ বার ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Earn reward points with zero expiry as long as card is active",
        rewardSummaryBn: "মেয়াদের সীমাবদ্ধতাহীন রিওয়ার্ড পয়েন্ট অর্জনের সুবিধা",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1e293b",
        popularity: 76,
        features: [
          "Wide coverage across Pubali Bank's 500+ branches",
          "0% Easy Pay EMI at top domestic electronics brands",
          "Dual currency support with passport endorsement",
        ],
        featuresBn: [
          "পূবালী ব্যাংকের ৫০০+ শাখা নেটওয়ার্কের সরাসরি সহায়তা",
          "শীর্ষ ব্র্যান্ডে ০% ইজি পে কিস্তি সুবিধা",
          "পাসপোর্ট এনডোর্সমেন্টের মাধ্যমে দ্বৈত মুদ্রা সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "sonali-bank",
    cards: [
      {
        slug: "sonali-visa-gold",
        name: "Sonali Bank Visa Gold Credit Card",
        nameBn: "সোনালী ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 1500,
        feeWaiverCondition: "Waived with 12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "Lowest government bank interest rate and affordable fee structure",
        rewardSummaryBn: "সরকারি ব্যাংকের সবচেয়ে কম সুদ ও সাশ্রয়ী বার্ষিক ফি",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#065f46",
        popularity: 75,
        features: [
          "Special low interest rate of 18% p.a. (below 20% BB ceiling)",
          "Accessible to government employees and private salaried professionals",
          "Free bill payment at 1,230+ Sonali Bank branches nationwide",
        ],
        featuresBn: [
          "বাংলাদেশ ব্যাংকের ২০% সীমার নিচে মাত্র ১৮% বার্ষিক বিশেষ সুদের হার",
          "সরকারি চাকরিজীবী ও সাধারণ বেতনভোগীদের জন্য সহজ শর্তে প্রাপ্তি",
          "সারাদেশে ১,২৩০+ সোনালী ব্যাংক শাখায় সম্পূর্ণ বিনামূল্যে বিল পরিশোধ",
        ],
      },
    ],
  },
];

export const LOANS_DATA: { bankSlug: string; loans: LoanSeed[] }[] = [
  {
    bankSlug: "the-city-bank",
    loans: [
      {
        slug: "city-personal-loan",
        name: "City Bank Personal Loan",
        nameBn: "সিটি ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.5,
        minAmount: 50000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 35000,
        popularity: 92,
        features: [
          "Loan up to ৳20 Lakh without any cash collateral",
          "Quick approval within 48 to 72 business hours",
          "Reducing balance interest calculation",
          "Partial payment and early settlement options available",
        ],
        featuresBn: [
          "কোনো জামানত ছাড়াই ২০ লাখ টাকা পর্যন্ত ব্যক্তিগত ঋণ",
          "৪৮ থেকে ৭২ ঘণ্টার মধ্যে দ্রুত অনুমোদন প্রক্রিয়া",
          "ক্রমহ্রাসমান স্থিতিতে সুদ হিসাবায়ন",
          "আংশিক পরিশোধ ও যেকোনো সময় আগাম নিষ্পত্তির সুযোগ",
        ],
      },
      {
        slug: "city-home-loan",
        name: "City Bank Home Loan",
        nameBn: "সিটি ব্যাংক গৃহ ঋণ",
        loanType: "HOME",
        interestRateMin: 10.5,
        interestRateMax: 12.0,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 50000,
        popularity: 90,
        features: [
          "Finance up to 70% of apartment or house construction cost",
          "Flexible repayment tenure up to 25 years (300 months)",
          "Takeover / balance transfer facility from other banks with lower rates",
        ],
        featuresBn: [
          "অ্যাপার্টমেন্ট ক্রয় বা বাড়ি নির্মাণের ব্যয়ের সর্বোচ্চ ৭০% অর্থায়ন",
          "২৫ বছর (৩০০ মাস) পর্যন্ত দীর্ঘমেয়াদি পরিশোধের সুবিধা",
          "অন্য ব্যাংকের গৃহ ঋণ কম সুদে সিটি ব্যাংকে রূপান্তরের সুযোগ",
        ],
      },
      {
        slug: "city-auto-loan",
        name: "City Bank Auto Loan",
        nameBn: "সিটি ব্যাংক গাড়ি ঋণ",
        loanType: "AUTO",
        interestRateMin: 11.0,
        interestRateMax: 12.5,
        minAmount: 300000,
        maxAmount: 4000000,
        minTenureMonths: 12,
        maxTenureMonths: 72,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 85,
        features: [
          "Financing up to 50% for reconditioned and new vehicles",
          "Tenure up to 6 years with fixed and variable rate options",
          "Special tie-ups with leading automotive dealerships",
        ],
        featuresBn: [
          "নতুন ও রিকন্ডিশন্ড গাড়ির মূল্যের সর্বোচ্চ ৫০% অর্থায়ন",
          "৬ বছর পর্যন্ত মেয়াদে কিস্তি পরিশোধের সুযোগ",
          "দেশের শীর্ষ অটোমোবাইল ডিলারদের কাছ থেকে বিশেষ সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "brac-bank",
    loans: [
      {
        slug: "brac-now-personal-loan",
        name: "BRAC Bank Now Personal Loan",
        nameBn: "ব্র্যাক ব্যাংক নাও পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.75,
        interestRateMax: 13.5,
        minAmount: 100000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 95,
        features: [
          "Zero cash security required up to ৳20 Lakh",
          "Minimal paperwork for salaried employees and self-employed professionals",
          "Convenient repayment via auto-debit from your BRAC Bank account",
        ],
        featuresBn: [
          "২০ লাখ টাকা পর্যন্ত কোনো প্রকার সিকিউরিটি ডিপোজিট প্রয়োজন নেই",
          "চাকরিজীবী ও পেশাজীবীদের জন্য সহজ ও দ্রুত কাগজপত্র প্রক্রিয়া",
          "ব্র্যাক ব্যাংক হিসাব থেকে স্বয়ংক্রিয় ডেবিটের মাধ্যমে ঝামেলাহীন কিস্তি",
        ],
      },
      {
        slug: "brac-home-loan",
        name: "BRAC Bank Home Loan",
        nameBn: "ব্র্যাক ব্যাংক গৃহ ঋণ",
        loanType: "HOME",
        interestRateMin: 10.25,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 25000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 93,
        features: [
          "Financing up to ৳2.5 Crore for purchasing ready flats, construction, or renovation",
          "Repayment term up to 25 years",
          "Option to bundle loan with free property insurance guidance",
        ],
        featuresBn: [
          "ফ্ল্যাট ক্রয়, বাড়ি নির্মাণ বা সংস্কারে আড়াই কোটি টাকা পর্যন্ত অর্থায়ন",
          "২৫ বছর পর্যন্ত দীর্ঘ ও স্বস্তিদায়ক কিস্তির মেয়াদ",
          "সম্পত্তি বীমা সংক্রান্ত দিকনির্দেশনা ও পরামর্শ সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "eastern-bank",
    loans: [
      {
        slug: "ebl-executive-loan",
        name: "EBL Executive Personal Loan",
        nameBn: "ইবিএল এক্সিকিউটিভ পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 35000,
        popularity: 91,
        features: [
          "Unsecured personal credit facility with prompt processing",
          "Competitive interest rate on reducing balance",
          "Pre-approved loan offers for existing EBL payroll clients",
        ],
        featuresBn: [
          "জামানতবিহীন সহজ ও দ্রুত প্রক্রিয়াজাত ব্যক্তিগত ঋণ",
          "ক্রমহ্রাসমান মূলধনের ওপর প্রতিযোগিতামূলক সুদের হার",
          "ইবিএল পে-রোল অ্যাকাউন্টধারীদের জন্য প্রি-অ্যাপ্রুভড বিশেষ অফার",
        ],
      },
      {
        slug: "ebl-auto-loan",
        name: "EBL Fast Loan Auto",
        nameBn: "ইবিএল ফাস্ট লোন অটো",
        loanType: "AUTO",
        interestRateMin: 10.75,
        interestRateMax: 12.25,
        minAmount: 300000,
        maxAmount: 5000000,
        minTenureMonths: 12,
        maxTenureMonths: 72,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 87,
        features: [
          "Loan up to ৳50 Lakh for brand new or reconditioned cars",
          "Up to 6 years loan repayment tenure",
          "Instant in-principle sanction with basic financial documents",
        ],
        featuresBn: [
          "নতুন বা রিকন্ডিশন্ড গাড়ির জন্য সর্বোচ্চ ৫০ লাখ টাকা পর্যন্ত ঋণ",
          "পরিশোধের মেয়াদ সর্বোচ্চ ৬ বছর (৭২ মাস)",
          "প্রাথমিক কাগজপত্রে দ্রুত নীতিগত অনুমোদন",
        ],
      },
    ],
  },
  {
    bankSlug: "dutch-bangla-bank",
    loans: [
      {
        slug: "dbbl-personal-loan",
        name: "DBBL Retail Personal Loan",
        nameBn: "ডিবিবিএল রিটেইল ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 88,
        features: [
          "Simple documentation with fast verification",
          "Payable across 5,000+ DBBL ATMs, FastTracks and branches",
          "No hidden fees or unexpected charges",
        ],
        featuresBn: [
          "সহজ কাগজপত্র ও দ্রুত সত্যতা যাচাই প্রক্রিয়া",
          "ডিবিবিএলের ৫,০০০+ এটিএম, ফাস্টট্র্যাক ও শাখায় কিস্তি পরিশোধ সুবিধা",
          "কোনো গোপন খরচ বা অপ্রত্যাশিত চার্জ নেই",
        ],
      },
      {
        slug: "dbbl-home-loan",
        name: "DBBL Home Loan",
        nameBn: "ডিবিবিএল হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 89,
        features: [
          "Up to ৳2 Crore for home purchase or construction in any city of Bangladesh",
          "Low competitive interest rates starting at 10.00%",
          "Flexible repayment schedule matching depositor cash flows",
        ],
        featuresBn: [
          "দেশের যেকোনো শহরে ফ্ল্যাট বা বাড়ি নির্মাণের জন্য ২ কোটি টাকা পর্যন্ত ঋণ",
          "১০.০০% থেকে শুরু হওয়া প্রতিযোগিতামূলক সুদের হার",
          "গ্রাহকের সুবিধা অনুযায়ী নমনীয় কিস্তি পরিশোধের সুযোগ",
        ],
      },
    ],
  },
  {
    bankSlug: "standard-chartered-bangladesh",
    loans: [
      {
        slug: "scb-personal-loan",
        name: "Standard Chartered Personal Loan",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.25,
        interestRateMax: 12.75,
        minAmount: 150000,
        maxAmount: 2500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 50000,
        popularity: 94,
        features: [
          "Loan up to ৳25 Lakh with no security or guarantor required",
          "Straightforward digital application via SC Mobile",
          "Top-up loan facility for eligible clients after 6 regular instalments",
        ],
        featuresBn: [
          "কোনো জামানত বা গ্যারান্টার ছাড়া ২৫ লাখ টাকা পর্যন্ত ঋণ",
          "এসসি মোবাইল অ্যাপে ঘরে বসেই ডিজিটাল আবেদন",
          "৬টি নিয়মিত কিস্তির পর অতিরিক্ত টপ-আপ লোন সুবিধা",
        ],
      },
      {
        slug: "scb-home-loan",
        name: "Standard Chartered Home Loan",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড হোম লোন",
        loanType: "HOME",
        interestRateMin: 9.75,
        interestRateMax: 11.25,
        minAmount: 1000000,
        maxAmount: 30000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 75000,
        popularity: 95,
        features: [
          "Highest loan ceiling up to ৳3 Crore for residential properties",
          "Competitive premium pricing starting from 9.75% p.a.",
          "Doorstep legal vetting and advisory support",
        ],
        featuresBn: [
          "আবাসিক প্রপার্টির জন্য দেশের অন্যতম শীর্ষ ৩ কোটি টাকা পর্যন্ত অর্থায়ন",
          "৯.৭৫% থেকে শুরু হওয়া প্রিমিয়াম সুদের হার",
          "বাসায় এসে আইনি যাচাই ও পরামর্শ প্রদান সেবা",
        ],
      },
    ],
  },
  {
    bankSlug: "islami-bank-bangladesh",
    loans: [
      {
        slug: "ibbl-home-investment-hpsm",
        name: "IBBL Home Investment (HPSM)",
        nameBn: "আইবিবিএল গৃহ বিনিয়োগ (এইচপিএসএম)",
        loanType: "HOME",
        interestRateMin: 10.5,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 40000,
        isShariah: true,
        popularity: 93,
        features: [
          "Hire Purchase under Shirkatul Melk (HPSM) — strictly Riba-free Shariah model",
          "Joint ownership with bank gradually transferred to client upon payment completion",
          "No hidden compound interest or penalty charges",
        ],
        featuresBn: [
          "শিরকাতুল মেলক পদ্ধতিতে সম্পূর্ণ রিবা-মুক্ত শরিয়াহসম্মত বাড়ি বিনিয়োগ",
          "ব্যাংকের সাথে যৌথ মালিকানা, যা কিস্তি পরিশোধের সাথে গ্রাহকের নামে হস্তান্তরিত হয়",
          "কোনো অনৈতিক চক্রবৃদ্ধি সুদ বা জরিমানা নেই",
        ],
      },
      {
        slug: "ibbl-car-investment",
        name: "IBBL Car Investment (HPSM)",
        nameBn: "আইবিবিএল গাড়ি বিনিয়োগ (এইচপিএসএম)",
        loanType: "AUTO",
        interestRateMin: 11.0,
        interestRateMax: 12.0,
        minAmount: 300000,
        maxAmount: 4000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 35000,
        isShariah: true,
        popularity: 88,
        features: [
          "Islamic vehicle financing under Hire Purchase under Shirkatul Melk",
          "Ownership shares transferred month by month",
          "Takaful comprehensive coverage inclusion",
        ],
        featuresBn: [
          "ইসলামি পদ্ধতিতে হালাল গাড়ি ক্রয়ের অর্থায়ন সুবিধা",
          "মাসিক কিস্তির মাধ্যমে অংশের মালিকানা গ্রাহকের অনুকূলে স্থানান্তর",
          "ইসলামি তাকাফুল বীমার সুরক্ষা সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "sonali-bank",
    loans: [
      {
        slug: "sonali-personal-loan",
        name: "Sonali Bank Personal Loan for Govt & Salaried",
        nameBn: "সোনালী ব্যাংক পার্সোনাল লোন (সরকারি ও বেতনভুক্ত)",
        loanType: "PERSONAL",
        interestRateMin: 10.5,
        interestRateMax: 12.0,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 20000,
        popularity: 86,
        features: [
          "Lowest minimum income criteria (৳20,000/month)",
          "Preferential rate for teachers, government personnel and public corporation staff",
          "Nominal processing charge of only 0.25%",
        ],
        featuresBn: [
          "সবচেয়ে সহজ আয়ের যোগ্যতা (মাত্র ২০,০০০ টাকা/মাস)",
          "শিক্ষক, সরকারি কর্মকর্তা-কর্মচারী ও স্বায়ত্তশাসিত প্রতিষ্ঠানের জন্য বিশেষ ছাড়",
          "মাত্র ০.২৫% নামমাত্র প্রসেসিং ফি",
        ],
      },
      {
        slug: "sonali-rural-home-loan",
        name: "Sonali Bank Housing Loan",
        nameBn: "সোনালী ব্যাংক গৃহ নির্মাণ ঋণ",
        loanType: "HOME",
        interestRateMin: 9.5,
        interestRateMax: 11.0,
        minAmount: 300000,
        maxAmount: 10000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 30000,
        popularity: 87,
        features: [
          "Lowest home loan interest rate among commercial banks starting from 9.50%",
          "Available for both urban flats and semi-urban / district home constructions",
          "Up to 20 years repayment period",
        ],
        featuresBn: [
          "বাণিজ্যিক ব্যাংকের মধ্যে অন্যতম সর্বনিম্ন ৯.৫০% থেকে শুরু হওয়া সুদের হার",
          "শহরের ফ্ল্যাটসহ জেলা ও মফস্বল পর্যায়ে বাড়ি নির্মাণের জন্য সহজ ঋণ",
          "২০ বছর পর্যন্ত স্বস্তিদায়ক কিস্তির মেয়াদ",
        ],
      },
    ],
  },
  {
    bankSlug: "prime-bank",
    loans: [
      {
        slug: "prime-personal-loan",
        name: "Prime Bank Personal Loan",
        nameBn: "প্রাইম ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 82,
        features: [
          "Collateral-free personal financing up to ৳20 Lakh",
          "Fast processing with dedicated relationship managers",
          "Competitive pricing for doctors, engineers, and corporate executives",
        ],
        featuresBn: [
          "২০ লাখ টাকা পর্যন্ত জামানতবিহীন ঋণ সুবিধা",
          "কাস্টমার রিলেশনশিপ অফিসারের মাধ্যমে দ্রুত প্রসেসিং",
          "ডাক্তার, প্রকৌশলী ও কর্পোরেট নির্বাহীদের জন্য বিশেষ রেট",
        ],
      },
    ],
  },
  {
    bankSlug: "bank-asia",
    loans: [
      {
        slug: "bank-asia-consumer-loan",
        name: "Bank Asia Consumer Durables & Personal Loan",
        nameBn: "ব্যাংক এশিয়া কনজিউমার ও ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.75,
        interestRateMax: 13.25,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 80,
        features: [
          "Flexible personal loan for medical, travel, wedding, or renovation needs",
          "Easy instalment deduction through Bank Asia savings accounts",
          "Early repayment allowed without hefty penalties",
        ],
        featuresBn: [
          "চিকিৎসা, ভ্রমণ, বিয়ে বা গৃহ সংস্কারের জন্য সহজ শর্তে ঋণ",
          "ব্যাংক এশিয়া সঞ্চয়ী হিসাব থেকে স্বয়ংক্রিয় কিস্তি কর্তন",
          "অতিরিক্ত জরিমানা ছাড়াই যেকোনো সময় আগাম পরিশোধের সুযোগ",
        ],
      },
    ],
  },
  {
    bankSlug: "pubali-bank",
    loans: [
      {
        slug: "pubali-personal-loan",
        name: "Pubali Bank Personal Loan",
        nameBn: "পূবালী ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 78,
        features: [
          "Accessible across 500+ branches throughout Bangladesh",
          "Transparent interest rates and clear repayment schedules",
          "Fast tracking for existing Pubali account holders",
        ],
        featuresBn: [
          "সারাদেশে ৫০০+ শাখার মাধ্যমে সরাসরি সেবা প্রাপ্তি",
          "স্বচ্ছ সুদের হার ও পরিষ্কার কিস্তির শিডিউল",
          "পূবালী ব্যাংকের নিয়মিত গ্রাহকদের জন্য অগ্রাধিকার ভিত্তিতে অনুমোদন",
        ],
      },
    ],
  },
];
