export type CardDealSeed = {
  slug: string;
  title: string;
  titleBn: string;
  bankSlug: string;
  bankName: string;
  cardTier: string;
  category: "DINING_B1G1" | "HOTEL_B1G1" | "SHOPPING" | "TRAVEL" | "HEALTHCARE";
  merchantName: string;
  discountDetails: string;
  discountDetailsBn: string;
  city: "DHAKA" | "CHITTAGONG" | "SYLHET" | "NATIONWIDE";
  location?: string;
  bannerBadge?: string;
  terms?: string;
  termsBn?: string;
  popularity?: number;
};

export const CARD_DEALS_DATA: CardDealSeed[] = [
  {
    slug: "westin-dhaka-b1g1-buffet",
    title: "The Westin Dhaka: Buy 1 Get 1 Free Buffet",
    titleBn: "দ্য ওয়েস্টিন ঢাকা: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "the-city-bank",
    bankName: "The City Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "The Westin Dhaka (Seasonal Tastes)",
    discountDetails: "Buy 1 Get 1 Free Buffet for Breakfast, Lunch & Dinner at Seasonal Tastes with City Bank Amex Platinum & Gold Cards.",
    discountDetailsBn: "সিটি ব্যাংক অ্যামেক্স কার্ড দিয়ে সিজনাল টেস্টসে বুফে ব্রেকফাস্ট, লাঞ্চ ও ডিনারে ১টি কিনলে ১টি ফ্রি।",
    city: "DHAKA",
    location: "Gulshan-2, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Prior reservation mandatory. Valid round the year.",
    termsBn: "অগ্রিম টেবিল বুকিং আবশ্যক। বছরজুড়ে কার্যকর।",
    popularity: 99,
  },
  {
    slug: "le-meridien-dhaka-b1g1",
    title: "Le Méridien Dhaka: Buy 1 Get 1 Buffet at Latest Recipe",
    titleBn: "লা মেরিডিয়ান ঢাকা: লেটেস্ট রেসিপিতে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "brac-bank",
    bankName: "BRAC Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Le Méridien Dhaka (Latest Recipe)",
    discountDetails: "Complimentary companion buffet dinner at Latest Recipe with BRAC Bank Visa Signature and Platinum credit cards.",
    discountDetailsBn: "ব্র্যাক ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডধারীদের জন্য লেটেস্ট রেসিপিতে সঙ্গীসহ ডিনার বুফে ফ্রি।",
    city: "DHAKA",
    location: "Airport Road, Nikunja-2, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "One card per table. Not applicable on blackout holiday dates.",
    termsBn: "প্রতি টেবিলে একটি কার্ড প্রযোজ্য। সরকারি ছুটির বিশেষ দিবসে প্রযোজ্য নাও হতে পারে।",
    popularity: 98,
  },
  {
    slug: "intercontinental-dhaka-b1g1",
    title: "InterContinental Dhaka: Buy 1 Get 1 Buffet at Elements",
    titleBn: "ইন্টারকন্টিনেন্টাল ঢাকা: এলিমেন্টসে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank (EBL)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "InterContinental Dhaka (Elements)",
    discountDetails: "Exclusive Buy 1 Get 1 Buffet Dinner for EBL Visa Signature, Mastercard Titanium & World Cardholders.",
    discountDetailsBn: "ইবিএল ভিসা সিগনেচার, টাইটানিয়াম ও ওয়ার্ল্ড কার্ডে এলিমেন্টসে এক্সক্লুসিভ ১টি কিনলে ১টি ফ্রি বুফে ডিনার।",
    city: "DHAKA",
    location: "1 Minto Road, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Available 7 days a week. Service charge and VAT applicable.",
    termsBn: "সপ্তাহের ৭ দিনই প্রযোজ্য। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 97,
  },
  {
    slug: "sheraton-dhaka-garden-kitchen-b1g1",
    title: "Sheraton Dhaka: Buy 1 Get 1 Buffet at The Garden Kitchen",
    titleBn: "শেরাটন ঢাকা: দ্য গার্ডেন কিচেনে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "standard-chartered-bangladesh",
    bankName: "Standard Chartered Bangladesh",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Sheraton Dhaka (The Garden Kitchen)",
    discountDetails: "Complimentary buffet lunch & dinner for guest with Standard Chartered Visa Signature & Priority cards.",
    discountDetailsBn: "স্ট্যান্ডার্ড চার্টার্ড ভিসা সিগনেচার ও প্রায়োরিটি কার্ডে গার্ডেন কিচেনে বুফে লাঞ্চ ও ডিনারে ১টি কিনলে ১টি ফ্রি।",
    city: "DHAKA",
    location: "Banani, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid on all days. Prior booking recommended.",
    termsBn: "সব দিন প্রযোজ্য। অগ্রিম বুকিং বাঞ্ছনীয়।",
    popularity: 96,
  },
  {
    slug: "radisson-blu-dhaka-brasserie-b1g1",
    title: "Radisson Blu Water Garden Dhaka: B1G1 Buffet Dinner",
    titleBn: "রেডিসন ব্লু ওয়াটার গার্ডেন ঢাকা: ১টি কিনলে ১টি ফ্রি ডিনার বুফে",
    bankSlug: "mutual-trust-bank",
    bankName: "Mutual Trust Bank (MTB)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Radisson Blu Water Garden (Water Garden Brasserie)",
    discountDetails: "Buy 1 Get 1 free international buffet dinner with MTB Visa Signature & Mastercard World cards.",
    discountDetailsBn: "এমটিবি ভিসা সিগনেচার ও মাস্টারকার্ড ওয়ার্ল্ডে ওয়াটার গার্ডেন ব্রাসেরিতে ১টি কিনলে ১টি ফ্রি ডিনার বুফে।",
    city: "DHAKA",
    location: "Airport Road, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Applicable on dinner buffet only.",
    termsBn: "শুধুমাত্র ডিনার বুফেতে প্রযোজ্য।",
    popularity: 95,
  },
  {
    slug: "amari-dhaka-amaya-b1g1",
    title: "Amari Dhaka: Buy 1 Get 1 Free Buffet at Amaya",
    titleBn: "আমারি ঢাকা: আমায়া ফুড গ্যালারিতে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "united-commercial-bank",
    bankName: "United Commercial Bank (UCB)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Amari Dhaka (Amaya Food Gallery)",
    discountDetails: "Buy 1 Get 1 Buffet Lunch & Dinner across 4 live Asian cooking stations with UCB Imperial cards.",
    discountDetailsBn: "ইউসিবি ইম্পেরিয়াল কার্ড দিয়ে আমায়া ফুড গ্যালারির ৪টি লাইভ এশিয়ান কিচেনে ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "DHAKA",
    location: "Gulshan-2, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Available Friday and Saturday dinner.",
    termsBn: "শুক্র ও শনিবারের ডিনারে প্রযোজ্য।",
    popularity: 94,
  },
  {
    slug: "renaissance-dhaka-bahar-b1g1",
    title: "Renaissance Dhaka Gulshan: B1G1 Buffet at Bahar",
    titleBn: "রেনেসাঁস ঢাকা গুলশান: বাহারে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "the-city-bank",
    bankName: "The City Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Renaissance Dhaka (Bahar Multicuisine)",
    discountDetails: "Buy 1 Get 1 Free Buffet for Breakfast, Lunch & Dinner with City Bank American Express Platinum cards.",
    discountDetailsBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস প্ল্যাটিনাম কার্ডে বাহার মাল্টিকুইজিন রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "DHAKA",
    location: "Gulshan-1, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Advance reservation required.",
    termsBn: "অগ্রিম টেবিল রিজার্ভেশন প্রয়োজন।",
    popularity: 93,
  },
  {
    slug: "radisson-blu-chattogram-b1g1",
    title: "Radisson Blu Chattogram Bay View: Buy 1 Get 1 Buffet",
    titleBn: "রেডিসন ব্লু চট্টগ্রাম বে ভিউ: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank (EBL)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Radisson Blu Chattogram (The Exchange)",
    discountDetails: "Buy 1 Get 1 Free International Buffet Dinner with EBL Visa Signature & Platinum Cards.",
    discountDetailsBn: "ইবিএল ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে দি এক্সচেঞ্জ রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি আন্তর্জাতিক ডিনার বুফে।",
    city: "CHITTAGONG",
    location: "SS Khaled Road, Lalkhan Bazar, Chattogram",
    bannerBadge: "Buy 1 Get 1",
    terms: "Daily dinner buffet.",
    termsBn: "প্রতিদিনের ডিনার বুফেতে প্রযোজ্য।",
    popularity: 92,
  },
  {
    slug: "grand-sylhet-hotel-b1g1",
    title: "Grand Sylhet Hotel & Resort: B1G1 Buffet & 40% Room Discount",
    titleBn: "গ্র্যান্ড সিলেট হোটেল অ্যান্ড রিসোর্ট: ১টি কিনলে ১টি ফ্রি বুফে ও ৪০% রুম ডিসকাউন্ট",
    bankSlug: "mutual-trust-bank",
    bankName: "Mutual Trust Bank (MTB)",
    cardTier: "ALL",
    category: "HOTEL_B1G1",
    merchantName: "Grand Sylhet Hotel & Resort",
    discountDetails: "Buy 1 Get 1 Buffet Dinner at Dhanshiri Restaurant + Flat 40% discount on room tariff with MTB cards.",
    discountDetailsBn: "এমটিবি কার্ডে ধানসিঁড়ি রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে এবং রুম ভাড়ায় ফ্ল্যাট ৪০% ডিসকাউন্ট।",
    city: "SYLHET",
    location: "Boroshala, Airport Road, Sylhet",
    bannerBadge: "40% OFF + B1G1",
    terms: "Subject to room availability.",
    termsBn: "রুম খালি থাকার সাপেক্ষে প্রযোজ্য।",
    popularity: 90,
  },
  {
    slug: "daraz-bangladesh-megasale-10pct",
    title: "Daraz Bangladesh: 10% Extra Savings on Mega Sales",
    titleBn: "দারাজ বাংলাদেশ: মেগা সেলে অতিরিক্ত ১০% সেভিংস",
    bankSlug: "brac-bank",
    bankName: "BRAC Bank",
    cardTier: "ALL",
    category: "SHOPPING",
    merchantName: "Daraz Bangladesh",
    discountDetails: "10% instant discount up to BDT 1,000 on online orders with BRAC Bank Visa and Mastercard Credit Cards.",
    discountDetailsBn: "ব্র্যাক ব্যাংক ভিসা ও মাস্টারকার্ড ক্রেডিট কার্ডে দারাজে অনলাইনে কেনাকাটায় ১০% (সর্বোচ্চ ১,০০০ টাকা) তাৎক্ষণিক ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "10% OFF",
    terms: "Minimum spend BDT 2,000. Valid during campaign periods.",
    termsBn: "ন্যূনতম ২,০০০ টাকার কেনাকাটায় প্রযোজ্য। ক্যাম্পেইন চলাকালীন কার্যকর।",
    popularity: 95,
  },
  {
    slug: "sharetrip-15pct-flight-discount",
    title: "ShareTrip: Up to 15% Discount on International Flight Tickets",
    titleBn: "শেয়ারট্রিপ: আন্তর্জাতিক বিমান টিকিট বেস ফেয়ারে ১৫% পর্যন্ত ছাড়",
    bankSlug: "standard-chartered-bangladesh",
    bankName: "Standard Chartered Bangladesh",
    cardTier: "SIGNATURE",
    category: "TRAVEL",
    merchantName: "ShareTrip",
    discountDetails: "Up to 15% discount on international flight base fares and 50% discount on domestic hotels with Standard Chartered cards.",
    discountDetailsBn: "স্ট্যান্ডার্ড চার্টার্ড কার্ডে আন্তর্জাতিক ফ্লাইটের বেস ফেয়ারে ১৫% পর্যন্ত এবং অভ্যন্তরীণ হোটেলে ৫০% পর্যন্ত ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Valid on online booking via ShareTrip app and website with promo code.",
    termsBn: "শেয়ারট্রিপ অ্যাপ ও ওয়েবসাইটে প্রোমোকোড ব্যবহারের মাধ্যমে প্রযোজ্য।",
    popularity: 91,
  },
  {
    slug: "gozayaan-flight-hotel-offer",
    title: "GoZayaan: 14% Off Air Tickets & 55% Off Luxury Resorts",
    titleBn: "গোযায়ান: বিমান টিকিটে ১৪% ও রিসোর্টে ৫৫% পর্যন্ত ছাড়",
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank (EBL)",
    cardTier: "ALL",
    category: "TRAVEL",
    merchantName: "GoZayaan",
    discountDetails: "Up to 14% discount on flights and up to 55% discount on partner resorts in Cox's Bazar & Sylhet with EBL cards.",
    discountDetailsBn: "ইবিএল কার্ডে বিমান টিকিটে ১৪% পর্যন্ত এবং কক্সবাজার ও সিলেটের রিসোর্টে ৫৫% পর্যন্ত ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "55% OFF",
    terms: "Discount auto-applied at checkout.",
    termsBn: "চেকআউটে কার্ড নাম্বার ইনপুট করলেই স্বয়ংক্রিয় ডিসকাউন্ট।",
    popularity: 89,
  },
  {
    slug: "evercare-hospital-20pct-health",
    title: "Evercare Hospital Dhaka & Chattogram: 20% Health Screening Discount",
    titleBn: "এভারকেয়ার হাসপাতাল: হেলথ স্ক্রিনিং প্যাকেজে ২০% ছাড়",
    bankSlug: "the-city-bank",
    bankName: "The City Bank",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "Evercare Hospital",
    discountDetails: "20% discount on comprehensive executive wellness checkup packages with City Bank Amex cards.",
    discountDetailsBn: "সিটি ব্যাংক অ্যামেক্স কার্ড দিয়ে এভারকেয়ার হাসপাতালের এক্সিকিউটিভ হেলথ চেকআপ প্যাকেজে ২০% ছাড়।",
    city: "NATIONWIDE",
    location: "Bashundhara, Dhaka & Chittagong",
    bannerBadge: "20% OFF",
    terms: "Prior appointment recommended. Applicable on investigations.",
    termsBn: "অগ্রিম অ্যাপয়েন্টমেন্ট কাম্য। প্যাথলজি ও রেডিওলজিতে প্রযোজ্য।",
    popularity: 88,
  },
];
