import type { LoanSeed, CreditCardSeed } from "./creditSeed";

export const ADDITIONAL_LOANS: { bankSlug: string; loans: LoanSeed[] }[] = [
  {
    bankSlug: "united-commercial-bank",
    loans: [
      {
        slug: "ucb-imperial-home-loan",
        name: "UCB Imperial Home Loan",
        nameBn: "ইউসিবি ইম্পেরিয়াল হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 1000000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 60000,
        popularity: 92,
        features: [
          "Financing up to 70% of property market value",
          "Flexible repayment terms up to 25 years",
          "Dedicated relationship manager and doorstep documentation",
        ],
        featuresBn: [
          "সম্পত্তির বাজারমূল্যের সর্বোচ্চ ৭০% পর্যন্ত অর্থায়ন",
          "২৫ বছর পর্যন্ত দীর্ঘমেয়াদি সুবিধাজনক কিস্তি পরিশোধের মেয়াদ",
          "নির্দিষ্ট রিলেশনশিপ ম্যানেজার ও বাসায় গিয়ে ডকুমেন্টেশন সেবা",
        ],
      },
      {
        slug: "ucb-upay-personal-loan",
        name: "UCB Express Personal Loan",
        nameBn: "ইউসিবি এক্সপ্রেস পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 35000,
        popularity: 89,
        features: [
          "Unsecured personal loan up to ৳20 Lakhs",
          "Fast approval within 48 hours for salaried professionals",
          "Convenient repayment via Upay MFS or auto-debit",
        ],
        featuresBn: [
          "কোনো জামানত ছাড়াই ২০ লাখ টাকা পর্যন্ত ব্যক্তিগত ঋণ",
          "বেতনভুক্ত চাকরিজীবীদের জন্য ৪৮ ঘণ্টায় দ্রুত অনুমোদন",
          "উপায় এমএফএস বা অটো-ডেবিটের মাধ্যমে সহজ কিস্তি পরিশোধ",
        ],
      },
      {
        slug: "ucb-auto-loan",
        name: "UCB Auto Loan",
        nameBn: "ইউসিবি অটো লোন",
        loanType: "AUTO",
        interestRateMin: 11.0,
        interestRateMax: 12.5,
        minAmount: 300000,
        maxAmount: 4000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 87,
        features: [
          "Up to 50% vehicle financing for brand-new and reconditioned cars",
          "Competitive rates tied to SMART benchmark",
          "Free fast-track motor insurance arrangement",
        ],
        featuresBn: [
          "নতুন ও রিকন্ডিশন্ড গাড়ির জন্য সর্বোচ্চ ৫০% অর্থায়ন",
          "স্মার্ট বেঞ্চমার্ক ভিত্তিক প্রতিযোগিতামূলক সুদের হার",
          "দ্রুত মোটর ইন্স্যুরেন্স সুবিধা অন্তর্ভুক্তি",
        ],
      },
    ],
  },
  {
    bankSlug: "mutual-trust-bank",
    loans: [
      {
        slug: "mtb-regular-home-loan",
        name: "MTB Apon Nibash Home Loan",
        nameBn: "এমটিবি আপন নিবাস হোম লোন",
        loanType: "HOME",
        interestRateMin: 9.75,
        interestRateMax: 11.25,
        minAmount: 1000000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 50000,
        popularity: 91,
        features: [
          "Apartment purchase, house construction, and renovation financing",
          "Takeover / balance transfer facility with zero prepayment penalty",
          "Competitive reducing-balance interest calculation",
        ],
        featuresBn: [
          "ফ্ল্যাট ক্রয়, বাড়ি নির্মাণ ও সংস্কারের জন্য সহজ ঋণ",
          "অন্য ব্যাংকের ঋণ স্থানান্তরে বিশেষ সুবিধা ও প্রিপেমেন্ট ফি মওকুফ",
          "প্রতিযোগিতামূলক ক্রমহ্রাসমান স্থিতিতে সুদ গণনা",
        ],
      },
      {
        slug: "mtb-personal-loan",
        name: "MTB Personal Loan",
        nameBn: "এমটিবি পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 12.75,
        minAmount: 100000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 88,
        features: [
          "Any-purpose personal financing up to ৳20 Lakhs",
          "No third-party mortgage required",
          "Special concessions for MTB payroll account holders",
        ],
        featuresBn: [
          "যেকোনো বৈধ ব্যক্তিগত প্রয়োজনে ২০ লাখ টাকা পর্যন্ত ঋণ",
          "কোনো মর্টগেজ বা অতিরিক্ত জামানতের প্রয়োজন নেই",
          "এমটিবি পে-রোল অ্যাকাউন্টধারীদের জন্য বিশেষ ছাড়",
        ],
      },
    ],
  },
  {
    bankSlug: "dhaka-bank",
    loans: [
      {
        slug: "dhaka-bank-amar-bari",
        name: "Dhaka Bank Amar Bari Home Loan",
        nameBn: "ঢাকা ব্যাংক আমার বাড়ি হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 89,
        features: [
          "Financing for ready flats, commercial spaces and independent homes",
          "Up to 20 years tenure with hassle-free legal vetting",
          "Flexible repayment schedule aligned with borrower cash flows",
        ],
        featuresBn: [
          "রেডি ফ্ল্যাট ও বাড়ি ক্রয়ের জন্য দীর্ঘমেয়াদি অর্থায়ন",
          "সহজ আইনি যাচাইসহ ২০ বছর পর্যন্ত পরিশোধের সুযোগ",
          "আয়ের সাথে মানানসই নমনীয় কিস্তি নির্ধারণ",
        ],
      },
      {
        slug: "dhaka-bank-personal-loan",
        name: "Dhaka Bank Personal Loan",
        nameBn: "ঢাকা ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 86,
        features: [
          "Quick processing within 3 business days",
          "Up to ৳15 Lakhs collateral-free loan",
          "Repayable in 12 to 60 equal monthly instalments",
        ],
        featuresBn: [
          "৩ কর্মদিবসের মধ্যে দ্রুত অনুমোদন প্রক্রিয়া",
          "১৫ লাখ টাকা পর্যন্ত সম্পূর্ণ জামানতবিহীন ঋণ",
          "১২ থেকে ৬০ মাসের সমপরিমাণ মাসিক কিস্তিতে পরিশোধযোগ্য",
        ],
      },
    ],
  },
  {
    bankSlug: "premier-bank",
    loans: [
      {
        slug: "premier-home-loan",
        name: "Premier Bank Home Loan",
        nameBn: "প্রিমিয়ার ব্যাংক হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.25,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 87,
        features: [
          "Apartment purchase and renovation loans across major divisional cities",
          "Attractive interest rates linked to prevailing SMART benchmarks",
          "Minimal documentation and prompt branch support",
        ],
        featuresBn: [
          "বিভাগীয় শহরগুলোতে ফ্ল্যাট ক্রয় ও সংস্কারে সাশ্রয়ী ঋণ",
          "স্মার্ট নির্দেশিকার সাথে সমন্বয়কৃত আকর্ষণীয় সুদের হার",
          "সহজ কাগজপত্র ও দ্রুত শাখা সেবা",
        ],
      },
      {
        slug: "premier-quick-personal-loan",
        name: "Premier Quick Personal Loan",
        nameBn: "প্রিমিয়ার কুইক পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.75,
        interestRateMax: 13.5,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 25000,
        popularity: 85,
        features: [
          "Emergency medical, education, wedding or travel funding",
          "Low minimum salary threshold (৳25,000)",
          "No hidden administrative penalties",
        ],
        featuresBn: [
          "চিকিৎসা, উচ্চশিক্ষা, বিয়ে বা ভ্রমণের জরুরি অর্থায়ন",
          "মাত্র ২৫,০০০ টাকা আয়ের ব্যক্তিদের জন্য সহজ আবেদন",
          "কোনো লুকায়িত অতিরিক্ত চার্জ নেই",
        ],
      },
    ],
  },
  {
    bankSlug: "jamuna-bank",
    loans: [
      {
        slug: "jamuna-apon-thikana",
        name: "Jamuna Apon Thikana Home Loan",
        nameBn: "যমুনা আপন ঠিকানা গৃহঋণ",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 86,
        features: [
          "Up to 70% of property cost financing",
          "Early settlement allowed with minimal penalty",
          "Coverage for both semi-pucca and modern high-rise apartments",
        ],
        featuresBn: [
          "প্রপার্টির মোট ব্যয়ের সর্বোচ্চ ৭০% পর্যন্ত অর্থায়ন",
          "স্বল্প চার্জে আগাম ঋণ পরিশোধের সুযোগ",
          "আধুনিক অ্যাপার্টমেন্ট ও সেমিপাকা বাড়ির নির্মাণ ঋণ",
        ],
      },
      {
        slug: "jamuna-easy-personal-loan",
        name: "Jamuna Easy Personal Loan",
        nameBn: "যমুনা ইজি পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 84,
        features: [
          "Collateral-free personal financing up to ৳15 Lakhs",
          "Fast approvals for confirmed corporate executives and doctors",
          "Automated monthly deductions via Jamuna internet banking",
        ],
        featuresBn: [
          "১৫ লাখ টাকা পর্যন্ত সম্পূর্ণ জামানতবিহীন ব্যক্তিগত ঋণ",
          "করপোরেট পেশাজীবী ও চিকিৎসকদের জন্য দ্রুত অনুমোদন",
          "যমুনা ইন্টারনেট ব্যাংকিংয়ের মাধ্যমে স্বয়ংস্ক্রিয় কিস্তি পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "trust-bank",
    loans: [
      {
        slug: "trust-nibash-home-loan",
        name: "Trust Bank Nibash Home Loan",
        nameBn: "ট্রাস্ট ব্যাংক নিবাস গৃহঋণ",
        loanType: "HOME",
        interestRateMin: 9.75,
        interestRateMax: 11.0,
        minAmount: 1000000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 90,
        features: [
          "Highly competitive housing rates for armed forces and civilians alike",
          "Longest tenure options up to 25 years",
          "Subsidized processing fees for payroll clients",
        ],
        featuresBn: [
          "প্রতিরক্ষা সদস্য ও সাধারণ নাগরিক উভয়ের জন্যই আকর্ষণীয় সুদের হার",
          "২৫ বছর পর্যন্ত দীর্ঘমেয়াদি কিস্তি সুবিধা",
          "পে-রোল গ্রাহকদের জন্য ভর্তুকিযুক্ত স্বল্প প্রসেসিং ফি",
        ],
      },
      {
        slug: "trust-defence-civilian-personal",
        name: "Trust Bank Any-Purpose Personal Loan",
        nameBn: "ট্রাস্ট ব্যাংক যেকোনো উদ্দেশ্যে পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.0,
        interestRateMax: 12.5,
        minAmount: 100000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 25000,
        popularity: 89,
        features: [
          "Up to ৳20 Lakhs with no third-party collateral",
          "Special priority fast-track processing for defence personnel",
          "Transparent pricing with no concealed charges",
        ],
        featuresBn: [
          "জামানত ছাড়া ২০ লাখ টাকা পর্যন্ত ব্যক্তিগত অর্থায়ন",
          "প্রতিরক্ষা বাহিনীর সদস্যদের জন্য অগ্রাধিকার ভিত্তিতে দ্রুত অনুমোদন",
          "কোনো গোপন খরচ ছাড়া স্বচ্ছ ব্যাংকিং হিসাব",
        ],
      },
    ],
  },
  {
    bankSlug: "southeast-bank",
    loans: [
      {
        slug: "southeast-bank-home-loan",
        name: "Southeast Bank Home Loan",
        nameBn: "সাউথইস্ট ব্যাংক হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 45000,
        popularity: 86,
        features: [
          "Tailored loans for flat purchase, extension, and home improvement",
          "Simple eligibility criteria for professionals and business owners",
          "Attractive balance transfer rates from other banks",
        ],
        featuresBn: [
          "ফ্ল্যাট ক্রয়, বাড়ি সম্প্রসারণ ও আধুনিকায়নে সাশ্রয়ী ঋণ",
          "চাকরিজীবী ও ব্যবসায়ীদের জন্য সহজ যোগ্যতার শর্ত",
          "অন্য ব্যাংক থেকে ঋণ স্থানান্তরে বিশেষ সুবিধা",
        ],
      },
      {
        slug: "southeast-personal-loan",
        name: "Southeast Bank Personal Loan",
        nameBn: "সাউথইস্ট ব্যাংক পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 84,
        features: [
          "Unsecured personal credit up to ৳15 Lakhs",
          "Competitive monthly reducing balance calculation",
          "Zero charges on partial loan prepayments after 12 months",
        ],
        featuresBn: [
          "১৫ লাখ টাকা পর্যন্ত সম্পূর্ণ জামানতবিহীন লোন",
          "প্রতিযোগিতামূলক ক্রমহ্রাসমান ব্যালেন্স ক্যালকুলেশন",
          "১২ মাস পর আংশিক আগাম পরিশোধে অতিরিক্ত ফি মওকুফ",
        ],
      },
    ],
  },
  {
    bankSlug: "mercantile-bank",
    loans: [
      {
        slug: "mercantile-apon-nibash",
        name: "Mercantile Bank Apon Nibash Housing Loan",
        nameBn: "মার্কেন্টাইল ব্যাংক আপন নিবাস হাউজিং লোন",
        loanType: "HOME",
        interestRateMin: 10.25,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 85,
        features: [
          "Complete financing package for residential flat acquisition",
          "Convenient tenure up to 20 years",
          "Transparent processing with in-house legal verification",
        ],
        featuresBn: [
          "আবাসিক ফ্ল্যাট কেনার জন্য পরিপূর্ণ আর্থিক প্যাকেজ",
          "২০ বছর পর্যন্ত সুবিধাজনক ঋণ পরিশোধের মেয়াদ",
          "সহজ আইনি যাচাইসহ সম্পূর্ণ স্বচ্ছ প্রসেসিং",
        ],
      },
      {
        slug: "mercantile-personal-loan",
        name: "Mercantile Bank Personal Loan",
        nameBn: "মার্কেন্টাইল ব্যাংক পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.75,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 28000,
        popularity: 83,
        features: [
          "Flexible personal loan up to ৳15 Lakhs",
          "Fast clearance for salaried professionals and teachers",
          "Automatic standing instruction payment integration",
        ],
        featuresBn: [
          "১৫ লাখ টাকা পর্যন্ত নমনীয় ব্যক্তিগত ঋণ",
          "বেতনভুক্ত পেশাজীবী ও শিক্ষকদের জন্য দ্রুত অনুমোদন",
          "অটোমেটিক স্ট্যান্ডিং ইনস্ট্রাকশন কিস্তি পরিশোধ সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "al-arafah-islami-bank",
    loans: [
      {
        slug: "aibl-bai-murabaha-real-estate",
        name: "AIBL Housing Investment (HPSM)",
        nameBn: "আল-আরাফাহ্ হাউজিং ইনভেস্টমেন্ট (এইচপিএসএম)",
        loanType: "HOME",
        interestRateMin: 10.5,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 40000,
        isShariah: true,
        popularity: 90,
        features: [
          "100% Shariah-compliant Shirkatul Melk housing investment",
          "Gradual transfer of property share to client upon each instalment",
          "No unethical compounding penalty charges",
        ],
        featuresBn: [
          "সম্পূর্ণ শরিয়াহসম্মত শিরকাতুল মেলক পদ্ধতিতে গৃহ অর্থায়ন",
          "প্রতি কিস্তির সাথে প্রপার্টির অংশের মালিকানা ক্রমান্বয়ে হস্তান্তর",
          "কোনো অনৈতিক চক্রবৃদ্ধি সুদ বা অন্যায্য জরিমানা নেই",
        ],
      },
      {
        slug: "aibl-auto-investment",
        name: "AIBL Car Investment (HPSM)",
        nameBn: "আল-আরাফাহ্ গাড়ি বিনিয়োগ (এইচপিএসএম)",
        loanType: "AUTO",
        interestRateMin: 11.25,
        interestRateMax: 12.5,
        minAmount: 300000,
        maxAmount: 4000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 40000,
        isShariah: true,
        popularity: 87,
        features: [
          "Islamic vehicle hire-purchase model for brand new and reconditioned cars",
          "Comprehensive Takaful insurance protection",
          "Transparent fixed profit rate throughout tenure",
        ],
        featuresBn: [
          "নতুন ও রিকন্ডিশন্ড গাড়ির জন্য ইসলামি ভাড়ায় ক্রয় বিনিয়োগ",
          "তাকাফুল ইসলামি সাধারণ বীমার সুরক্ষা সুবিধা",
          "পুরো মেয়াদে সম্পূর্ণ স্বচ্ছ ও পূর্বনির্ধারিত মুনাফার হার",
        ],
      },
    ],
  },
  {
    bankSlug: "shahjalal-islami-bank",
    loans: [
      {
        slug: "sjibl-housing-investment",
        name: "Shahjalal Housing Investment (HPSM)",
        nameBn: "শাহ্জালাল হাউজিং ইনভেস্টমেন্ট (এইচপিএসএম)",
        loanType: "HOME",
        interestRateMin: 10.25,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 45000,
        isShariah: true,
        popularity: 89,
        features: [
          "Shariah-certified Hire Purchase under Shirkatul Melk financing",
          "Up to 20 years flexible repayment duration",
          "Competitive profit rate strictly audited by Shariah supervisory board",
        ],
        featuresBn: [
          "শরিয়াহ সুপারভাইজরি বোর্ড অনুমোদিত শিরকাতুল মেলক বিনিয়োগ",
          "২০ বছর পর্যন্ত নমনীয় কিস্তি পরিশোধের সুবিধা",
          "সুদমুক্ত হালাল মুনাফার হারে বাড়ি ক্রয়ের সুযোগ",
        ],
      },
      {
        slug: "sjibl-car-investment",
        name: "Shahjalal Car Investment (HPSM)",
        nameBn: "শাহ্জালাল কার ইনভেস্টমেন্ট (এইচপিএসএম)",
        loanType: "AUTO",
        interestRateMin: 11.0,
        interestRateMax: 12.25,
        minAmount: 300000,
        maxAmount: 4000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 35000,
        isShariah: true,
        popularity: 86,
        features: [
          "Islamic auto finance for sedan, SUV and hybrid vehicles",
          "Up to 50% vehicle cost financing",
          "No usury or compounding delays",
        ],
        featuresBn: [
          "সিডান, এসইউভি ও হাইব্রিড গাড়ির জন্য ইসলামি অর্থায়ন",
          "গাড়ির বাজারমূল্যের সর্বোচ্চ ৫০% পর্যন্ত হালাল বিনিয়োগ",
          "কোনো প্রকার রিবা বা অন্যায্য বিলম্ব সুদ নেই",
        ],
      },
    ],
  },
  {
    bankSlug: "exim-bank",
    loans: [
      {
        slug: "exim-apon-ghor",
        name: "EXIM Apon Ghor Home Investment",
        nameBn: "এক্সিম আপন ঘর আবাসন বিনিয়োগ",
        loanType: "HOME",
        interestRateMin: 10.5,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 40000,
        isShariah: true,
        popularity: 88,
        features: [
          "Islamic housing investment under Izara wa Iqtina / HPSM",
          "Wide coverage for residential flats in Dhaka, Chattogram and Sylhet",
          "Fast-track documentation vetted by Shariah experts",
        ],
        featuresBn: [
          "ইজারা ওয়া ইকতিলা / এইচপিএসএম পদ্ধতিতে ইসলামি আবাসন অর্থায়ন",
          "ঢাকা, চট্টগ্রাম ও সিলেট শহরের আবাসিক ফ্ল্যাটের জন্য উপযোগী",
          "শরিয়াহ বিশেষজ্ঞদের তত্ত্বাবধানে দ্রুত ও স্বচ্ছ অনুমোদন",
        ],
      },
      {
        slug: "exim-sheba-personal",
        name: "EXIM Sheba Consumer Investment",
        nameBn: "এক্সিম সেবা কনজিউমার বিনিয়োগ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 12.75,
        minAmount: 100000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 30000,
        isShariah: true,
        popularity: 85,
        features: [
          "Shariah-compliant personal financing for household appliances, medical and travel",
          "Bai-Muajjal goods purchase model with transparent markup",
          "Easy instalment deduction from EXIM salary account",
        ],
        featuresBn: [
          "চিকিৎসা, উচ্চশিক্ষা ও গৃহস্থালী সামগ্রী ক্রয়ে ইসলামি ব্যক্তিগত অর্থায়ন",
          "বাই-মুয়াজ্জল পদ্ধতিতে স্পষ্ট লাভ নির্ধারণ",
          "এক্সিম স্যালারি অ্যাকাউন্ট থেকে সহজে কিস্তি পরিশোধের সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "social-islami-bank",
    loans: [
      {
        slug: "sibl-home-investment",
        name: "SIBL Housing Investment (HPSM)",
        nameBn: "এসআইবিএল আবাসন বিনিয়োগ (এইচপিএসএম)",
        loanType: "HOME",
        interestRateMin: 10.5,
        interestRateMax: 11.75,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.25,
        minIncome: 35000,
        isShariah: true,
        popularity: 87,
        features: [
          "Pure Shariah-compliant housing investment for city and peri-urban areas",
          "Shared equity transferred upon completion of instalments",
          "Low documentation fee and Islamic legal support",
        ],
        featuresBn: [
          "শহর ও উপশহরের জন্য সম্পূর্ণ শরিয়াহভিত্তিক আবাসন বিনিয়োগ",
          "কিস্তি পরিশোধের সাথে মালিকানার হিস্যা ক্রেতাকে হস্তান্তর",
          "স্বল্প ফি ও ইসলামি আইনি পরামর্শের সুবিধা",
        ],
      },
      {
        slug: "sibl-personal-investment",
        name: "SIBL Murabaha Consumer Finance",
        nameBn: "এসআইবিএল মুদারাবা কনজিউমার বিনিয়োগ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.25,
        minIncome: 25000,
        isShariah: true,
        popularity: 85,
        features: [
          "Murabaha post-import and household consumer goods purchase facility",
          "Fixed predetermined profit rate with no compounding penal interest",
          "Direct disbursement to vendor / merchant for Shariah authenticity",
        ],
        featuresBn: [
          "মুরাবাহা পদ্ধতিতে গৃহস্থালি ও প্রয়োজনীয় পণ্যের হালাল অর্থায়ন",
          "কোনো চক্রবৃদ্ধি বিলম্ব জরিমানা ছাড়া পূর্বনির্ধারিত মুনাফা",
          "শরিয়াহর বিশুদ্ধতা রক্ষায় সরাসরি বিক্রেতাকে মূল্য পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "ific-bank",
    loans: [
      {
        slug: "ific-aamar-bari",
        name: "IFIC Aamar Bari Home Loan",
        nameBn: "আইএফআইসি আমার বাড়ি হোম লোন",
        loanType: "HOME",
        interestRateMin: 9.75,
        interestRateMax: 11.25,
        minAmount: 500000,
        maxAmount: 20000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 35000,
        popularity: 91,
        features: [
          "Nationwide coverage across 1200+ IFIC Uposhakhas and branches",
          "Financing for construction, apartment purchase and floor expansion",
          "Repayment terms up to 25 years with reducing balance computation",
        ],
        featuresBn: [
          "১২০০+ উপশাখা ও শাখার মাধ্যমে সারাদেশে তৃণমূল পর্যায়ে সহজে হোম লোন",
          "বাড়ি নির্মাণ, ফ্ল্যাট ক্রয় ও ছাদ সম্প্রসারণে দীর্ঘমেয়াদি অর্থায়ন",
          "২৫ বছর পর্যন্ত দীর্ঘ মেয়াদ ও হ্রাসমান ব্যালেন্সে সুদ হিসাব",
        ],
      },
      {
        slug: "ific-shohoj-personal",
        name: "IFIC Shohoj Personal Loan",
        nameBn: "আইএফআইসি সহজ পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 2000000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 25000,
        popularity: 88,
        features: [
          "Unsecured loan available at any IFIC Uposhakha across Bangladesh",
          "Fast processing with minimal paperwork for salaried and self-employed",
          "Convenient repayment via IFIC Aamar Account",
        ],
        featuresBn: [
          "সারাদেশের যেকোনো আইএফআইসি উপশাখা থেকে সহজে জামানতবিহীন ঋণ",
          "বেতনভুক্ত ও ক্ষুদ্র ব্যবসায়ীদের জন্য দ্রুত প্রসেসিং",
          "আইএফআইসি আমার অ্যাকাউন্টের মাধ্যমে সহজ কিস্তি পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "ab-bank",
    loans: [
      {
        slug: "ab-bank-aashroy",
        name: "AB Bank Aashroy Home Loan",
        nameBn: "এবি ব্যাংক আশ্রয় হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 86,
        features: [
          "Pioneer private bank housing finance for residential properties",
          "Tenure up to 20 years with straightforward legal verification",
          "Takeover facility from other banks with concessionary fees",
        ],
        featuresBn: [
          "দেশের প্রথম বেসরকারি ব্যাংকের নির্ভরযোগ্য আবাসন অর্থায়ন",
          "২০ বছর পর্যন্ত মেয়াদ ও সহজ আইনি কাগজপত্র যাচাই",
          "অন্য ব্যাংকের ঋণ স্থানান্তরে ফি-তে বিশেষ ছাড়",
        ],
      },
      {
        slug: "ab-bank-personal-loan",
        name: "AB Bank Personal Loan",
        nameBn: "এবি ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 100000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 84,
        features: [
          "Unsecured credit up to ৳15 Lakhs for urgent personal goals",
          "Competitive rate tied to central bank guidelines",
          "Quick sanction for corporate executives",
        ],
        featuresBn: [
          "জরুরি ব্যক্তিগত প্রয়োজনে ১৫ লাখ টাকা পর্যন্ত জামানতহীন ঋণ",
          "কেন্দ্রীয় ব্যাংকের নির্দেশিকা অনুযায়ী স্বচ্ছ সুদের হার",
          "করপোরেট চাকরিজীবীদের জন্য দ্রুত অনুমোদন সুবিধা",
        ],
      },
    ],
  },
  {
    bankSlug: "community-bank",
    loans: [
      {
        slug: "community-nibash-home",
        name: "Community Bank Nibash Home Loan",
        nameBn: "কমিউনিটি ব্যাংক নিবাস হোম লোন",
        loanType: "HOME",
        interestRateMin: 9.75,
        interestRateMax: 11.25,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 35000,
        popularity: 89,
        features: [
          "Attractive housing loans for Bangladesh Police members and general public",
          "Tenure up to 25 years with reducing balance interest",
          "Low processing fees and prompt branch disbursement",
        ],
        featuresBn: [
          "বাংলাদেশ পুলিশ সদস্য ও সাধারণ নাগরিক উভয়ের জন্যই সুবিধাজনক হোম লোন",
          "২৫ বছর পর্যন্ত দীর্ঘ পরিশোধের মেয়াদ ও হ্রাসমান ব্যালেন্সে সুদ হিসাব",
          "স্বল্প প্রসেসিং ফি ও দ্রুত ঋণ ছাড়ের সুবিধা",
        ],
      },
      {
        slug: "community-personal-loan",
        name: "Community Bank Aspire Personal Loan",
        nameBn: "কমিউনিটি ব্যাংক অ্যাসপায়ার পার্সোনাল লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.25,
        interestRateMax: 12.75,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 25000,
        popularity: 88,
        features: [
          "Collateral-free personal credit up to ৳15 Lakhs",
          "Low salary requirement (৳25,000/month)",
          "Direct standing instructions via Community Cash mobile app",
        ],
        featuresBn: [
          "জামানত ছাড়া ১৫ লাখ টাকা পর্যন্ত ব্যক্তিগত ঋণ",
          "মাত্র ২৫,০০০ টাকা মাসিক বেতনের ব্যক্তিদের জন্য সহজ শর্ত",
          "কমিউনিটি ক্যাশ অ্যাপের মাধ্যমে সহজ স্বয়ংক্রিয় কিস্তি পরিশোধ",
        ],
      },
    ],
  },
  {
    bankSlug: "midland-bank",
    loans: [
      {
        slug: "midland-home-loan",
        name: "Midland Bank Home Loan",
        nameBn: "মিডল্যান্ড ব্যাংক হোম লোন",
        loanType: "HOME",
        interestRateMin: 10.0,
        interestRateMax: 11.5,
        minAmount: 500000,
        maxAmount: 15000000,
        minTenureMonths: 36,
        maxTenureMonths: 240,
        processingFeePct: 0.5,
        minIncome: 40000,
        popularity: 86,
        features: [
          "Financing for apartment purchase and house construction",
          "Digital application and tracking via midland online app",
          "Fast processing within 5 working days",
        ],
        featuresBn: [
          "ফ্ল্যাট ক্রয় ও বাড়ি নির্মাণের জন্য সাশ্রয়ী গৃহঋণ",
          "মিডল্যান্ড অনলাইন অ্যাপে ডিজিটাল আবেদন ও ট্র্যাকিং সুবিধা",
          "মাত্র ৫ কার্যদিবসের মধ্যে দ্রুত অনুমোদন প্রক্রিয়া",
        ],
      },
      {
        slug: "midland-personal-loan",
        name: "Midland Bank Personal Loan",
        nameBn: "মিডল্যান্ড ব্যাংক ব্যক্তিগত ঋণ",
        loanType: "PERSONAL",
        interestRateMin: 11.5,
        interestRateMax: 13.0,
        minAmount: 50000,
        maxAmount: 1500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 30000,
        popularity: 84,
        features: [
          "Unsecured personal credit up to ৳15 Lakhs",
          "Flexible repayment options from 12 to 60 months",
          "Minimal documentation for salaried individuals",
        ],
        featuresBn: [
          "১৫ লাখ টাকা পর্যন্ত সম্পূর্ণ জামানতবিহীন লোন সুবিধা",
          "১২ থেকে ৬০ মাসের নমনীয় কিস্তি পরিশোধের বিকল্প",
          "বেতনভুক্ত চাকরিজীবীদের জন্য ঝামেলাহীন দ্রুত কাগজপত্র যাচাই",
        ],
      },
    ],
  },
  {
    bankSlug: "hsbc-bangladesh",
    loans: [
      {
        slug: "hsbc-premier-home-loan",
        name: "HSBC Premier Home Loan",
        nameBn: "এইচএসবিসি প্রিমিয়ার হোম লোন",
        loanType: "HOME",
        interestRateMin: 9.5,
        interestRateMax: 11.0,
        minAmount: 2000000,
        maxAmount: 30000000,
        minTenureMonths: 36,
        maxTenureMonths: 300,
        processingFeePct: 0.5,
        minIncome: 100000,
        popularity: 96,
        features: [
          "Prestigious high-value home loan up to ৳3 Crore for prime residential properties",
          "Global cross-border wealth management and relationship support",
          "Special benchmark-linked preferential rate for HSBC Premier clients",
        ],
        featuresBn: [
          "অভিজাত আবাসিক সম্পত্তির জন্য দেশের অন্যতম শীর্ষ ৩ কোটি টাকা পর্যন্ত হোম লোন",
          "আন্তর্জাতিক মানের সম্পদ ব্যবস্থাপনা ও সার্বক্ষণিক রিলেশনশিপ সেবা",
          "এইচএসবিসি প্রিমিয়ার গ্রাহকদের জন্য বিশেষ অগ্রাধিকারমূলক সুদের হার",
        ],
      },
      {
        slug: "hsbc-personal-loan",
        name: "HSBC Personal Installment Loan",
        nameBn: "এইচএসবিসি পার্সোনাল ইনস্টলমেন্ট লোন",
        loanType: "PERSONAL",
        interestRateMin: 11.0,
        interestRateMax: 12.5,
        minAmount: 200000,
        maxAmount: 2500000,
        minTenureMonths: 12,
        maxTenureMonths: 60,
        processingFeePct: 0.5,
        minIncome: 60000,
        popularity: 93,
        features: [
          "Unsecured personal loan up to ৳25 Lakhs with transparent terms",
          "Fast digital sanctioning for multinational and corporate executives",
          "No hidden administrative penalties on planned repayments",
        ],
        featuresBn: [
          "স্বচ্ছ ব্যাংকিং নীতিতে ২৫ লাখ টাকা পর্যন্ত জামানতহীন ব্যক্তিগত ঋণ",
          "বহুজাতিক ও প্রতিষ্ঠিত করপোরেট নির্বাহীদের জন্য দ্রুত ডিজিটাল অনুমোদন",
          "কোনো অন্যায্য লুকানো ফি বা অতিরিক্ত জরিমানা নেই",
        ],
      },
    ],
  },
];

export const SIBL_CREDIT_CARDS: CreditCardSeed[] = [
  {
    slug: "sibl-visa-islamic-platinum",
    name: "SIBL Visa Islamic Platinum Credit Card",
    nameBn: "এসআইবিএল ভিসা ইসলামিক প্ল্যাটিনাম ক্রেডিট কার্ড",
    network: "VISA",
    tier: "PLATINUM",
    annualFee: 4000,
    feeWaiverCondition: "100% annual fee waiver on 15 transactions in a year",
    feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি সম্পূর্ণ মওকুফ",
    interestRateMonthly: 0,
    interestRateAnnual: 0,
    interestFreeDays: 50,
    minIncome: 50000,
    isDualCurrency: true,
    airportLoungeAccess: true,
    loungeDetails: "Complimentary access to Balaka Lounge at Hazrat Shahjalal International Airport",
    loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের বলাকা লাউঞ্জে ফ্রি প্রবেশাধিকার",
    rewardType: "REWARDS",
    rewardSummary: "Halal reward points redeemable against annual renewal fees and merchant vouchers",
    rewardSummaryBn: "হালাল রিওয়ার্ড পয়েন্ট যা বার্ষিক ফি সমন্বয় ও ভাউচারে রূপান্তরযোগ্য",
    zeroPctEmiAvailable: true,
    maxEmiMonths: 24,
    contactless: true,
    isShariah: true,
    cardColor: "#00693E",
    popularity: 90,
    features: [
      "Strictly Riba-free Ujrah-based Shariah credit card",
      "Complimentary domestic airport lounge privileges",
      "Worldwide Acceptance in BDT and USD under Bangladesh Bank travel quota",
    ],
    featuresBn: [
      "উজরহ (সেবামূল্য) ভিত্তিতে সম্পূর্ণ রিবা-মুক্ত ইসলামি ক্রেডিট কার্ড",
      "বিমানবন্দরে আরামদায়ক লাউঞ্জ ব্যবহারের বিশেষ সুবিধা",
      "বাংলাদেশ ব্যাংকের ট্রাভেল কোটায় বিশ্বজুড়ে টাকা ও ডলারে ব্যবহারযোগ্য",
    ],
  },
  {
    slug: "sibl-visa-classic-card",
    name: "SIBL Visa Islamic Gold Credit Card",
    nameBn: "এসআইবিএল ভিসা ইসলামিক গোল্ড ক্রেডিট কার্ড",
    network: "VISA",
    tier: "GOLD",
    annualFee: 2000,
    feeWaiverCondition: "100% annual fee waiver on 12 transactions in a year",
    feeWaiverConditionBn: "বছরে ১২টি লেনদেনে বার্ষিক ফি সম্পূর্ণ মওকুফ",
    interestRateMonthly: 0,
    interestRateAnnual: 0,
    interestFreeDays: 50,
    minIncome: 25000,
    isDualCurrency: true,
    airportLoungeAccess: false,
    rewardType: "REWARDS",
    rewardSummary: "Reward points on all POS and e-commerce shopping transactions",
    rewardSummaryBn: "সব ধরণের পিওএস ও অনলাইন কেনাকাটায় আকর্ষণীয় রিওয়ার্ড পয়েন্ট",
    zeroPctEmiAvailable: true,
    maxEmiMonths: 18,
    contactless: true,
    isShariah: true,
    cardColor: "#B45309",
    popularity: 85,
    features: [
      "Riba-free Islamic credit card with easy minimum income requirement",
      "0% profit EMI facilities across 150+ partner lifestyle stores",
      "SMS alerts and instant EMV chip security",
    ],
    featuresBn: [
      "স্বল্প আয়ের চাকরিজীবীদের জন্য সহজ শর্তে সুদমুক্ত ইসলামি কার্ড",
      "১৫০+ মার্চেন্টে ০% মুনাফায় সহজ কিস্তি (ইএমআই) সুবিধা",
      "ইএমভি চিপ ও এসএমএস অ্যালার্টের মাধ্যমে শতভাগ সুরক্ষিত লেনদেন",
    ],
  },
];
