/**
 * Extended list of scheduled Bangladeshi banks to provide complete coverage
 * of private commercial, Islamic, state-owned, and international banks in Bangladesh.
 */

export type AdditionalBankSeed = {
  slug: string;
  name: string;
  nameBn: string;
  shortName: string;
  category: "PRIVATE" | "ISLAMIC" | "STATE_OWNED" | "FOREIGN" | "SPECIALIZED";
  isShariah?: boolean;
  establishedYear: number;
  headquarters: string;
  branchCount: number;
  atmCount: number;
  website: string;
  swiftCode: string;
  brandColor: string;
  logoInitials: string;
  rating: number;
  reviewCount: number;
  mobileAppName: string;
  description: string;
  descriptionBn: string;
  savings: {
    slug: string;
    name: string;
    nameBn: string;
    interestRate: number;
    interestRateMax?: number;
    minOpeningBalance: number;
    minBalanceForInterest?: number;
    maintenanceFee?: number;
    debitCardAnnualFee?: number;
    freeChequebook?: boolean;
    freeDebitCard?: boolean;
    interestPayout?: string;
    dailyBalanceInterest?: boolean;
    onlineAccountOpening?: boolean;
    segment?: string;
    isShariah?: boolean;
    features: string[];
    featuresBn: string[];
    popularity?: number;
  }[];
  fdr: {
    slug: string;
    name: string;
    nameBn: string;
    minDeposit: number;
    maxDeposit?: number;
    interestPayout?: string;
    prematureEncashment?: boolean;
    autoRenewal?: boolean;
    loanAgainstFdrPct?: number;
    isShariah?: boolean;
    features: string[];
    featuresBn: string[];
    rates: [number, number][];
  }[];
};

export const EXTENDED_BANKS: AdditionalBankSeed[] = [
  {
    slug: "united-commercial-bank",
    name: "United Commercial Bank PLC (UCB)",
    nameBn: "ইউনাইটেড কমার্শিয়াল ব্যাংক পিএলসি",
    shortName: "UCB",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1983,
    headquarters: "Gulshan-1, Dhaka",
    branchCount: 224,
    atmCount: 550,
    website: "https://www.ucb.com.bd",
    swiftCode: "UCBLBDDH",
    brandColor: "#D32F2F",
    logoInitials: "UCB",
    rating: 4.2,
    reviewCount: 940,
    mobileAppName: "Upay / UCBnet",
    description: "One of Bangladesh's premier private commercial banks, known for high-tier Imperial retail banking, Upay MFS, and extensive card programs.",
    descriptionBn: "বাংলাদেশের অন্যতম শীর্ষস্থানীয় বেসরকারি বাণিজ্যিক ব্যাংক, যার প্রিমিয়াম রিটেইল ব্যাংকিং এবং সমৃদ্ধ কার্ড সুবিধা সুপরিচিত।",
    savings: [
      {
        slug: "ucb-smart-savings",
        name: "UCB Smart Savings",
        nameBn: "ইউসিবি স্মার্ট সঞ্চয়ী হিসাব",
        interestRate: 4.5,
        interestRateMax: 5.5,
        minOpeningBalance: 1000,
        features: ["High yield on daily balance", "Free Upay fund transfers", "Dual-currency Visa card"],
        featuresBn: ["দৈনিক স্থিতির উপর আকর্ষণীয় মুনাফা", "উপায়ে ফ্রি ফান্ড ট্রান্সফার", "ডুয়াল কারেন্সি ভিসা কার্ড"],
      },
    ],
    fdr: [
      {
        slug: "ucb-term-deposit",
        name: "UCB Fixed Term Deposit",
        nameBn: "ইউসিবি মেয়াদী আমানত",
        minDeposit: 10000,
        features: ["Up to 90% loan against FDR", "Auto-renewal facility"],
        featuresBn: ["এফডিআরের বিপরীতে ৯০% ঋণ সুবিধা", "অটো রিনিউয়াল সুবিধা"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "mutual-trust-bank",
    name: "Mutual Trust Bank PLC (MTB)",
    nameBn: "মিউচুয়াল ট্রাস্ট ব্যাংক পিএলসি",
    shortName: "MTB",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1999,
    headquarters: "Gulshan-1, Dhaka",
    branchCount: 120,
    atmCount: 310,
    website: "https://www.mutualtrustbank.com",
    swiftCode: "MTBLBDDH",
    brandColor: "#0D47A1",
    logoInitials: "MTB",
    rating: 4.3,
    reviewCount: 780,
    mobileAppName: "MTB Smart Banking",
    description: "Renowned for elite airport lounge access network in Bangladesh, superior credit card privileges, and digital banking innovation.",
    descriptionBn: "দেশের বিমানবন্দর লাউঞ্জ নেটওয়ার্ক, উন্নত ক্রেডিট কার্ড সুযোগ-সুবিধা এবং আধুনিক ডিজিটাল ব্যাংকিংয়ের জন্য সুপরিচিত।",
    savings: [
      {
        slug: "mtb-inspire-savings",
        name: "MTB Inspire Savings Account",
        nameBn: "এমটিবি ইন্সপায়ার সেভিংস",
        interestRate: 4.0,
        interestRateMax: 5.25,
        minOpeningBalance: 1000,
        features: ["Tiered daily balance interest", "Complimentary lounge visit voucher", "Mobile check-in"],
        featuresBn: ["দৈনিক ব্যালেন্সের উপর ধাপে ধাপে সুদ", "লাউঞ্জ ভিজিট ভাউচার", "মোবাইল চেক-ইন সুবিধা"],
      },
    ],
    fdr: [
      {
        slug: "mtb-fixed-deposit",
        name: "MTB General Fixed Deposit",
        nameBn: "এমটিবি ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["High return on maturity", "Premature encashment option"],
        featuresBn: ["মেয়াদান্তে সর্বোচ্চ রিটার্ন", "মেয়াদপূর্তির পূর্বে নগদায়ন সুবিধা"],
        rates: [[3, 8.75], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "dhaka-bank",
    name: "Dhaka Bank PLC",
    nameBn: "ঢাকা ব্যাংক পিএলসি",
    shortName: "Dhaka Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1995,
    headquarters: "Motijheel C/A, Dhaka",
    branchCount: 115,
    atmCount: 220,
    website: "https://www.dhakabankltd.com",
    swiftCode: "DHBLBDDH",
    brandColor: "#004D40",
    logoInitials: "DBL",
    rating: 4.1,
    reviewCount: 620,
    mobileAppName: "Dhaka Bank Go",
    description: "A solid corporate and retail powerhouse offering versatile consumer loan solutions and high-reward card products.",
    descriptionBn: "কর্পোরেট ও রিটেইল খাতে সুপ্রতিষ্ঠিত ব্যাংক, যা গ্রাহকদের বহুমুখী ঋণ ও কার্ড সুবিধা প্রদান করে।",
    savings: [
      {
        slug: "dhaka-bank-excel-savings",
        name: "Dhaka Bank Excel Savings",
        nameBn: "ঢাকা ব্যাংক এক্সেল সেভিংস",
        interestRate: 4.25,
        interestRateMax: 5.0,
        minOpeningBalance: 1000,
        features: ["Daily interest computation", "Free internet banking app", "Discount privileges"],
        featuresBn: ["দৈনিক ভিত্তিতে সুদ গণনা", "ফ্রি ইন্টারনেট ব্যাংকিং অ্যাপ", "বিভিন্ন আউটলেটে ডিসকাউন্ট"],
      },
    ],
    fdr: [
      {
        slug: "dhaka-bank-fdr",
        name: "Dhaka Bank Fixed Deposit",
        nameBn: "ঢাকা ব্যাংক ফিক্সড ডিপোজিট",
        minDeposit: 25000,
        features: ["Attractive profit slabs", "Fast processing"],
        featuresBn: ["আকর্ষণীয় সুদ হার", "দ্রুত প্রসেসিং সুবিধা"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "premier-bank",
    name: "The Premier Bank PLC",
    nameBn: "দ্য প্রিমিয়ার ব্যাংক পিএলসি",
    shortName: "Premier Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1999,
    headquarters: "Banani, Dhaka",
    branchCount: 135,
    atmCount: 180,
    website: "https://www.premierbankltd.com",
    swiftCode: "PRMRBDDH",
    brandColor: "#880E4F",
    logoInitials: "PBL",
    rating: 4.0,
    reviewCount: 510,
    mobileAppName: "Pmoney",
    description: "Fast-growing commercial bank known for customer-centric personal financing, competitive deposit rates, and Pmoney app.",
    descriptionBn: "গ্রাহকবান্ধব ব্যাংকিং, প্রতিযোগিতামূলক ডিপোজিট রেট এবং পি-মানি অ্যাপের জন্য পরিচিত।",
    savings: [
      {
        slug: "premier-general-savings",
        name: "Premier General Savings",
        nameBn: "প্রিমিয়ার জেনারেল সেভিংস",
        interestRate: 4.0,
        interestRateMax: 4.75,
        minOpeningBalance: 1000,
        features: ["ATM cash withdrawal nationwide", "SMS alert facility"],
        featuresBn: ["সারাদেশে এটিএম উত্তোলনের সুযোগ", "এসএমএস এলার্ট সুবিধা"],
      },
    ],
    fdr: [
      {
        slug: "premier-fixed-deposit",
        name: "Premier Fixed Deposit Receipt",
        nameBn: "প্রিমিয়ার মেয়াদী আমানত",
        minDeposit: 10000,
        features: ["High rate of return", "Auto rollover"],
        featuresBn: ["উচ্চ মুনাফার হার", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3, 8.5], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "jamuna-bank",
    name: "Jamuna Bank PLC",
    nameBn: "যমুনা ব্যাংক পিএলসি",
    shortName: "Jamuna Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2001,
    headquarters: "Shantinagar, Dhaka",
    branchCount: 165,
    atmCount: 320,
    website: "https://www.jamunabankbd.com",
    swiftCode: "JAMUBDDH",
    brandColor: "#1B5E20",
    logoInitials: "JBL",
    rating: 4.0,
    reviewCount: 460,
    mobileAppName: "JustPay",
    description: "Renowned for robust SME support, consumer loans, and both conventional and Islamic banking windows across Bangladesh.",
    descriptionBn: "সারাদেশে এসএমই ঋণ, পার্সোনাল ব্যাংকিং এবং কনভেনশনাল ও ইসলামিক উভয় ধারার নির্ভরযোগ্য সেবাদাতা।",
    savings: [
      {
        slug: "jamuna-classic-savings",
        name: "Jamuna Classic Savings",
        nameBn: "যমুনা ক্লাসিক সেভিংস",
        interestRate: 4.0,
        interestRateMax: 5.0,
        minOpeningBalance: 1000,
        features: ["Free JustPay app access", "Cheque book facility"],
        featuresBn: ["ফ্রি জাস্টপে অ্যাপ ব্যবহার", "চেকবই সুবিধা"],
      },
    ],
    fdr: [
      {
        slug: "jamuna-term-deposit",
        name: "Jamuna Term Deposit",
        nameBn: "যমুনা ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["Guaranteed return", "Quarterly interest option"],
        featuresBn: ["নিশ্চিত মুনাফা", "ত্রৈমাসিক সুদ উত্তোলনের সুযোগ"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "trust-bank",
    name: "Trust Bank PLC",
    nameBn: "ট্রাস্ট ব্যাংক পিএলসি",
    shortName: "Trust Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1999,
    headquarters: "Dhaka Cantonment, Dhaka",
    branchCount: 118,
    atmCount: 260,
    website: "https://www.tblbd.com",
    swiftCode: "TRBLBDDH",
    brandColor: "#004B87",
    logoInitials: "TBL",
    rating: 4.3,
    reviewCount: 890,
    mobileAppName: "Trust Money",
    description: "Highly trusted financial institution backed by the Army Welfare Trust, offering stellar consumer finance and premier credit cards.",
    descriptionBn: "আর্মি ওয়েলফেয়ার ট্রাস্ট পরিচালিত অত্যন্ত আস্থাশীল ব্যাংক, যা চমৎকার রিটেইল লোন ও কার্ড সেবা প্রদান করে।",
    savings: [
      {
        slug: "trust-smart-savers",
        name: "Trust Smart Savers Account",
        nameBn: "ট্রাস্ট স্মার্ট সেভার্স একাউন্ট",
        interestRate: 4.25,
        interestRateMax: 5.25,
        minOpeningBalance: 1000,
        features: ["Daily profit calculation", "Trust Money app", "Dual-currency debit card"],
        featuresBn: ["দৈনিক ব্যালেন্সে সুদ গণনা", "ট্রাস্ট মানি অ্যাপ", "ডুয়াল কারেন্সি ডেবিট কার্ড"],
      },
    ],
    fdr: [
      {
        slug: "trust-fixed-deposit",
        name: "Trust Bank Fixed Deposit",
        nameBn: "ট্রাস্ট ব্যাংক ফিক্সড ডিপোজিট",
        minDeposit: 25000,
        features: ["Loan against deposit up to 90%", "Flexible tenures"],
        featuresBn: ["ডিপোজিটের বিপরীতে ৯০% পর্যন্ত ঋণ", "সুবিধাজনক মেয়াদ"],
        rates: [[3, 8.75], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "southeast-bank",
    name: "Southeast Bank PLC",
    nameBn: "সাউথইস্ট ব্যাংক পিএলসি",
    shortName: "Southeast Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1995,
    headquarters: "Dilkusha C/A, Dhaka",
    branchCount: 135,
    atmCount: 220,
    website: "https://www.southeastbank.com.bd",
    swiftCode: "SEBDDH",
    brandColor: "#C62828",
    logoInitials: "SEB",
    rating: 4.1,
    reviewCount: 540,
    mobileAppName: "SEBL TeleBank",
    description: "Pioneer in remittance distribution, trade finance, and comprehensive retail cards with nationwide presence.",
    descriptionBn: "রেমিট্যান্স বিতরণ, বাণিজ্য অর্থায়ন এবং উন্নত কার্ড সেবায় দেশের শীর্ষস্থানীয় ব্যাংক।",
    savings: [
      {
        slug: "southeast-regular-savings",
        name: "Southeast Regular Savings Account",
        nameBn: "সাউথইস্ট নিয়মিত সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        interestRateMax: 4.75,
        minOpeningBalance: 1000,
        features: ["Any branch banking facility", "Free internet banking"],
        featuresBn: ["যেকোনো শাখায় ব্যাংকিং সুবিধা", "ফ্রি ইন্টারনেট ব্যাংকিং"],
      },
    ],
    fdr: [
      {
        slug: "southeast-fixed-deposit",
        name: "Southeast Fixed Deposit",
        nameBn: "সাউথইস্ট ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["High yield maturity", "Easy encashment"],
        featuresBn: ["মেয়াদান্তে উচ্চ রিটার্ন", "সহজ নগদায়ন"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "mercantile-bank",
    name: "Mercantile Bank PLC",
    nameBn: "মার্কেন্টাইল ব্যাংক পিএলসি",
    shortName: "Mercantile Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1999,
    headquarters: "Dilkusha C/A, Dhaka",
    branchCount: 152,
    atmCount: 190,
    website: "https://www.mblbd.com",
    swiftCode: "MBLBDDH",
    brandColor: "#0277BD",
    logoInitials: "MBL",
    rating: 4.0,
    reviewCount: 480,
    mobileAppName: "MBL Rainbow",
    description: "Customer-first bank offering tailored SME solutions, personal finance, and modern contactless card products.",
    descriptionBn: "গ্রাহকবান্ধব সেবা, সমৃদ্ধ এসএমই অর্থায়ন এবং আধুনিক কন্টাক্টলেস কার্ডের জন্য সমাদৃত।",
    savings: [
      {
        slug: "mercantile-regular-savings",
        name: "Mercantile Regular Savings",
        nameBn: "মার্কেন্টাইল রেগুলার সেভিংস",
        interestRate: 4.0,
        interestRateMax: 5.0,
        minOpeningBalance: 1000,
        features: ["MBL Rainbow app", "SMS banking alerts"],
        featuresBn: ["এমবিএল রেইনবো অ্যাপ সুবিধা", "এসএমএস নোটিফিকেশন"],
      },
    ],
    fdr: [
      {
        slug: "mercantile-fixed-deposit",
        name: "Mercantile Fixed Deposit",
        nameBn: "মার্কেন্টাইল ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["Safe investment", "Multiple payout modes"],
        featuresBn: ["নিরাপদ বিনিয়োগ", "একাধিক পদ্ধতিতে মুনাফা উত্তোলন"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "al-arafah-islami-bank",
    name: "Al-Arafah Islami Bank PLC",
    nameBn: "আল-আরাফাহ্ ইসলামী ব্যাংক পিএলসি",
    shortName: "Al-Arafah",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 1995,
    headquarters: "Purana Paltan, Dhaka",
    branchCount: 215,
    atmCount: 240,
    website: "https://www.aibl.com.bd",
    swiftCode: "ALIBBDDH",
    brandColor: "#00796B",
    logoInitials: "AIBL",
    rating: 4.2,
    reviewCount: 710,
    mobileAppName: "AIBL i-Banking",
    description: "100% Shariah-compliant Islamic bank with strict adherence to Islamic finance principles and Shariah credit cards.",
    descriptionBn: "শতভাগ শরীয়াহভিত্তিক পূর্ণাঙ্গ ইসলামিক ব্যাংক, যা হালাল বিনিয়োগ এবং ইসলামী কার্ড সুবিধা নিশ্চিত করে।",
    savings: [
      {
        slug: "aibl-mudaraba-savings",
        name: "Mudaraba Savings Deposit (MSD)",
        nameBn: "মুদারাবা সঞ্চয়ী আমানত",
        interestRate: 3.25,
        interestRateMax: 4.0,
        minOpeningBalance: 1000,
        isShariah: true,
        features: ["Halal profit sharing", "Shariah supervisory board approved"],
        featuresBn: ["হালাল মুনাফা অংশীদারিত্ব", "শরীয়াহ বোর্ডের অনুমোদন"],
      },
    ],
    fdr: [
      {
        slug: "aibl-mudaraba-term-deposit",
        name: "Mudaraba Term Deposit (MTDR)",
        nameBn: "মুদারাবা মেয়াদী আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Islamic profit sharing", "Flexible tenure"],
        featuresBn: ["ইসলামিক মুনাফা বণ্টন", "সুবিধাজনক মেয়াদ"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "shahjalal-islami-bank",
    name: "Shahjalal Islami Bank PLC",
    nameBn: "শাহ্‌জালাল ইসলামী ব্যাংক পিএলসি",
    shortName: "Shahjalal Islami",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 2001,
    headquarters: "Gulshan-1, Dhaka",
    branchCount: 140,
    atmCount: 160,
    website: "https://www.sjiblbd.com",
    swiftCode: "SJBLBDDH",
    brandColor: "#1565C0",
    logoInitials: "SJIBL",
    rating: 4.2,
    reviewCount: 590,
    mobileAppName: "SJIBL Net",
    description: "Progressive Islamic bank operating strictly under Islamic Shariah, recognized for ethical banking and digital services.",
    descriptionBn: "ইসলামী শরীয়াহর আলোকে পরিচালিত আধুনিক প্রযুক্তিনির্ভর ও বিশ্বস্ত ইসলামিক ব্যাংক।",
    savings: [
      {
        slug: "sjibl-mudaraba-savings",
        name: "SJIBL Mudaraba Savings",
        nameBn: "মুদারাবা সঞ্চয়ী হিসাব",
        interestRate: 3.25,
        interestRateMax: 4.0,
        minOpeningBalance: 1000,
        isShariah: true,
        features: ["Zero riba / interest", "ATM network across BD"],
        featuresBn: ["সুদমুক্ত শরীয়াহ ব্যাংকিং", "সারাদেশে এটিএম সুবিধা"],
      },
    ],
    fdr: [
      {
        slug: "sjibl-term-deposit",
        name: "SJIBL Mudaraba Term Deposit",
        nameBn: "মুদারাবা মেয়াদী আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Shariah profit rate", "Secured investment"],
        featuresBn: ["শরীয়াহ সম্মত মুনাফা", "নিরাপদ আমানত"],
        rates: [[3, 8.5], [6, 9.25], [12, 9.5]],
      },
    ],
  },
  {
    slug: "exim-bank",
    name: "Export Import Bank of Bangladesh PLC (EXIM Bank)",
    nameBn: "এক্সিম ব্যাংক পিএলসি",
    shortName: "EXIM Bank",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 1999,
    headquarters: "Gulshan-1, Dhaka",
    branchCount: 150,
    atmCount: 170,
    website: "https://www.eximbankbd.com",
    swiftCode: "EXIMBDDH",
    brandColor: "#2E7D32",
    logoInitials: "EXIM",
    rating: 4.1,
    reviewCount: 520,
    mobileAppName: "EXIM Pay",
    description: "Major Shariah-compliant bank with strong foreign trade financing and full Islamic retail products.",
    descriptionBn: "বৈদেশিক বাণিজ্য অর্থায়নে দেশের শীর্ষস্থানীয় এবং পূর্ণাঙ্গ শরীয়াহভিত্তিক ইসলামিক ব্যাংক।",
    savings: [
      {
        slug: "exim-mudaraba-savings",
        name: "EXIM Mudaraba Savings Deposit",
        nameBn: "এক্সিম মুদারাবা সঞ্চয়ী আমানত",
        interestRate: 3.0,
        interestRateMax: 3.75,
        minOpeningBalance: 1000,
        isShariah: true,
        features: ["Mudaraba profit principle", "Nationwide branch network"],
        featuresBn: ["মুদারাবা নীতিমালায় মুনাফা", "সারাদেশে শাখা নেটওয়ার্ক"],
      },
    ],
    fdr: [
      {
        slug: "exim-term-deposit",
        name: "EXIM Mudaraba Term Deposit",
        nameBn: "এক্সিম মেয়াদী আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Reliable halal returns", "Encashment flexibility"],
        featuresBn: ["হালাল নির্ভরযোগ্য মুনাফা", "নগদায়ন সুবিধা"],
        rates: [[3, 8.25], [6, 8.75], [12, 9.25]],
      },
    ],
  },
  {
    slug: "social-islami-bank",
    name: "Social Islami Bank PLC (SIBL)",
    nameBn: "সোশ্যাল ইসলামী ব্যাংক পিএলসি",
    shortName: "SIBL",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 1995,
    headquarters: "Kakrail, Dhaka",
    branchCount: 180,
    atmCount: 210,
    website: "https://www.siblbd.com",
    swiftCode: "SOISBDDH",
    brandColor: "#006064",
    logoInitials: "SIBL",
    rating: 3.9,
    reviewCount: 440,
    mobileAppName: "SIBL NOW",
    description: "Islamic bank dedicated to social banking, financial inclusion, micro-finance, and Shariah-compliant retail products.",
    descriptionBn: "সামাজিক ব্যাংকিং ও অন্তর্ভুক্তিমূলক আর্থিক সেবায় নিয়োজিত পূর্ণাঙ্গ ইসলামী ব্যাংক।",
    savings: [
      {
        slug: "sibl-mudaraba-savings",
        name: "SIBL Mudaraba Savings Account",
        nameBn: "এসআইবিএল মুদারাবা সঞ্চয়ী হিসাব",
        interestRate: 3.0,
        interestRateMax: 3.75,
        minOpeningBalance: 1000,
        isShariah: true,
        features: ["Shariah compliance", "SIBL NOW digital app"],
        featuresBn: ["শরীয়াহ সম্মত", "এসআইবিএল নাউ ডিজিটাল অ্যাপ"],
      },
    ],
    fdr: [
      {
        slug: "sibl-term-deposit",
        name: "SIBL Mudaraba Term Deposit",
        nameBn: "এসআইবিএল মেয়াদী আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Halal investment", "High reliability"],
        featuresBn: ["হালাল বিনিয়োগ", "উচ্চ নির্ভরযোগ্যতা"],
        rates: [[3, 8.25], [6, 8.75], [12, 9.25]],
      },
    ],
  },
  {
    slug: "ific-bank",
    name: "IFIC Bank PLC",
    nameBn: "আইএফআইসি ব্যাংক পিএলসি",
    shortName: "IFIC Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1976,
    headquarters: "Purana Paltan, Dhaka",
    branchCount: 1250,
    atmCount: 600,
    website: "https://www.ificbank.com.bd",
    swiftCode: "IFICBDDH",
    brandColor: "#B71C1C",
    logoInitials: "IFIC",
    rating: 4.1,
    reviewCount: 750,
    mobileAppName: "IFIC Aamar Bank",
    description: "Massive network with over 1,200 upazila sub-branches across Bangladesh, famed for the single-window 'IFIC Aamar Account'.",
    descriptionBn: "দেশের সর্ববৃহৎ উপশাখা নেটওয়ার্কযুক্ত ব্যাংক, যা তাদের বিখ্যাত 'আইএফআইসি আমার অ্যাকাউন্ট' এর জন্য সুপরিচিত।",
    savings: [
      {
        slug: "ific-aamar-account",
        name: "IFIC Aamar Account",
        nameBn: "আইএফআইসি আমার একাউন্ট",
        interestRate: 5.0,
        interestRateMax: 6.5,
        minOpeningBalance: 500,
        features: ["Savings + current account combined", "Daily interest", "Zero maintenance fee for students"],
        featuresBn: ["সঞ্চয়ী ও চলতি অ্যাকাউন্টের সমন্বয়", "দৈনিক ভিত্তিতে সুদ", "শিক্ষার্থীদের জন্য রক্ষণাবেক্ষণ ফি ফ্রি"],
      },
    ],
    fdr: [
      {
        slug: "ific-fixed-deposit",
        name: "IFIC Fixed Deposit",
        nameBn: "আইএফআইসি ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["Nationwide access", "Overdraft facility up to 90%"],
        featuresBn: ["সারাদেশে সেবা প্রাপ্তি", "৯০% পর্যন্ত ওভারড্রাফট সুবিধা"],
        rates: [[3, 8.75], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "ab-bank",
    name: "AB Bank PLC",
    nameBn: "এবি ব্যাংক পিএলসি",
    shortName: "AB Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1982,
    headquarters: "BCIC Bhaban, Dilkusha, Dhaka",
    branchCount: 105,
    atmCount: 160,
    website: "https://www.abbl.com",
    swiftCode: "ABBLBDDH",
    brandColor: "#01579B",
    logoInitials: "AB",
    rating: 4.0,
    reviewCount: 420,
    mobileAppName: "AB Direct",
    description: "The first private sector commercial bank in Bangladesh, offering decades of trust, corporate banking, and retail cards.",
    descriptionBn: "বাংলাদেশের প্রথম বেসরকারি বাণিজ্যিক ব্যাংক, চার দশকের অধিক সময়ের আস্থা ও ঐতিহ্যের প্রতীক।",
    savings: [
      {
        slug: "ab-smart-saver",
        name: "AB Smart Saver",
        nameBn: "এবি স্মার্ট সেভার",
        interestRate: 4.0,
        interestRateMax: 5.0,
        minOpeningBalance: 1000,
        features: ["Daily interest credit", "Free internet banking"],
        featuresBn: ["দৈনিক ব্যালেন্সে মুনাফা", "ফ্রি ইন্টারনেট ব্যাংকিং"],
      },
    ],
    fdr: [
      {
        slug: "ab-fixed-deposit",
        name: "AB Fixed Deposit",
        nameBn: "এবি ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["Assured competitive return", "Automatic renewal"],
        featuresBn: ["নিশ্চিত প্রতিযোগিতামূলক সুদ", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3, 8.5], [6, 9.0], [12, 9.5]],
      },
    ],
  },
  {
    slug: "community-bank",
    name: "Community Bank Bangladesh PLC",
    nameBn: "কমিউনিটি ব্যাংক বাংলাদেশ পিএলসি",
    shortName: "Community Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2019,
    headquarters: "Gulshan-1, Dhaka",
    branchCount: 30,
    atmCount: 80,
    website: "https://www.communitybankbd.com",
    swiftCode: "CMMBBDDH",
    brandColor: "#1A237E",
    logoInitials: "CB",
    rating: 4.2,
    reviewCount: 380,
    mobileAppName: "Community Cash",
    description: "Fast-growing digital bank founded by Bangladesh Police Kallyan Trust, offering sleek digital onboarding and competitive cards.",
    descriptionBn: "বাংলাদেশ পুলিশ কল্যাণ ট্রাস্ট প্রতিষ্ঠিত আধুনিক ডিজিটাল ব্যাংক, যা আকর্ষণীয় কার্ড ও ডিপোজিট সেবা দেয়।",
    savings: [
      {
        slug: "community-smart-savings",
        name: "Community Smart Savings",
        nameBn: "কমিউনিটি স্মার্ট সেভিংস",
        interestRate: 4.5,
        interestRateMax: 5.5,
        minOpeningBalance: 1000,
        features: ["High rate on daily balance", "Community Cash app with free transfers"],
        featuresBn: ["দৈনিক ভিত্তিতে আকর্ষণীয় মুনাফা", "কমিউনিটি ক্যাশ অ্যাপে ফ্রি ট্রান্সফার"],
      },
    ],
    fdr: [
      {
        slug: "community-fixed-deposit",
        name: "Community Fixed Deposit",
        nameBn: "কমিউনিটি ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        features: ["Guaranteed return", "High rate"],
        featuresBn: ["নিশ্চিত উচ্চ মুনাফার হার", "সহজ ঋণ সুবিধা"],
        rates: [[3, 8.75], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "midland-bank",
    name: "Midland Bank PLC",
    nameBn: "মিডল্যান্ড ব্যাংক পিএলসি",
    shortName: "Midland Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2013,
    headquarters: "Gulshan-2, Dhaka",
    branchCount: 40,
    atmCount: 65,
    website: "https://www.midlandbankbd.net",
    swiftCode: "MDLGBDDH",
    brandColor: "#00695C",
    logoInitials: "MDB",
    rating: 4.1,
    reviewCount: 290,
    mobileAppName: "midland online",
    description: "Known for technology-driven modern banking, midland online, and competitive retail products.",
    descriptionBn: "আধুনিক তথ্যপ্রযুক্তিনির্ভর ব্যাংকিং সেবা এবং মিডল্যান্ড অনলাইনের জন্য গ্রাহকপ্রিয়।",
    savings: [
      {
        slug: "midland-super-saver",
        name: "Midland Super Saver",
        nameBn: "মিডল্যান্ড সুপার সেভার",
        interestRate: 4.25,
        interestRateMax: 5.25,
        minOpeningBalance: 1000,
        features: ["Daily interest computation", "Free debit card for 1st year"],
        featuresBn: ["দৈনিক ব্যালেন্সে সুদ গণনা", "প্রথম বছর ফ্রি ডেবিট কার্ড"],
      },
    ],
    fdr: [
      {
        slug: "midland-term-deposit",
        name: "Midland Term Deposit",
        nameBn: "মিডল্যান্ড মেয়াদী আমানত",
        minDeposit: 10000,
        features: ["Flexible tenure", "Fast loan against FDR"],
        featuresBn: ["সুবিধাজনক মেয়াদ", "দ্রুত এফডিআর লোন সুবিধা"],
        rates: [[3, 8.5], [6, 9.25], [12, 9.75]],
      },
    ],
  },
  {
    slug: "hsbc-bangladesh",
    name: "The Hongkong and Shanghai Banking Corporation (HSBC Bangladesh)",
    nameBn: "এইচএসবিসি বাংলাদেশ",
    shortName: "HSBC",
    category: "FOREIGN",
    isShariah: false,
    establishedYear: 1996,
    headquarters: "Shanta Western Tower, Bir Uttam Mir Shawkat Sarak, Dhaka",
    branchCount: 15,
    atmCount: 40,
    website: "https://www.hsbc.com.bd",
    swiftCode: "HSBCBDDH",
    brandColor: "#DB0011",
    logoInitials: "HSBC",
    rating: 4.6,
    reviewCount: 1450,
    mobileAppName: "HSBC BD Mobile Banking",
    description: "International banking giant in Bangladesh, acclaimed for global Premier privileges, world-class credit cards, and multi-currency accounts.",
    descriptionBn: "আন্তর্জাতিক ব্যাংকিং জায়ান্ট, বিশ্বমানের প্রিমিয়ার প্রিভিলেজ, আন্তর্জাতিক ক্রেডিট কার্ড এবং বহুমুখী কারেন্সি সার্ভিসের জন্য খ্যাত।",
    savings: [
      {
        slug: "hsbc-premier-savings",
        name: "HSBC Premier Savings Account",
        nameBn: "এইচএসবিসি প্রিমিয়ার সেভিংস",
        interestRate: 3.5,
        interestRateMax: 4.5,
        minOpeningBalance: 100000,
        features: ["Global Premier status recognition", "Relationship manager", "Global emergency assistance"],
        featuresBn: ["বিশ্বব্যাপী প্রিমিয়ার স্ট্যাটাস সুবিধা", "ডেডিকেটেড রিলেশনশিপ ম্যানেজার", "আন্তর্জাতিক জরুরি সহায়তা"],
      },
    ],
    fdr: [
      {
        slug: "hsbc-time-deposit",
        name: "HSBC Time Deposit",
        nameBn: "এইচএসবিসি টাইম ডিপোজিট",
        minDeposit: 100000,
        features: ["Secured multinational trust", "Multi-currency placement options"],
        featuresBn: ["বহুজাতিক ব্যাংকের সর্বোচ্চ নিরাপত্তা", "বহুমুখী মুদ্রায় বিনিয়োগের সুযোগ"],
        rates: [[3, 7.5], [6, 8.0], [12, 8.5]],
      },
    ],
  },
];
