import { CreditCardSeed } from "./creditSeed";

export const EXTENDED_CREDIT_CARDS: { bankSlug: string; cards: CreditCardSeed[] }[] = [
  {
    bankSlug: "united-commercial-bank",
    cards: [
      {
        slug: "ucb-imperial-visa-signature",
        name: "UCB Imperial Visa Signature Credit Card",
        nameBn: "ইউসিবি ইম্পেরিয়াল ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "100% annual fee waiver on 15 transactions a year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে শতভাগ বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 75000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary unlimited access to Imperial Lounge at Hazrat Shahjalal International Airport + LoungeKey access",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের ইম্পেরিয়াল লাউঞ্জে ফ্রি আনলিমিটেড প্রবেশ ও লাউঞ্জ-কি সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 Reward points per ৳100 spent · Double points on overseas USD spending",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ রিওয়ার্ড পয়েন্ট · আন্তর্জাতিক খরচে দ্বিগুণ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#991B1B",
        features: [
          "Imperial airport lounge access with guest privilege",
          "Buy 1 Get 1 complimentary dining at 5-star hotels in Dhaka & Chittagong",
          "Zero renewal fee on 15 transactions",
          "Insurance coverage up to BDT 5,00,000",
        ],
        featuresBn: [
          "গেস্টসহ ইম্পেরিয়াল এয়ারপোর্ট লাউঞ্জ সুবিধা",
          "ঢাকা ও চট্টগ্রামের পাঁচতারা হোটেলে ১টি কিনলে ১টি ফ্রি বুফে ডাইনিং",
          "১৫টি ট্রানজ্যাকশনে বার্ষিক ফি শতভাগ মওকুফ",
          "৫ লাখ টাকা পর্যন্ত ফ্রি জীবনবীমা কভারেজ",
        ],
        popularity: 92,
      },
      {
        slug: "ucb-visa-platinum",
        name: "UCB Visa Platinum Credit Card",
        nameBn: "ইউসিবি ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Free renewal with 14 transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি লেনদেনে ফ্রি রিনিউয়াল",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka lounge visits annually at Dhaka Airport",
        loungeDetailsBn: "ঢাকা বিমানবন্দরে বছরে ৪ বার বলাকা লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "1 Point per ৳100 · 0% U-Plan EMI up to 24 months",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট · ২৪ মাস পর্যন্ত ০% ইউ-প্ল্যান ইএমআই",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#DC2626",
        features: [
          "B1G1 buffet dining at top restaurants",
          "Up to 24 months 0% interest EMI",
          "Dual currency global spend facility",
        ],
        featuresBn: [
          "শীর্ষ রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে",
          "২৪ মাস পর্যন্ত ০% সুদে সহজ কিস্তি",
          "বিশ্বব্যাপী ডুয়াল কারেন্সি ব্যবহারের সুবিধা",
        ],
        popularity: 84,
      },
    ],
  },
  {
    bankSlug: "mutual-trust-bank",
    cards: [
      {
        slug: "mtb-visa-signature",
        name: "MTB Visa Signature Credit Card",
        nameBn: "এমটিবি ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions in a year for 100% waiver",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 80000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Free unlimited access to MTB Air Lounges at Dhaka, Chittagong, Sylhet, Cox's Bazar, Saidpur & Jashore",
        loungeDetailsBn: "ঢাকা, চট্টগ্রাম, সিলেট, কক্সবাজার, সৈয়দপুর ও যশোর এমটিবি এয়ার লাউঞ্জে আনলিমিটেড ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "2 Points per ৳100 spent · High conversion rate for voucher redemption",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · আকর্ষণীয় ভাউচার রিডেম্পশন রেট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#1E3A8A",
        features: [
          "Nationwide MTB Air Lounge network (6 domestic airports)",
          "B1G1 buffet privileges at The Westin, Sheraton, Radisson & Le Méridien",
          "Priority Pass membership with 10 free international visits",
          "Flexible FlexiPay 0% EMI up to 36 months",
        ],
        featuresBn: [
          "সারাদেশে ৬টি বিমানবন্দরে এমটিবি এয়ার লাউঞ্জ সুবিধা",
          "ওয়েস্টিন, শেরাটন, রেডিসন ও লা মেরিডিয়ানে ১টি কিনলে ১টি ফ্রি বুফে",
          "১০টি আন্তর্জাতিক ভিজিটসহ প্রায়োরিটি পাস",
          "৩৬ মাস পর্যন্ত ০% সুদে ফ্লেক্সিপে ইএমআই সুবিধা",
        ],
        popularity: 95,
      },
      {
        slug: "mtb-angona-mastercard",
        name: "MTB Angona Mastercard Platinum (For Women)",
        nameBn: "এমটিবি অঙ্গনা মাস্টারকার্ড প্ল্যাটিনাম (নারীদের জন্য)",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 2500,
        feeWaiverCondition: "12 transactions annually for 100% waiver",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary MTB Air Lounge access at Dhaka & domestic airports",
        loungeDetailsBn: "ঢাকা ও অভ্যন্তরীণ বিমানবন্দরে এমটিবি এয়ার লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "5% cashback on beauty salons, parlor & lifestyle shopping",
        rewardSummaryBn: "বিউটি পার্লার, রূপচর্চা ও লাইফস্টাইল কেনাকাটায় ৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#9D174D",
        features: [
          "Special lifestyle & beauty discounts for women",
          "Free supplementary card for family",
          "Exciting B1G1 dining privileges across Dhaka",
        ],
        featuresBn: [
          "নারীদের জন্য রূপচর্চা ও ফ্যাশনে বিশেষ ক্যাশব্যাক ও ছাড়",
          "পরিবারের জন্য বিনামূল্যে সাপ্লিমেন্টারি কার্ড",
          "ঢাকাজুড়ে ১টি কিনলে ১টি ফ্রি ডাইনিং সুবিধা",
        ],
        popularity: 87,
      },
    ],
  },
  {
    bankSlug: "dhaka-bank",
    cards: [
      {
        slug: "dhaka-bank-visa-signature",
        name: "Dhaka Bank Visa Signature Credit Card",
        nameBn: "ঢাকা ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 5000,
        feeWaiverCondition: "Waiver upon 15 POS/E-commerce transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি পিওএস বা ই-কমার্স লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge and LoungeKey international airports",
        loungeDetailsBn: "বলাকা লাউঞ্জ এবং লাউঞ্জ-কির মাধ্যমে আন্তর্জাতিক বিমানবন্দরে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Earn 1.5x reward points on all supermarket and utility spends",
        rewardSummaryBn: "সুপারমার্কেট ও ইউটিলিটি বিল পরিশোধে ১.৫ গুণ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#064E3B",
        features: [
          "B1G1 dining at upscale restaurants in Dhaka",
          "Zero renewal fee with active card usage",
          "0% EMI swipe-it facility",
        ],
        featuresBn: [
          "ঢাকার অভিজাত রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে",
          "নিয়মিত ব্যবহারে বার্ষিক ফি শতভাগ মওকুফ",
          "০% সুদে সোয়াইপ-ইট ইএমআই কিস্তি সুবিধা",
        ],
        popularity: 83,
      },
    ],
  },
  {
    bankSlug: "trust-bank",
    cards: [
      {
        slug: "trust-bank-mastercard-world",
        name: "Trust Bank World Mastercard Credit Card",
        nameBn: "ট্রাস্ট ব্যাংক ওয়ার্ল্ড মাস্টারকার্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 7000,
        feeWaiverCondition: "100% waiver upon 18 transactions annually",
        feeWaiverConditionBn: "বছরে ১৮টি লেনদেনে শতভাগ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 90000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Executive Lounge visits + Priority Pass global lounge program",
        loungeDetailsBn: "বলাকা এক্সিকিউটিভ লাউঞ্জে আনলিমিটেড প্রবেশ এবং বিশ্বব্যাপী প্রায়োরিটি পাস সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "Double reward points on international airfare and hotel bookings",
        rewardSummaryBn: "আন্তর্জাতিক বিমান টিকিট ও হোটেল বুকিংয়ে দ্বিগুণ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#0F172A",
        features: [
          "World Mastercard concierge service 24/7",
          "Exclusive B1G1 hotel buffet privileges in Dhaka & Chittagong",
          "Up to ৳10,00,000 comprehensive travel accidental insurance",
          "0% Trust Pay EMI facility",
        ],
        featuresBn: [
          "সার্বক্ষণিক ওয়ার্ল্ড মাস্টারকার্ড কনসিয়ার্জ সুবিধা",
          "ঢাকা ও চট্টগ্রামে এক্সক্লুসিভ ১টি কিনলে ১টি ফ্রি বুফে ডাইনিং",
          "১০ লাখ টাকা পর্যন্ত আন্তর্জাতিক ট্রাভেল এক্সিডেন্ট ইন্স্যুরেন্স",
          "০% ট্রাস্ট পে ইএমআই সুবিধা",
        ],
        popularity: 89,
      },
    ],
  },
  {
    bankSlug: "premier-bank",
    cards: [
      {
        slug: "premier-visa-platinum",
        name: "Premier Bank Visa Platinum Credit Card",
        nameBn: "প্রিমিয়ার ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "100% waiver on 14 transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি লেনদেনে শতভাগ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at Hazrat Shahjalal International Airport",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের বলাকা লাউঞ্জে ফ্রি প্রবেশ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "1 Reward point per ৳100 spend",
        rewardSummaryBn: "প্রতি ১০০ টাকা খরচে ১ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#701A75",
        features: [
          "B1G1 dining offers in Dhaka",
          "Quick credit limit increase on clean history",
          "0% interest EMI at partner outlets",
        ],
        featuresBn: [
          "ঢাকায় বিভিন্ন রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি ডাইনিং",
          "ভালো ট্রানজ্যাকশন রেকর্ডে দ্রুত লিমিট বৃদ্ধির সুযোগ",
          "পার্টনার আউটলেটে ০% সুদে ইএমআই",
        ],
        popularity: 78,
      },
    ],
  },
  {
    bankSlug: "jamuna-bank",
    cards: [
      {
        slug: "jamuna-bank-visa-signature",
        name: "Jamuna Bank Visa Signature Credit Card",
        nameBn: "যমুনা ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 5000,
        feeWaiverCondition: "15 transactions a year for full waiver",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 60000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary Balaka lounge access at Dhaka Airport",
        loungeDetailsBn: "ঢাকা আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "Earn reward points on every transaction redeemable for cash vouchers",
        rewardSummaryBn: "প্রতিটি কেনাকাটায় পয়েন্ট যা ক্যাশ ভাউচারে রূপান্তরযোগ্য",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#14532D",
        features: [
          "B1G1 luxury hotel buffet packages",
          "Free dual-currency international usability",
          "Easy Installment Plan (EIP) at 0%",
        ],
        featuresBn: [
          "বিলাসবহুল হোটেলের বুফেতে ১টি কিনলে ১টি ফ্রি অফার",
          "আন্তর্জাতিক ডুয়াল কারেন্সি ব্যবহার সুবিধা",
          "০% সুদে ইজি ইনস্টলমেন্ট প্ল্যান (ইআইপি)",
        ],
        popularity: 79,
      },
    ],
  },
  {
    bankSlug: "southeast-bank",
    cards: [
      {
        slug: "southeast-visa-platinum",
        name: "Southeast Bank Visa Platinum Credit Card",
        nameBn: "সাউথইস্ট ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Full waiver on 15 transactions annually",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে শতভাগ বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 45000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary visits to Balaka Executive Lounge, Dhaka",
        loungeDetailsBn: "ঢাকার বলাকা এক্সিকিউটিভ লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "Reward points on POS & online payments",
        rewardSummaryBn: "পিওএস ও অনলাইন পেমেন্টে আকর্ষণীয় পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#7F1D1D",
        features: [
          "Buy 1 Get 1 buffet dining at selected luxury hotels",
          "Free supplementary card for immediate family",
          "Fast processing and easy documentation",
        ],
        featuresBn: [
          "নির্বাচিত বিলাসবহুল হোটেলে ১টি কিনলে ১টি ফ্রি বুফে",
          "পরিবারের জন্য বিনামূল্যে প্রথম সাপ্লিমেন্টারি কার্ড",
          "সহজ কাগজপত্র ও দ্রুত কার্ড ইস্যুর নিশ্চয়তা",
        ],
        popularity: 76,
      },
    ],
  },
  {
    bankSlug: "mercantile-bank",
    cards: [
      {
        slug: "mbl-visa-platinum",
        name: "Mercantile Bank Visa Platinum Credit Card",
        nameBn: "মার্কেন্টাইল ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "Waiver upon 14 transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Balaka Lounge access at Dhaka Airport",
        loungeDetailsBn: "ঢাকা আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "1 Reward Point per BDT 100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১টি রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#0C4A6E",
        features: [
          "B1G1 dining offers across partner hotels",
          "0% SimplePay EMI up to 24 months",
          "SMS alerts & contactless tap & pay",
        ],
        featuresBn: [
          "পার্টনার হোটেলে ১টি কিনলে ১টি ফ্রি ডাইনিং",
          "২৪ মাস পর্যন্ত ০% সিম্পলপে ইএমআই",
          "এসএমএস অ্যালার্ট ও কন্টাক্টলেস ট্যাপ-এন্ড-পে",
        ],
        popularity: 74,
      },
    ],
  },
  {
    bankSlug: "al-arafah-islami-bank",
    cards: [
      {
        slug: "aibl-tayyib-islamic-card",
        name: "AIBL Tayyib Islamic Credit Card (Shariah Compliant)",
        nameBn: "এআইবিএল তাইয়্যিব ইসলামিক ক্রেডিট কার্ড (শরীয়াহ সম্মত)",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "Waiver on 15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Balaka Lounge complimentary access for cardholder",
        loungeDetailsBn: "কার্ডধারীর জন্য বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Zero Interest / Riba · Monthly fixed Ujrah (maintenance fee) · Halal merchants only",
        rewardSummaryBn: "শতভাগ সুদমুক্ত · নির্ধারিত মাসিক উজরাহ ফি · শুধুমাত্র হালাল কেনাকাটায় গ্রহণযোগ্য",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#065F46",
        features: [
          "100% Shariah compliant (Ujrah model, zero compound interest)",
          "Auto blocks un-Islamic transactions (bars, gambling, casinos)",
          "B1G1 Halal certified buffet dining at 5-star hotels",
          "Dual currency travel quota endorsement",
        ],
        featuresBn: [
          "শতভাগ শরীয়াহভিত্তিক (উজরাহ মডেল, কোনো চক্রবৃদ্ধি সুদ নেই)",
          "অনৈতিক বা অনৈসলামিক লেনদেনে স্বয়ংক্রিয় ব্লক ব্যবস্থা",
          "পাঁচতারা হোটেলে হালাল সার্টিফায়েড ১টি কিনলে ১টি ফ্রি বুফে",
          "ডুয়াল কারেন্সি ট্রাভেল কোটা এন্ডোর্সমেন্ট সুবিধা",
        ],
        popularity: 90,
      },
    ],
  },
  {
    bankSlug: "shahjalal-islami-bank",
    cards: [
      {
        slug: "sjibl-souhardo-card",
        name: "SJIBL Souhardo Islamic Credit Card",
        nameBn: "শাহ্‌জালাল ইসলামী ব্যাংক সৌহার্দ্য ইসলামিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 2500,
        feeWaiverCondition: "12 transactions annually for full fee waiver",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge, Dhaka",
        loungeDetailsBn: "ঢাকার বলাকা লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "Zero interest · Shariah approved transaction model",
        rewardSummaryBn: "সম্পূর্ণ সুদমুক্ত · শরীয়াহ অনুমোদিত পেমেন্ট পদ্ধতি",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#1E40AF",
        features: [
          "100% Riba-free Shariah compliance",
          "B1G1 dining privileges across top hotels",
          "Halal travel & Umrah package EMI",
        ],
        featuresBn: [
          "শতভাগ সুদমুক্ত শরীয়াহ নিশ্চয়তা",
          "শীর্ষ হোটেলসমূহে ১টি কিনলে ১টি ফ্রি বুফে",
          "হালাল ট্রাভেল ও ওমরাহ প্যাকেজে সহজ কিস্তি",
        ],
        popularity: 82,
      },
    ],
  },
  {
    bankSlug: "exim-bank",
    cards: [
      {
        slug: "exim-islamic-credit-card",
        name: "EXIM Islamic Visa Platinum Credit Card",
        nameBn: "এক্সিম ইসলামিক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 2500,
        feeWaiverCondition: "Waiver upon 12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি ট্রানজ্যাকশনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Balaka Lounge access at Dhaka Airport",
        loungeDetailsBn: "ঢাকা বিমানবন্দরে বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "Shariah Ujrah based fee structure · Zero interest",
        rewardSummaryBn: "শরীয়াহ সম্মত উজরাহ কাঠামো · সম্পূর্ণ সুদমুক্ত",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#166534",
        features: [
          "Pure Shariah banking principles",
          "B1G1 dining in Dhaka & Chittagong",
          "Free SMS and e-statement services",
        ],
        featuresBn: [
          "বিশুদ্ধ শরীয়াহ ব্যাংকিং মূলনীতি",
          "ঢাকা ও চট্টগ্রামে ১টি কিনলে ১টি ফ্রি ডাইনিং",
          "বিনামূল্যে এসএমএস ও ই-স্টেটমেন্ট সুবিধা",
        ],
        popularity: 80,
      },
    ],
  },
  {
    bankSlug: "ific-bank",
    cards: [
      {
        slug: "ific-aamar-visa-platinum",
        name: "IFIC Aamar Visa Platinum Credit Card",
        nameBn: "আইএফআইসি আমার ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "14 transactions annually for 100% waiver",
        feeWaiverConditionBn: "বছরে ১৪টি লেনদেনে শতভাগ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at Dhaka Airport",
        loungeDetailsBn: "ঢাকা আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "REWARDS",
        rewardSummary: "1 Point per ৳100 · Easy redemption on utility bills",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট · ইউটিলিটি বিলে সহজ রিডেম্পশন",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#991B1B",
        features: [
          "B1G1 dining privileges across Bangladesh",
          "Access to over 1,200 IFIC sub-branches for card payment",
          "0% Aamar EMI at hundreds of electronics & lifestyle partners",
        ],
        featuresBn: [
          "সারাদেশে পার্টনার রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি ডাইনিং",
          "১২০০+ আইএফআইসি উপশাখায় কার্ডের বিল পরিশোধের সুবিধা",
          "ইলেকট্রনিক্স ও লাইফস্টাইল পার্টনারদের কাছে ০% আমার ইএমআই",
        ],
        popularity: 85,
      },
    ],
  },
  {
    bankSlug: "ab-bank",
    cards: [
      {
        slug: "ab-bank-visa-signature",
        name: "AB Bank Visa Signature Credit Card",
        nameBn: "এবি ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 5000,
        feeWaiverCondition: "15 transactions per year for 100% fee waiver",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে শতভাগ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary Balaka Lounge access and global LoungeKey support",
        loungeDetailsBn: "বলাকা লাউঞ্জে ফ্রি প্রবেশ ও আন্তর্জাতিক লাউঞ্জ-কি সমর্থন",
        rewardType: "REWARDS",
        rewardSummary: "2 Points per ৳100 · High travel redemption value",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · ট্রাভেলে আকর্ষণীয় রিডেম্পশন",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#075985",
        features: [
          "B1G1 hotel buffet dining at prestigious Dhaka hotels",
          "Zero renewal fee on 15 swipes",
          "0% AB Installment facility",
        ],
        featuresBn: [
          "ঢাকার নামিদামি হোটেলে ১টি কিনলে ১টি ফ্রি বুফে",
          "১৫টি সোয়াইপে বার্ষিক ফি শতভাগ মওকুফ",
          "০% এবি সহজ কিস্তি সুবিধা",
        ],
        popularity: 77,
      },
    ],
  },
  {
    bankSlug: "community-bank",
    cards: [
      {
        slug: "community-bank-visa-platinum",
        name: "Community Bank Visa Platinum Credit Card",
        nameBn: "কমিউনিটি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 2500,
        feeWaiverCondition: "12 transactions a year for full waiver",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Balaka Lounge access at Dhaka Airport",
        loungeDetailsBn: "ঢাকা বিমানবন্দরে বলাকা লাউঞ্জে প্রবেশের সুযোগ",
        rewardType: "CASHBACK",
        rewardSummary: "1% flat cashback on grocery supermarket spends",
        rewardSummaryBn: "গ্রোসারি ও সুপারমার্কেট কেনাকাটায় ফ্ল্যাট ১% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1E1B4B",
        features: [
          "B1G1 dining at popular restaurants",
          "Instant bill payment via Community Cash app",
          "Attractive 0% installment plans",
        ],
        featuresBn: [
          "জনপ্রিয় রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি ডাইনিং",
          "কমিউনিটি ক্যাশ অ্যাপে তাৎক্ষণিক বিল পরিশোধ",
          "আকর্ষণীয় ০% কিস্তি সুবিধা",
        ],
        popularity: 81,
      },
    ],
  },
  {
    bankSlug: "midland-bank",
    cards: [
      {
        slug: "midland-bank-visa-platinum",
        name: "Midland Bank Visa Platinum Credit Card",
        nameBn: "মিডল্যান্ড ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "Waiver upon 14 transactions per year",
        feeWaiverConditionBn: "বছরে ১৪টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge",
        loungeDetailsBn: "বলাকা লাউঞ্জে ফ্রি প্রবেশের সুযোগ",
        rewardType: "REWARDS",
        rewardSummary: "Reward points redeemable for gift vouchers",
        rewardSummaryBn: "উপহার ভাউচারে রূপান্তরযোগ্য রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#115E59",
        features: [
          "B1G1 dining privileges",
          "0% MDB Smart Pay EMI",
          "Paperless onboarding via midland online",
        ],
        featuresBn: [
          "১টি কিনলে ১টি ফ্রি ডাইনিং সুবিধা",
          "০% এমডিবি স্মার্ট পে ইএমআই",
          "মিডল্যান্ড অনলাইনের মাধ্যমে পেপারলেস প্রসেসিং",
        ],
        popularity: 75,
      },
    ],
  },
  {
    bankSlug: "hsbc-bangladesh",
    cards: [
      {
        slug: "hsbc-visa-platinum",
        name: "HSBC Visa Platinum Credit Card",
        nameBn: "এইচএসবিসি ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Annual fee waived on spending BDT 2,50,000 annually",
        feeWaiverConditionBn: "বছরে ২,৫০,০০০ টাকা ব্যয়ে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 75000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary Balaka Executive Lounge access + Priority Pass membership",
        loungeDetailsBn: "বলাকা এক্সিকিউটিভ লাউঞ্জে ফ্রি প্রবেশ এবং প্রায়োরিটি পাস মেম্বারশিপ",
        rewardType: "REWARDS",
        rewardSummary: "Reward points with global airline miles conversion (Singapore Airlines, Emirates, Qatar)",
        rewardSummaryBn: "বিশ্বখ্যাত এয়ারলাইন্সের মাইলস রূপান্তরযোগ্য রিওয়ার্ড পয়েন্ট (সিঙ্গাপুর, এমিরেটস, কাতার)",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#991B1B",
        features: [
          "Premier global concierge and travel insurance up to USD 100,000",
          "Exclusive B1G1 buffet dining at Westin, Radisson & Le Méridien",
          "Global merchant privileges in 40+ countries",
          "0% HSBC installment plan",
        ],
        featuresBn: [
          "আন্তর্জাতিক কনসিয়ার্জ ও ১ লাখ ডলার পর্যন্ত ট্রাভেল ইন্স্যুরেন্স",
          "ওয়েস্টিন, রেডিসন ও লা মেরিডিয়ানে ১টি কিনলে ১টি ফ্রি বুফে",
          "৪০টিরও বেশি দেশে আন্তর্জাতিক মার্চেন্ট ডিসকাউন্ট",
          "০% এইচএসবিসি সহজ কিস্তি সুবিধা",
        ],
        popularity: 96,
      },
    ],
  },
  {
    bankSlug: "the-city-bank",
    cards: [
      {
        slug: "city-amex-agora-card",
        name: "City Bank American Express Agora Card",
        nameBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস আগোরা কার্ড",
        network: "AMEX",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "100% waiver upon 15 transactions annually",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে শতভাগ বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to City Bank Amex Lounge at Hazrat Shahjalal International Airport",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরের সিটি ব্যাংক অ্যামেক্স লাউঞ্জে ফ্রি প্রবেশাধিকার",
        rewardType: "CASHBACK",
        rewardSummary: "Up to 5% savings & bonus points at Agora superstores across Bangladesh",
        rewardSummaryBn: "সারাদেশে আগোরা সুপারস্টোরে কেনাকাটায় ৫% পর্যন্ত সেভিংস ও বোনাস পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#B45309",
        features: [
          "Accelerated reward points on grocery and daily household spend",
          "City Bank Amex Lounge access at Dhaka airport",
          "Exclusive Amex Selects dining offers nationwide",
        ],
        featuresBn: [
          "নিত্যপ্রয়োজনীয় মুদি কেনাকাটায় দ্রুত রিওয়ার্ড পয়েন্ট অর্জন",
          "ঢাকা বিমানবন্দরে সিটি ব্যাংক অ্যামেক্স লাউঞ্জ ব্যবহারের সুযোগ",
          "সারাদেশে অ্যামেক্স সিলেক্টসের অধীনে এক্সক্লুসিভ ডাইনিং অফার",
        ],
        popularity: 91,
      },
    ],
  },
  {
    bankSlug: "eastern-bank",
    cards: [
      {
        slug: "ebl-skymiles-signature",
        name: "EBL SkyMiles Visa Signature Credit Card",
        nameBn: "ইবিএল স্কাইমাইলস ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions per year for 100% waiver",
        feeWaiverConditionBn: "বছরে ১৫টি ট্রানজ্যাকশনে শতভাগ বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 85000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited EBL Skylounge access at Dhaka, Chattogram & Cox's Bazar airports + Priority Pass",
        loungeDetailsBn: "ঢাকা, চট্টগ্রাম ও কক্সবাজার বিমানবন্দরে ইবিএল স্কাইলাউঞ্জে আনলিমিটেড প্রবেশ ও প্রায়োরিটি পাস",
        rewardType: "MILES",
        rewardSummary: "Earn SkyMiles on every BDT & USD spend · Direct airline ticket & travel redemption",
        rewardSummaryBn: "প্রতিটি দেশি ও বিদেশি ব্যয়ে স্কাইমাইলস অর্জন · বিমান টিকিট ও ট্রাভেলে সরাসরি রূপান্তর",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#1E293B",
        features: [
          "Dedicated EBL Skylounge access across 3 airports in Bangladesh",
          "Buy 1 Get 1 buffet dining at Westin, Radisson, Le Méridien & Amari",
          "Free annual travel accident insurance up to ৳20,00,000",
          "0% ZIP EMI up to 36 months",
        ],
        featuresBn: [
          "দেশের ৩টি বিমানবন্দরে ডেডিকেটেড ইবিএল স্কাইলাউঞ্জ প্রবেশাধিকার",
          "ওয়েস্টিন, রেডিসন, লা মেরিডিয়ান ও আমারিতে ১টি কিনলে ১টি ফ্রি বুফে",
          "২০ লাখ টাকা পর্যন্ত বিনামূল্যে ভ্রমণ দুর্ঘটনা বীমা",
          "৩৬ মাস পর্যন্ত ০% জিপ ইএমআই সুবিধা",
        ],
        popularity: 97,
      },
    ],
  },
];
