import { CardDealSeed } from "./dealsSeed";

/**
 * Additional card deals — v2
 * 50+ more deals covering all 27 banks across all categories
 */
export const MORE_DEALS: CardDealSeed[] = [
  // ══════════════════ DINING B1G1 ══════════════════

  // IBBL
  {
    slug: "pan-pacific-dhaka-b1g1-ibbl",
    title: "Pan Pacific Sonargaon Dhaka: B1G1 Buffet",
    titleBn: "প্যান প্যাসিফিক সোনারগাঁও ঢাকা: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh (IBBL)",
    cardTier: "GOLD",
    category: "DINING_B1G1",
    merchantName: "Pan Pacific Sonargaon (The Verandah)",
    discountDetails: "Buy 1 Get 1 complimentary buffet at The Verandah restaurant with IBBL Khidmah Gold & Platinum Credit Cards.",
    discountDetailsBn: "আইবিবিএল খিদমাহ গোল্ড ও প্ল্যাটিনাম কার্ডে দ্য ভেরান্দায় ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "DHAKA",
    location: "107 Kazi Nazrul Islam Ave, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Advance booking required. VAT & SC applicable.",
    termsBn: "অগ্রিম বুকিং আবশ্যক। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 91,
  },

  // DBBL
  {
    slug: "dhaka-regency-b1g1-dbbl",
    title: "Dhaka Regency Hotel: B1G1 Buffet Dinner",
    titleBn: "ঢাকা রিজেন্সি হোটেল: ১টি কিনলে ১টি ফ্রি বুফে ডিনার",
    bankSlug: "dutch-bangla-bank",
    bankName: "Dutch-Bangla Bank (DBBL)",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Dhaka Regency Hotel & Resort",
    discountDetails: "Buy 1 Get 1 complimentary buffet dinner with DBBL Nexus-Visa Platinum & Signature credit cards at all restaurants.",
    discountDetailsBn: "ডিবিবিএল নেক্সাস-ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে ঢাকা রিজেন্সির সব রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি ডিনার বুফে।",
    city: "DHAKA",
    location: "Airport Road, Nikunja-2, Khilkhet, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid for dinner only. Reservation required 24 hrs in advance.",
    termsBn: "শুধু ডিনারের জন্য প্রযোজ্য। ২৪ ঘণ্টা আগে রিজার্ভেশন করতে হবে।",
    popularity: 89,
  },

  // Prime Bank
  {
    slug: "hotel-71-b1g1-prime",
    title: "Hotel 71 Dhaka: B1G1 Buffet at Saffron",
    titleBn: "হোটেল ৭১ ঢাকা: স্যাফ্রনে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "prime-bank",
    bankName: "Prime Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Hotel 71 (Saffron Restaurant)",
    discountDetails: "Complimentary companion buffet at Saffron Restaurant, Hotel 71 with Prime Bank Visa Signature & Platinum cards.",
    discountDetailsBn: "প্রাইম ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে হোটেল ৭১-এর স্যাফ্রন রেস্তোরাঁয় সঙ্গী বুফে বিনামূল্যে।",
    city: "DHAKA",
    location: "71 Naya Paltan, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Applicable for lunch and dinner. VAT applicable.",
    termsBn: "লাঞ্চ ও ডিনারের জন্য প্রযোজ্য। ভ্যাট প্রযোজ্য।",
    popularity: 86,
  },

  // Bank Asia
  {
    slug: "lakeshore-b1g1-bank-asia",
    title: "Lakeshore Hotel: B1G1 Buffet Dinner",
    titleBn: "লেকশোর হোটেল: ১টি কিনলে ১টি ফ্রি বুফে ডিনার",
    bankSlug: "bank-asia",
    bankName: "Bank Asia",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Lakeshore Hotel & Apartments",
    discountDetails: "Buy 1 Get 1 free buffet dinner at Lakeshore Hotel restaurants with Bank Asia Mastercard & Visa Platinum cards.",
    discountDetailsBn: "ব্যাংক এশিয়া মাস্টারকার্ড ও ভিসা প্ল্যাটিনাম কার্ডে লেকশোর হোটেলে ১টি কিনলে ১টি ফ্রি ডিনার বুফে।",
    city: "DHAKA",
    location: "Lake Circus, Kalabagan, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation required. Not valid on public holidays.",
    termsBn: "রিজার্ভেশন আবশ্যক। সরকারি ছুটিতে প্রযোজ্য নয়।",
    popularity: 82,
  },

  // Pubali Bank
  {
    slug: "palace-luxury-b1g1-pubali",
    title: "Palace Luxury Hotel: 25% Dining Discount",
    titleBn: "প্যালেস লাক্সারি হোটেল: ২৫% ডাইনিং ডিসকাউন্ট",
    bankSlug: "pubali-bank",
    bankName: "Pubali Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Palace Luxury Hotel",
    discountDetails: "25% discount on food at Palace Luxury Hotel restaurants for Pubali Bank Visa Platinum cardholders.",
    discountDetailsBn: "পূবালী ব্যাংক ভিসা প্ল্যাটিনাম কার্ডধারীদের জন্য প্যালেস লাক্সারি হোটেলে খাবারে ২৫% ছাড়।",
    city: "DHAKA",
    location: "Uttara, Dhaka",
    bannerBadge: "25% OFF",
    terms: "Valid on weekdays only. Maximum discount BDT 1,000.",
    termsBn: "শুধু সপ্তাহের দিনে প্রযোজ্য। সর্বোচ্চ ছাড় ১,০০০ টাকা।",
    popularity: 72,
  },

  // Southeast Bank
  {
    slug: "navy-anchorage-b1g1-southeast",
    title: "Navy Anchorage Hotel: B1G1 Buffet",
    titleBn: "নেভি অ্যাংকরেজ হোটেল: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "southeast-bank",
    bankName: "Southeast Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Navy Anchorage Hotel Chittagong",
    discountDetails: "Complimentary buffet for companion with Southeast Bank Visa Signature cards at Navy Anchorage Hotel Chittagong.",
    discountDetailsBn: "সাউথইস্ট ব্যাংক ভিসা সিগনেচার কার্ডে চট্টগ্রামের নেভি অ্যাংকরেজ হোটেলে সঙ্গীর বুফে বিনামূল্যে।",
    city: "CHITTAGONG",
    location: "Patenga, Chattogram",
    bannerBadge: "Buy 1 Get 1",
    terms: "Prior reservation required 24 hours in advance.",
    termsBn: "২৪ ঘণ্টা আগে রিজার্ভেশন করতে হবে।",
    popularity: 80,
  },

  // Trust Bank
  {
    slug: "army-golf-club-b1g1-trust",
    title: "Army Golf Club Restaurant: B1G1 Lunch",
    titleBn: "আর্মি গলফ ক্লাব রেস্তোরাঁ: ১টি কিনলে ১টি ফ্রি লাঞ্চ",
    bankSlug: "trust-bank",
    bankName: "Trust Bank",
    cardTier: "WORLD",
    category: "DINING_B1G1",
    merchantName: "Army Golf Club Restaurant",
    discountDetails: "Exclusive B1G1 lunch offer at Army Golf Club Restaurant, Dhaka Cantonment for Trust Bank World Mastercard holders.",
    discountDetailsBn: "ট্রাস্ট ব্যাংক ওয়ার্ল্ড মাস্টারকার্ডধারীদের জন্য ঢাকা ক্যান্টনমেন্টের আর্মি গলফ ক্লাব রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি লাঞ্চ।",
    city: "DHAKA",
    location: "Dhaka Cantonment, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid for Trust Bank World Mastercard holders only.",
    termsBn: "শুধুমাত্র ট্রাস্ট ব্যাংক ওয়ার্ল্ড মাস্টারকার্ডধারীদের জন্য প্রযোজ্য।",
    popularity: 77,
  },

  // Dhaka Bank
  {
    slug: "rose-view-sylhet-b1g1-dhaka-bank",
    title: "Rose View Hotel Sylhet: B1G1 Buffet",
    titleBn: "রোজ ভিউ হোটেল সিলেট: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "dhaka-bank",
    bankName: "Dhaka Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Rose View Hotel Sylhet",
    discountDetails: "Buy 1 Get 1 buffet at all restaurants in Rose View Hotel Sylhet with Dhaka Bank Visa Signature credit cards.",
    discountDetailsBn: "ঢাকা ব্যাংক ভিসা সিগনেচার কার্ডে সিলেটের রোজ ভিউ হোটেলের সব রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "SYLHET",
    location: "Taltola, Sylhet",
    bannerBadge: "Buy 1 Get 1",
    terms: "Prior reservation required. VAT & SC applicable.",
    termsBn: "অগ্রিম রিজার্ভেশন আবশ্যক। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 81,
  },

  // Mercantile Bank
  {
    slug: "noorjahan-grand-b1g1-mercantile",
    title: "Noorjahan Grand Hotel: B1G1 Buffet Dinner",
    titleBn: "নূরজাহান গ্র্যান্ড হোটেল: ১টি কিনলে ১টি ফ্রি বুফে ডিনার",
    bankSlug: "mercantile-bank",
    bankName: "Mercantile Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Noorjahan Grand Hotel & Suites",
    discountDetails: "Complimentary buffet dinner for companion at Noorjahan Grand Hotel Sylhet with Mercantile Bank Visa Platinum & Signature cards.",
    discountDetailsBn: "মার্কেন্টাইল ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে সিলেটের নূরজাহান গ্র্যান্ড হোটেলে সঙ্গীর ডিনার বুফে বিনামূল্যে।",
    city: "SYLHET",
    location: "Zindabazar, Sylhet",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation required. Valid for dinner only.",
    termsBn: "রিজার্ভেশন আবশ্যক। শুধু ডিনারের জন্য প্রযোজ্য।",
    popularity: 79,
  },

  // UCB
  {
    slug: "six-seasons-b1g1-ucb",
    title: "Six Seasons Hotel: B1G1 Buffet with UCB",
    titleBn: "সিক্স সিজনস হোটেল: ইউসিবি কার্ডে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "united-commercial-bank",
    bankName: "United Commercial Bank (UCB)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Six Seasons Hotel",
    discountDetails: "Buy 1 Get 1 buffet dinner at Six Seasons Hotel Gulshan with UCB Imperial Visa Signature credit cards.",
    discountDetailsBn: "ইউসিবি ইম্পেরিয়াল ভিসা সিগনেচার কার্ডে গুলশানের সিক্স সিজনস হোটেলে ১টি কিনলে ১টি ফ্রি ডিনার বুফে।",
    city: "DHAKA",
    location: "Gulshan-2, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid on all days. VAT & SC applicable.",
    termsBn: "সব দিন প্রযোজ্য। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 87,
  },

  // MTB
  {
    slug: "cox-today-b1g1-mtb",
    title: "Cox's Today Hotel: B1G1 Buffet with MTB",
    titleBn: "কক্সেস টুডে হোটেল: এমটিবি কার্ডে ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "mutual-trust-bank",
    bankName: "Mutual Trust Bank (MTB)",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Long Beach Hotel Cox's Bazar",
    discountDetails: "Complimentary buffet at Long Beach Hotel Cox's Bazar restaurants with MTB Visa Signature & World Mastercard.",
    discountDetailsBn: "এমটিবি ভিসা সিগনেচার ও ওয়ার্ল্ড মাস্টারকার্ডে কক্সবাজারের লং বিচ হোটেলের রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "CHITTAGONG",
    location: "Kolatoli Beach Road, Cox's Bazar",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation required 24 hrs in advance. SC & VAT applicable.",
    termsBn: "২৪ ঘণ্টা আগে রিজার্ভেশন করতে হবে। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 84,
  },

  // IFIC Bank
  {
    slug: "ocean-paradise-b1g1-ific",
    title: "Ocean Paradise Hotel & Resort: B1G1 Buffet",
    titleBn: "ওশান প্যারাডাইস হোটেল ও রিসোর্ট: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "ific-bank",
    bankName: "IFIC Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Ocean Paradise Hotel & Resort",
    discountDetails: "Buy 1 Get 1 buffet at Ocean Paradise Hotel Cox's Bazar with IFIC Bank Aamar Visa Platinum & Signature cards.",
    discountDetailsBn: "আইএফআইসি ব্যাংক আমার ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে কক্সবাজারের ওশান প্যারাডাইসে ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "CHITTAGONG",
    location: "Cox's Bazar Beachfront",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation 24 hrs in advance. VAT applicable.",
    termsBn: "২৪ ঘণ্টা আগে রিজার্ভেশন করতে হবে। ভ্যাট প্রযোজ্য।",
    popularity: 83,
  },

  // AB Bank
  {
    slug: "royal-tulip-b1g1-ab-bank",
    title: "Royal Tulip Sea Pearl Beach Resort: B1G1",
    titleBn: "রয়্যাল টিউলিপ সি পার্ল বিচ রিসোর্ট: ১টি কিনলে ১টি ফ্রি",
    bankSlug: "ab-bank",
    bankName: "AB Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Royal Tulip Sea Pearl Beach Resort",
    discountDetails: "Exclusive Buy 1 Get 1 dining offer at Royal Tulip Sea Pearl Beach Resort Cox's Bazar with AB Bank Visa Signature.",
    discountDetailsBn: "এবি ব্যাংক ভিসা সিগনেচার কার্ডে কক্সবাজারের রয়্যাল টিউলিপে এক্সক্লুসিভ ১টি কিনলে ১টি ফ্রি ডাইনিং অফার।",
    city: "CHITTAGONG",
    location: "Himchari, Cox's Bazar",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid for AB Bank Signature cardholders only. Advance booking.",
    termsBn: "শুধু এবি ব্যাংক সিগনেচার কার্ডধারীদের জন্য। অগ্রিম বুকিং প্রয়োজন।",
    popularity: 85,
  },

  // HSBC
  {
    slug: "aloft-dhaka-b1g1-hsbc",
    title: "Aloft Dhaka Banani: B1G1 Dining",
    titleBn: "অ্যালফট ঢাকা বনানী: ১টি কিনলে ১টি ফ্রি ডাইনিং",
    bankSlug: "hsbc-bangladesh",
    bankName: "HSBC Bangladesh",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Aloft Dhaka Banani (W XYZ Bar & Nook)",
    discountDetails: "Buy 1 Get 1 complimentary dining at Aloft Dhaka Banani with HSBC Visa Platinum & Signature credit cards.",
    discountDetailsBn: "এইচএসবিসি ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে অ্যালফট ঢাকা বনানীতে ১টি কিনলে ১টি ফ্রি ডাইনিং।",
    city: "DHAKA",
    location: "Plot 3, Road 22, Banani, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid 7 days a week. SC & VAT applicable.",
    termsBn: "সপ্তাহের ৭ দিনই প্রযোজ্য। সার্ভিস চার্জ ও ভ্যাট প্রযোজ্য।",
    popularity: 90,
  },

  // Premier Bank
  {
    slug: "spectra-convention-b1g1-premier",
    title: "Spectra Convention Center: B1G1 Buffet",
    titleBn: "স্পেকট্রা কনভেনশন সেন্টার: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "premier-bank",
    bankName: "Premier Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Spectra Convention Center",
    discountDetails: "Buy 1 Get 1 buffet lunch & dinner at Spectra Convention Center Gulshan with Premier Bank Visa Platinum cards.",
    discountDetailsBn: "প্রিমিয়ার ব্যাংক ভিসা প্ল্যাটিনাম কার্ডে গুলশানের স্পেকট্রা কনভেনশন সেন্টারে ১টি কিনলে ১টি ফ্রি লাঞ্চ ও ডিনার বুফে।",
    city: "DHAKA",
    location: "Gulshan-1, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation required. VAT & SC applicable.",
    termsBn: "রিজার্ভেশন আবশ্যক। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 76,
  },

  // Jamuna Bank
  {
    slug: "bashundhara-bistro-b1g1-jamuna",
    title: "Bashundhara City: 20% Dining Discount",
    titleBn: "বসুন্ধরা সিটি: ২০% ডাইনিং ডিসকাউন্ট",
    bankSlug: "jamuna-bank",
    bankName: "Jamuna Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Bashundhara City (Food Court & Restaurants)",
    discountDetails: "20% discount at all food court and restaurant outlets in Bashundhara City with Jamuna Bank Visa Signature & Platinum cards.",
    discountDetailsBn: "যমুনা ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে বসুন্ধরা সিটির সব রেস্তোরাঁ ও ফুড কোর্টে ২০% ছাড়।",
    city: "DHAKA",
    location: "Panthapath, Dhaka",
    bannerBadge: "20% OFF",
    terms: "Valid on all days. Maximum discount BDT 1,500 per transaction.",
    termsBn: "সব দিন প্রযোজ্য। প্রতি লেনদেনে সর্বোচ্চ ছাড় ১,৫০০ টাকা।",
    popularity: 74,
  },

  // Community Bank
  {
    slug: "police-officers-club-b1g1-community",
    title: "Police Officers Club: B1G1 Dining",
    titleBn: "পুলিশ অফিসার্স ক্লাব: ১টি কিনলে ১টি ফ্রি ডাইনিং",
    bankSlug: "community-bank",
    bankName: "Community Bank Bangladesh",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Police Officers Club Restaurant",
    discountDetails: "Exclusive B1G1 dining offer at Police Officers Club restaurants for Community Bank Visa Platinum cardholders.",
    discountDetailsBn: "কমিউনিটি ব্যাংক ভিসা প্ল্যাটিনাম কার্ডধারীদের জন্য পুলিশ অফিসার্স ক্লাব রেস্তোরাঁয় এক্সক্লুসিভ ১টি কিনলে ১টি ফ্রি।",
    city: "DHAKA",
    location: "Rajarbagh, Dhaka",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid for Community Bank cardholders only.",
    termsBn: "শুধুমাত্র কমিউনিটি ব্যাংক কার্ডধারীদের জন্য প্রযোজ্য।",
    popularity: 68,
  },

  // Midland Bank
  {
    slug: "radisson-chittagong-b1g1-midland",
    title: "Radisson Blu Chittagong: B1G1 Buffet",
    titleBn: "র‌্যাডিসন ব্লু চট্টগ্রাম: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "midland-bank",
    bankName: "Midland Bank",
    cardTier: "SIGNATURE",
    category: "DINING_B1G1",
    merchantName: "Radisson Blu Chittagong Bay View",
    discountDetails: "Buy 1 Get 1 buffet at all restaurants in Radisson Blu Chittagong Bay View with Midland Bank Visa Signature & Platinum cards.",
    discountDetailsBn: "মিডল্যান্ড ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে চট্টগ্রামের র‌্যাডিসন ব্লুতে ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "CHITTAGONG",
    location: "Agrabad, Chattogram",
    bannerBadge: "Buy 1 Get 1",
    terms: "Prior booking required. VAT & SC applicable.",
    termsBn: "আগাম বুকিং প্রয়োজন। ভ্যাট ও সার্ভিস চার্জ প্রযোজ্য।",
    popularity: 78,
  },

  // Al-Arafah
  {
    slug: "bashati-hotel-b1g1-aibl",
    title: "Bashati Hotel Bashundhara: 25% Dining",
    titleBn: "বাশাতি হোটেল বসুন্ধরা: ২৫% ডাইনিং ছাড়",
    bankSlug: "al-arafah-islami-bank",
    bankName: "Al-Arafah Islami Bank (AIBL)",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Bashati Hotel & Convention Center",
    discountDetails: "25% discount on halal food at Bashati Hotel restaurants with Al-Arafah Islami Bank Tayyib Platinum & Gold cards.",
    discountDetailsBn: "আল-আরাফাহ ইসলামী ব্যাংক তাইয়্যিব প্ল্যাটিনাম ও গোল্ড কার্ডে বাশাতি হোটেলের হালাল রেস্তোরাঁয় ২৫% ছাড়।",
    city: "DHAKA",
    location: "Plot-5/B, Bashundhara R/A, Dhaka",
    bannerBadge: "25% OFF",
    terms: "Halal certified food only. Reservation required.",
    termsBn: "শুধুমাত্র হালাল সার্টিফাইড খাবারের জন্য প্রযোজ্য। রিজার্ভেশন আবশ্যক।",
    popularity: 71,
  },

  // Shahjalal Islami Bank
  {
    slug: "parjatan-motel-b1g1-sjibl",
    title: "BPC Parjatan Motel Cox's Bazar: B1G1",
    titleBn: "বিপিসি পর্যটন মোটেল কক্সবাজার: ১টি কিনলে ১টি ফ্রি",
    bankSlug: "shahjalal-islami-bank",
    bankName: "Shahjalal Islami Bank (SJIBL)",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "BPC Parjatan Motel (Coral Wing Restaurant)",
    discountDetails: "Buy 1 Get 1 buffet at Coral Wing Restaurant in BPC Parjatan Motel Cox's Bazar with SJIBL Souhardo Islamic Platinum cards.",
    discountDetailsBn: "এসজেআইবিএল সৌহার্দ ইসলামিক প্ল্যাটিনাম কার্ডে কক্সবাজারের বিপিসি পর্যটন মোটেলে ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "CHITTAGONG",
    location: "Hotel Zone, Cox's Bazar",
    bannerBadge: "Buy 1 Get 1",
    terms: "Halal food only. Reservation required. VAT applicable.",
    termsBn: "শুধু হালাল খাবার। রিজার্ভেশন আবশ্যক। ভ্যাট প্রযোজ্য।",
    popularity: 69,
  },

  // EXIM Bank
  {
    slug: "sky-garden-chittagong-b1g1-exim",
    title: "Sayeman Beach Resort: B1G1 Buffet",
    titleBn: "সায়েমান বিচ রিসোর্ট: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "exim-bank",
    bankName: "EXIM Bank",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Sayeman Beach Resort Cox's Bazar",
    discountDetails: "Complimentary companion buffet at Sayeman Beach Resort restaurants with EXIM Islamic Visa Platinum & Mastercard Platinum.",
    discountDetailsBn: "এক্সিম ইসলামিক ভিসা প্ল্যাটিনাম ও মাস্টারকার্ড কার্ডে কক্সবাজারের সায়েমান বিচ রিসোর্টে সঙ্গীর বুফে বিনামূল্যে।",
    city: "CHITTAGONG",
    location: "Kolatoli Road, Cox's Bazar",
    bannerBadge: "Buy 1 Get 1",
    terms: "Reservation required. SC & VAT applicable.",
    termsBn: "রিজার্ভেশন আবশ্যক। সার্ভিস চার্জ ও ভ্যাট প্রযোজ্য।",
    popularity: 73,
  },

  // SIBL
  {
    slug: "agrabad-hotel-b1g1-sibl",
    title: "Agrabad Hotel Chittagong: B1G1 Buffet",
    titleBn: "আগ্রাবাদ হোটেল চট্টগ্রাম: ১টি কিনলে ১টি ফ্রি বুফে",
    bankSlug: "social-islami-bank",
    bankName: "Social Islami Bank (SIBL)",
    cardTier: "PLATINUM",
    category: "DINING_B1G1",
    merchantName: "Agrabad Hotel (Rangmahal Restaurant)",
    discountDetails: "Buy 1 Get 1 buffet at Rangmahal Restaurant, Agrabad Hotel Chittagong with SIBL Visa Islamic Platinum cards.",
    discountDetailsBn: "এসআইবিএল ভিসা ইসলামিক প্ল্যাটিনাম কার্ডে চট্টগ্রামের আগ্রাবাদ হোটেলের রাঙামহল রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি বুফে।",
    city: "CHITTAGONG",
    location: "Agrabad C/A, Chattogram",
    bannerBadge: "Buy 1 Get 1",
    terms: "Valid for dinner only. Reservation required.",
    termsBn: "শুধু ডিনারের জন্য প্রযোজ্য। রিজার্ভেশন আবশ্যক।",
    popularity: 70,
  },

  // Sonali Bank
  {
    slug: "biswa-sahitya-kendra-sonali",
    title: "Hotel International Rajshahi: 20% Dining",
    titleBn: "হোটেল ইন্টারন্যাশনাল রাজশাহী: ২০% ডাইনিং ছাড়",
    bankSlug: "sonali-bank",
    bankName: "Sonali Bank",
    cardTier: "GOLD",
    category: "DINING_B1G1",
    merchantName: "Hotel International Rajshahi",
    discountDetails: "20% discount on food bills at Hotel International Rajshahi with Sonali Bank Visa Gold & Platinum credit cards.",
    discountDetailsBn: "সোনালী ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে রাজশাহীর হোটেল ইন্টারন্যাশনালে খাবারের বিলে ২০% ছাড়।",
    city: "NATIONWIDE",
    location: "Rajshahi City",
    bannerBadge: "20% OFF",
    terms: "Valid at participating Sonali Bank partner hotels.",
    termsBn: "সোনালী ব্যাংকের পার্টনার হোটেলগুলোতে প্রযোজ্য।",
    popularity: 62,
  },

  // ══════════════════ HOTEL B1G1 ══════════════════

  // DBBL
  {
    slug: "pan-pacific-stay-dbbl",
    title: "Pan Pacific Sonargaon: B1G1 Room Stay",
    titleBn: "প্যান প্যাসিফিক সোনারগাঁও: ১টি কিনলে ১টি ফ্রি রুম স্টে",
    bankSlug: "dutch-bangla-bank",
    bankName: "Dutch-Bangla Bank (DBBL)",
    cardTier: "SIGNATURE",
    category: "HOTEL_B1G1",
    merchantName: "Pan Pacific Sonargaon Hotel",
    discountDetails: "Buy 1 night Get 1 night free on Superior & Deluxe rooms at Pan Pacific Sonargaon Dhaka with DBBL Nexus-Visa Signature cards.",
    discountDetailsBn: "ডিবিবিএল নেক্সাস-ভিসা সিগনেচার কার্ডে প্যান প্যাসিফিক সোনারগাঁওতে সুপেরিয়র ও ডিলাক্স রুমে ১ রাত কিনলে ১ রাত ফ্রি।",
    city: "DHAKA",
    location: "107 Kazi Nazrul Islam Ave, Dhaka",
    bannerBadge: "B1G1 Night",
    terms: "Minimum 2 nights stay. Advance booking required. Blackout dates apply.",
    termsBn: "কমপক্ষে ২ রাত থাকতে হবে। আগাম বুকিং প্রয়োজন। ব্ল্যাকআউট তারিখ প্রযোজ্য।",
    popularity: 93,
  },

  // BRAC Bank
  {
    slug: "westin-sylhet-stay-brac",
    title: "The Westin Sylhet: 30% Off Room Booking",
    titleBn: "দ্য ওয়েস্টিন সিলেট: রুম বুকিংয়ে ৩০% ছাড়",
    bankSlug: "brac-bank",
    bankName: "BRAC Bank",
    cardTier: "WORLD",
    category: "HOTEL_B1G1",
    merchantName: "The Westin Sylhet",
    discountDetails: "30% off on best available rate for rooms at The Westin Sylhet with BRAC Bank Visa Signature & World Mastercard credit cards.",
    discountDetailsBn: "ব্র্যাক ব্যাংক ভিসা সিগনেচার ও ওয়ার্ল্ড মাস্টারকার্ডে সিলেটের ওয়েস্টিনে রুমে সেরা উপলব্ধ মূল্যে ৩০% ছাড়।",
    city: "SYLHET",
    location: "Dargah Gate, Sylhet",
    bannerBadge: "30% OFF",
    terms: "Subject to availability. VAT applicable on room rates.",
    termsBn: "প্রাপ্যতাসাপেক্ষে। রুম রেটে ভ্যাট প্রযোজ্য।",
    popularity: 88,
  },

  // UCB
  {
    slug: "seagull-hotel-coxsbazar-ucb",
    title: "Seagull Hotel Cox's Bazar: 25% Off Stay",
    titleBn: "সিগাল হোটেল কক্সবাজার: থাকায় ২৫% ছাড়",
    bankSlug: "united-commercial-bank",
    bankName: "UCB",
    cardTier: "PLATINUM",
    category: "HOTEL_B1G1",
    merchantName: "Seagull Hotel Cox's Bazar",
    discountDetails: "25% discount on room bookings at Seagull Hotel Cox's Bazar with UCB Visa Platinum & Imperial Signature credit cards.",
    discountDetailsBn: "ইউসিবি ভিসা প্ল্যাটিনাম ও ইম্পেরিয়াল সিগনেচার কার্ডে কক্সবাজারের সিগাল হোটেলে রুম বুকিংয়ে ২৫% ছাড়।",
    city: "CHITTAGONG",
    location: "Kolatoli Road, Cox's Bazar",
    bannerBadge: "25% OFF",
    terms: "Valid for direct bookings. Advance reservation required.",
    termsBn: "শুধু সরাসরি বুকিংয়ে প্রযোজ্য। আগাম রিজার্ভেশন আবশ্যক।",
    popularity: 85,
  },

  // Prime Bank
  {
    slug: "breakwater-resort-sylhet-prime",
    title: "Breakwater Resort Sylhet: 20% Off Stay",
    titleBn: "ব্রেকওয়াটার রিসোর্ট সিলেট: থাকায় ২০% ছাড়",
    bankSlug: "prime-bank",
    bankName: "Prime Bank",
    cardTier: "PLATINUM",
    category: "HOTEL_B1G1",
    merchantName: "Breakwater Resort Sylhet",
    discountDetails: "Flat 20% discount on all room categories at Breakwater Resort Sylhet with Prime Bank Visa Platinum & Signature cards.",
    discountDetailsBn: "প্রাইম ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে সিলেটের ব্রেকওয়াটার রিসোর্টে সব রুমে ২০% ছাড়।",
    city: "SYLHET",
    location: "Jaflong Road, Sylhet",
    bannerBadge: "20% OFF",
    terms: "Subject to availability. Direct booking only.",
    termsBn: "প্রাপ্যতাসাপেক্ষে। শুধু সরাসরি বুকিংয়ে প্রযোজ্য।",
    popularity: 80,
  },

  // HSBC
  {
    slug: "hilton-dhaka-stay-hsbc",
    title: "Hilton Dhaka: 35% Off Room Stay",
    titleBn: "হিলটন ঢাকা: রুমে ৩৫% ছাড়",
    bankSlug: "hsbc-bangladesh",
    bankName: "HSBC Bangladesh",
    cardTier: "SIGNATURE",
    category: "HOTEL_B1G1",
    merchantName: "Hilton Dhaka",
    discountDetails: "Up to 35% off on room bookings at Hilton Dhaka with HSBC Visa Signature & Platinum credit cards. Includes breakfast for 2.",
    discountDetailsBn: "এইচএসবিসি ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে হিলটন ঢাকায় রুম বুকিংয়ে ৩৫% পর্যন্ত ছাড়। দুজনের জন্য ব্রেকফাস্টসহ।",
    city: "DHAKA",
    location: "1 Minto Road, Dhaka (Opening 2026)",
    bannerBadge: "35% OFF",
    terms: "Limited time offer. HSBC cardholders only. Subject to availability.",
    termsBn: "সীমিত সময়ের অফার। শুধু এইচএসবিসি কার্ডধারীদের জন্য। প্রাপ্যতাসাপেক্ষে।",
    popularity: 92,
  },

  // ══════════════════ TRAVEL ══════════════════

  // IBBL
  {
    slug: "umrah-package-discount-ibbl",
    title: "Umrah & Hajj Package: 15% Discount with IBBL",
    titleBn: "ওমরাহ ও হজ প্যাকেজে ইবিবিএল কার্ডে ১৫% ছাড়",
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh (IBBL)",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "Bangladesh Hajj Agencies (selected)",
    discountDetails: "15% discount on Umrah and Hajj packages from selected agencies when paid with IBBL Khidmah Gold & Platinum credit cards.",
    discountDetailsBn: "আইবিবিএল খিদমাহ গোল্ড ও প্ল্যাটিনাম কার্ডে নির্বাচিত এজেন্সি থেকে ওমরাহ ও হজ প্যাকেজে ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Valid for selected Hajj agencies only. Limited seats.",
    termsBn: "শুধু নির্বাচিত হজ এজেন্সিতে প্রযোজ্য। আসন সীমিত।",
    popularity: 86,
  },

  // Prime Bank
  {
    slug: "biman-flight-discount-prime",
    title: "Biman Bangladesh Airlines: 10% Ticket Discount",
    titleBn: "বিমান বাংলাদেশ এয়ারলাইন্স: টিকিটে ১০% ছাড়",
    bankSlug: "prime-bank",
    bankName: "Prime Bank",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "Biman Bangladesh Airlines",
    discountDetails: "10% discount on domestic and international Biman Bangladesh Airlines tickets purchased with Prime Bank Visa Platinum & Signature cards.",
    discountDetailsBn: "প্রাইম ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে বিমান বাংলাদেশ এয়ারলাইন্সের দেশীয় ও আন্তর্জাতিক টিকিটে ১০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "10% OFF Flights",
    terms: "Valid on Biman tickets only. Minimum 7 days advance purchase.",
    termsBn: "শুধু বিমানের টিকিটে প্রযোজ্য। কমপক্ষে ৭ দিন আগে কিনতে হবে।",
    popularity: 88,
  },

  // UCB
  {
    slug: "us-bangla-ticket-ucb",
    title: "US-Bangla Airlines: 12% Off Tickets",
    titleBn: "ইউএস-বাংলা এয়ারলাইন্স: টিকিটে ১২% ছাড়",
    bankSlug: "united-commercial-bank",
    bankName: "UCB",
    cardTier: "SIGNATURE",
    category: "TRAVEL",
    merchantName: "US-Bangla Airlines",
    discountDetails: "12% discount on US-Bangla Airlines domestic and international tickets for UCB Imperial Visa Signature cardholders.",
    discountDetailsBn: "ইউসিবি ইম্পেরিয়াল ভিসা সিগনেচার কার্ডধারীদের জন্য ইউএস-বাংলার দেশীয় ও আন্তর্জাতিক টিকিটে ১২% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "12% OFF Flights",
    terms: "Valid on direct purchases from US-Bangla website.",
    termsBn: "ইউএস-বাংলার ওয়েবসাইটে সরাসরি কেনাকাটায় প্রযোজ্য।",
    popularity: 83,
  },

  // DBBL
  {
    slug: "novoair-ticket-dbbl",
    title: "Novoair: 10% Off Domestic Flights",
    titleBn: "নভোএয়ার: দেশীয় ফ্লাইটে ১০% ছাড়",
    bankSlug: "dutch-bangla-bank",
    bankName: "DBBL",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "Novoair",
    discountDetails: "10% discount on Novoair domestic flight tickets when booked through their website with DBBL Nexus-Visa Platinum & Signature cards.",
    discountDetailsBn: "ডিবিবিএল নেক্সাস-ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে নভোএয়ারের ওয়েবসাইটে দেশীয় ফ্লাইট টিকিটে ১০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "10% OFF Flights",
    terms: "Valid on domestic routes only.",
    termsBn: "শুধু দেশীয় রুটে প্রযোজ্য।",
    popularity: 79,
  },

  // Bank Asia
  {
    slug: "tours-travels-discount-bank-asia",
    title: "Cholo Jai Tours: 15% Travel Package Discount",
    titleBn: "চলো যাই ট্যুরস: ১৫% ভ্রমণ প্যাকেজ ছাড়",
    bankSlug: "bank-asia",
    bankName: "Bank Asia",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "Cholo Jai (Holiday Package)",
    discountDetails: "Flat 15% discount on all domestic and international holiday packages from Cholo Jai with Bank Asia Mastercard Titanium & Platinum cards.",
    discountDetailsBn: "ব্যাংক এশিয়া মাস্টারকার্ড টাইটানিয়াম ও প্ল্যাটিনাম কার্ডে চলো যাই-এর সব দেশীয় ও আন্তর্জাতিক হলিডে প্যাকেজে ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Minimum package value BDT 20,000. Advance booking required.",
    termsBn: "সর্বনিম্ন প্যাকেজ মূল্য ২০,০০০ টাকা। আগাম বুকিং প্রয়োজন।",
    popularity: 76,
  },

  // Southeast Bank
  {
    slug: "sharetrip-southeast-travel",
    title: "ShareTrip: 20% Off Hotels & Flights",
    titleBn: "শেয়ারট্রিপ: হোটেল ও ফ্লাইটে ২০% ছাড়",
    bankSlug: "southeast-bank",
    bankName: "Southeast Bank",
    cardTier: "SIGNATURE",
    category: "TRAVEL",
    merchantName: "ShareTrip (Hotels & Flights)",
    discountDetails: "20% discount on hotels and 10% off flights on ShareTrip.net with Southeast Bank Visa Signature & Platinum credit cards.",
    discountDetailsBn: "সাউথইস্ট ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে শেয়ারট্রিপে হোটেলে ২০% ও ফ্লাইটে ১০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "Up to 20% OFF",
    terms: "Use promo code at checkout. Valid for registered users.",
    termsBn: "চেকআউটে প্রোমো কোড ব্যবহার করুন। নিবন্ধিত ব্যবহারকারীদের জন্য প্রযোজ্য।",
    popularity: 81,
  },

  // MTB
  {
    slug: "gozayaan-mtb-travel",
    title: "GoZayaan: 25% Off Hotel Bookings",
    titleBn: "গোযায়ান: হোটেল বুকিংয়ে ২৫% ছাড়",
    bankSlug: "mutual-trust-bank",
    bankName: "MTB",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "GoZayaan Hotels",
    discountDetails: "Get 25% cashback on hotel bookings (max ৳2,000) on GoZayaan.com with MTB Visa Signature & World Mastercard credit cards.",
    discountDetailsBn: "এমটিবি ভিসা সিগনেচার ও ওয়ার্ল্ড মাস্টারকার্ডে গোযায়ানে হোটেল বুকিংয়ে ২৫% ক্যাশব্যাক (সর্বোচ্চ ২,০০০ টাকা)।",
    city: "NATIONWIDE",
    bannerBadge: "25% Cashback",
    terms: "Max cashback ৳2,000 per transaction. Valid once per month.",
    termsBn: "প্রতি লেনদেনে সর্বোচ্চ ক্যাশব্যাক ২,০০০ টাকা। মাসে একবার প্রযোজ্য।",
    popularity: 84,
  },

  // HSBC
  {
    slug: "agoda-hsbc-hotel-deal",
    title: "Agoda Hotels: 40% Off for HSBC Cardholders",
    titleBn: "অ্যাগোডা হোটেল: এইচএসবিসি কার্ডধারীদের জন্য ৪০% ছাড়",
    bankSlug: "hsbc-bangladesh",
    bankName: "HSBC Bangladesh",
    cardTier: "PLATINUM",
    category: "TRAVEL",
    merchantName: "Agoda (International Hotels)",
    discountDetails: "Up to 40% off on selected hotel bookings on Agoda.com exclusively for HSBC Bangladesh Visa Platinum & Signature cardholders.",
    discountDetailsBn: "এইচএসবিসি বাংলাদেশ ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডধারীদের জন্য অ্যাগোডায় নির্বাচিত হোটেলে ৪০% পর্যন্ত ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "Up to 40% OFF",
    terms: "Subject to hotel availability and deal activation dates.",
    termsBn: "হোটেলের প্রাপ্যতা ও ডিল সক্রিয়করণ তারিখ সাপেক্ষে।",
    popularity: 91,
  },

  // ══════════════════ SHOPPING ══════════════════

  // IBBL
  {
    slug: "chaldal-discount-ibbl",
    title: "Chaldal.com: 10% Grocery Cashback",
    titleBn: "চালডাল.কম: ১০% মুদি পণ্য ক্যাশব্যাক",
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh (IBBL)",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "Chaldal.com",
    discountDetails: "10% instant cashback on grocery orders from Chaldal.com (min ৳500, max ৳200 cashback) with IBBL Khidmah Gold & Platinum cards.",
    discountDetailsBn: "আইবিবিএল খিদমাহ গোল্ড ও প্ল্যাটিনাম কার্ডে চালডালে মুদি পণ্যে ১০% তাৎক্ষণিক ক্যাশব্যাক (সর্বনিম্ন ৫০০ টাকা, সর্বোচ্চ ক্যাশব্যাক ২০০ টাকা)।",
    city: "NATIONWIDE",
    bannerBadge: "10% Cashback",
    terms: "Min order ৳500. Max cashback ৳200 per order. Valid 2x per month.",
    termsBn: "সর্বনিম্ন অর্ডার ৫০০ টাকা। প্রতি অর্ডারে সর্বোচ্চ ক্যাশব্যাক ২০০ টাকা। মাসে ২ বার প্রযোজ্য।",
    popularity: 84,
  },

  // Prime Bank
  {
    slug: "pathao-food-prime",
    title: "Pathao Food: 20% Off on Food Orders",
    titleBn: "পাঠাও ফুড: ফুড অর্ডারে ২০% ছাড়",
    bankSlug: "prime-bank",
    bankName: "Prime Bank",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "Pathao Food",
    discountDetails: "20% instant discount on Pathao Food orders (min ৳300, max ৳150 discount) with Prime Bank Visa Gold & Platinum credit cards.",
    discountDetailsBn: "প্রাইম ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে পাঠাও ফুড অর্ডারে ২০% তাৎক্ষণিক ছাড় (সর্বনিম্ন ৩০০ টাকা, সর্বোচ্চ ১৫০ টাকা)।",
    city: "NATIONWIDE",
    bannerBadge: "20% OFF Food",
    terms: "Min order ৳300. Max discount ৳150. 3x per month.",
    termsBn: "সর্বনিম্ন অর্ডার ৩০০ টাকা। সর্বোচ্চ ছাড় ১৫০ টাকা। মাসে ৩ বার।",
    popularity: 83,
  },

  // DBBL
  {
    slug: "shohoz-bus-discount-dbbl",
    title: "Shohoz.com: 15% Off Bus Tickets",
    titleBn: "শোহজ.কম: বাসের টিকিটে ১৫% ছাড়",
    bankSlug: "dutch-bangla-bank",
    bankName: "DBBL",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "Shohoz.com",
    discountDetails: "15% discount on bus and launch tickets booked on Shohoz.com with DBBL Nexus-Mastercard & Visa Platinum credit cards.",
    discountDetailsBn: "ডিবিবিএল নেক্সাস-মাস্টারকার্ড ও ভিসা প্ল্যাটিনাম কার্ডে শোহজ.কমে বাস ও লঞ্চের টিকিটে ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Min booking ৳200. Max discount ৳100. Valid on non-peak journeys.",
    termsBn: "সর্বনিম্ন বুকিং ২০০ টাকা। সর্বোচ্চ ছাড় ১০০ টাকা। অফ-পিক যাত্রায় প্রযোজ্য।",
    popularity: 77,
  },

  // Bank Asia
  {
    slug: "shajgoj-beauty-bank-asia",
    title: "Shajgoj: 15% Beauty & Skincare Discount",
    titleBn: "শাজগোজ: বিউটি ও স্কিনকেয়ারে ১৫% ছাড়",
    bankSlug: "bank-asia",
    bankName: "Bank Asia",
    cardTier: "TITANIUM",
    category: "SHOPPING",
    merchantName: "Shajgoj.com",
    discountDetails: "Flat 15% discount on all beauty, skincare & cosmetics orders on Shajgoj.com with Bank Asia Mastercard Titanium & Platinum cards.",
    discountDetailsBn: "ব্যাংক এশিয়া মাস্টারকার্ড টাইটানিয়াম ও প্ল্যাটিনাম কার্ডে শাজগোজে সব বিউটি ও স্কিনকেয়ার পণ্যে ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Min purchase ৳1,000. Max discount ৳500 per order.",
    termsBn: "সর্বনিম্ন কেনাকাটা ১,০০০ টাকা। প্রতি অর্ডারে সর্বোচ্চ ছাড় ৫০০ টাকা।",
    popularity: 74,
  },

  // Mercantile Bank
  {
    slug: "rokomari-books-mercantile",
    title: "Rokomari.com: 20% Off Books & Stationery",
    titleBn: "রকমারি.কম: বই ও স্টেশনারিতে ২০% ছাড়",
    bankSlug: "mercantile-bank",
    bankName: "Mercantile Bank",
    cardTier: "PLATINUM",
    category: "SHOPPING",
    merchantName: "Rokomari.com",
    discountDetails: "20% discount on books, stationery and gadgets from Rokomari.com with Mercantile Bank Visa Platinum & Signature cards.",
    discountDetailsBn: "মার্কেন্টাইল ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে রকমারি.কম থেকে বই, স্টেশনারি ও গ্যাজেটে ২০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "20% OFF",
    terms: "Min purchase ৳500. Max discount ৳300 per order.",
    termsBn: "সর্বনিম্ন কেনাকাটা ৫০০ টাকা। প্রতি অর্ডারে সর্বোচ্চ ছাড় ৩০০ টাকা।",
    popularity: 71,
  },

  // Dhaka Bank
  {
    slug: "khaas-food-dhaka-bank",
    title: "KhaasFood: 15% Off Organic Products",
    titleBn: "খাঁস ফুড: অর্গানিক পণ্যে ১৫% ছাড়",
    bankSlug: "dhaka-bank",
    bankName: "Dhaka Bank",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "KhaasFood.com",
    discountDetails: "15% instant discount on all organic food and agro products from KhaasFood.com with Dhaka Bank Visa Gold & Platinum cards.",
    discountDetailsBn: "ঢাকা ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে খাঁস ফুডে সব অর্গানিক খাদ্য পণ্যে ১৫% তাৎক্ষণিক ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Min order ৳800. Max discount ৳400.",
    termsBn: "সর্বনিম্ন অর্ডার ৮০০ টাকা। সর্বোচ্চ ছাড় ৪০০ টাকা।",
    popularity: 69,
  },

  // Southeast Bank
  {
    slug: "meena-bazar-southeast",
    title: "Meena Bazar: 10% Grocery Discount",
    titleBn: "মিনা বাজার: ১০% মুদি পণ্য ছাড়",
    bankSlug: "southeast-bank",
    bankName: "Southeast Bank",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "Meena Bazar",
    discountDetails: "10% discount on grocery shopping at all Meena Bazar outlets with Southeast Bank Visa Gold & Platinum credit cards.",
    discountDetailsBn: "সাউথইস্ট ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে মিনা বাজারের সব শাখায় মুদি কেনাকাটায় ১০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "10% OFF",
    terms: "Min purchase ৳1,000. Max discount ৳500. Valid on weekdays.",
    termsBn: "সর্বনিম্ন কেনাকাটা ১,০০০ টাকা। সর্বোচ্চ ছাড় ৫০০ টাকা। সপ্তাহের দিনে প্রযোজ্য।",
    popularity: 73,
  },

  // AB Bank
  {
    slug: "shwapno-groceries-ab-bank",
    title: "Shwapno: 12% Grocery Discount",
    titleBn: "স্বপ্ন: ১২% মুদি পণ্য ছাড়",
    bankSlug: "ab-bank",
    bankName: "AB Bank",
    cardTier: "GOLD",
    category: "SHOPPING",
    merchantName: "Shwapno Superstore",
    discountDetails: "12% discount at all Shwapno outlets on grocery and daily necessities with AB Bank Visa Gold & Platinum credit cards.",
    discountDetailsBn: "এবি ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে স্বপ্নের সব শাখায় মুদি ও নিত্যপণ্যে ১২% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "12% OFF",
    terms: "Min purchase ৳1,500. Max discount ৳750 per visit.",
    termsBn: "সর্বনিম্ন কেনাকাটা ১,৫০০ টাকা। প্রতি ভিজিটে সর্বোচ্চ ছাড় ৭৫০ টাকা।",
    popularity: 72,
  },

  // Trust Bank
  {
    slug: "military-store-discount-trust",
    title: "CSD Canteen: 10% Discount for Trust Bank",
    titleBn: "সিএসডি ক্যান্টিন: ট্রাস্ট ব্যাংক কার্ডে ১০% ছাড়",
    bankSlug: "trust-bank",
    bankName: "Trust Bank",
    cardTier: "PLATINUM",
    category: "SHOPPING",
    merchantName: "CSD (Combined Services Depot) Canteen",
    discountDetails: "10% discount at CSD Cantonment Stores for Trust Bank Visa Platinum & World Mastercard credit card holders.",
    discountDetailsBn: "ট্রাস্ট ব্যাংক ভিসা প্ল্যাটিনাম ও ওয়ার্ল্ড মাস্টারকার্ড কার্ডধারীদের জন্য সিএসডি ক্যান্টিনমেন্ট স্টোরে ১০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "10% OFF",
    terms: "Valid at all CSD Canteen locations nationwide. Valid for active/retired military only.",
    termsBn: "সারাদেশে সব সিএসডি ক্যান্টিনে প্রযোজ্য। শুধু সক্রিয়/অবসরপ্রাপ্ত সামরিক সদস্যদের জন্য।",
    popularity: 78,
  },

  // Jamuna Bank
  {
    slug: "foodpanda-discount-jamuna",
    title: "Foodpanda: 25% Off Food Delivery",
    titleBn: "ফুডপান্ডা: ফুড ডেলিভারিতে ২৫% ছাড়",
    bankSlug: "jamuna-bank",
    bankName: "Jamuna Bank",
    cardTier: "PLATINUM",
    category: "SHOPPING",
    merchantName: "Foodpanda Bangladesh",
    discountDetails: "25% discount on Foodpanda orders (min ৳400, max ৳200 discount) with Jamuna Bank Visa Signature & Platinum credit cards.",
    discountDetailsBn: "যমুনা ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে ফুডপান্ডায় ২৫% ছাড় (সর্বনিম্ন ৪০০ টাকা, সর্বোচ্চ ২০০ টাকা)।",
    city: "NATIONWIDE",
    bannerBadge: "25% OFF",
    terms: "Use promo code at checkout. 3x per month. Min ৳400.",
    termsBn: "চেকআউটে প্রোমো কোড ব্যবহার করুন। মাসে ৩ বার। সর্বনিম্ন ৪০০ টাকা।",
    popularity: 80,
  },

  // Community Bank
  {
    slug: "bpl-police-market-community",
    title: "Police Market BD: 15% Shopping Discount",
    titleBn: "পুলিশ মার্কেট বিডি: ১৫% শপিং ছাড়",
    bankSlug: "community-bank",
    bankName: "Community Bank Bangladesh",
    cardTier: "PLATINUM",
    category: "SHOPPING",
    merchantName: "Police Market Bangladesh",
    discountDetails: "15% discount on all shopping at Police Market outlets with Community Bank Visa Platinum & Signature credit cards.",
    discountDetailsBn: "কমিউনিটি ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে পুলিশ মার্কেটের সব শাখায় কেনাকাটায় ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Valid for Community Bank cardholders. Max discount ৳1,000.",
    termsBn: "কমিউনিটি ব্যাংক কার্ডধারীদের জন্য প্রযোজ্য। সর্বোচ্চ ছাড় ১,০০০ টাকা।",
    popularity: 65,
  },

  // Midland Bank
  {
    slug: "daraz-midland-cashback",
    title: "Daraz.com.bd: 10% Cashback with Midland",
    titleBn: "দারাজ.কম.বিডি: মিডল্যান্ড কার্ডে ১০% ক্যাশব্যাক",
    bankSlug: "midland-bank",
    bankName: "Midland Bank",
    cardTier: "PLATINUM",
    category: "SHOPPING",
    merchantName: "Daraz Bangladesh",
    discountDetails: "10% cashback on all purchases on Daraz.com.bd (max ৳500) with Midland Bank Visa Platinum & Signature credit cards.",
    discountDetailsBn: "মিডল্যান্ড ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে দারাজে সব কেনাকাটায় ১০% ক্যাশব্যাক (সর্বোচ্চ ৫০০ টাকা)।",
    city: "NATIONWIDE",
    bannerBadge: "10% Cashback",
    terms: "Max cashback ৳500 per month. Valid on full-price items only.",
    termsBn: "মাসে সর্বোচ্চ ক্যাশব্যাক ৫০০ টাকা। শুধু পূর্ণ মূল্যের পণ্যে প্রযোজ্য।",
    popularity: 68,
  },

  // ══════════════════ HEALTHCARE ══════════════════

  // IBBL
  {
    slug: "ibngine-health-ibbl",
    title: "Ibn Sina Hospital: 15% Health Discount",
    titleBn: "ইবনে সিনা হাসপাতাল: ১৫% স্বাস্থ্যসেবা ছাড়",
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh (IBBL)",
    cardTier: "GOLD",
    category: "HEALTHCARE",
    merchantName: "Ibn Sina Hospital (All Branches)",
    discountDetails: "15% discount on all diagnostic tests and selected specialist consultations at Ibn Sina Hospital with IBBL Khidmah Gold & Platinum cards.",
    discountDetailsBn: "আইবিবিএল খিদমাহ গোল্ড ও প্ল্যাটিনাম কার্ডে ইবনে সিনা হাসপাতালে সব ডায়াগনস্টিক পরীক্ষা ও নির্বাচিত বিশেষজ্ঞ পরামর্শে ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Valid at all Ibn Sina Hospital branches. Prescription required.",
    termsBn: "ইবনে সিনার সব শাখায় প্রযোজ্য। প্রেসক্রিপশন আবশ্যক।",
    popularity: 83,
  },

  // DBBL
  {
    slug: "square-hospital-dbbl",
    title: "Square Hospital: 20% Diagnostic Discount",
    titleBn: "স্কয়ার হাসপাতাল: ২০% ডায়াগনস্টিক ছাড়",
    bankSlug: "dutch-bangla-bank",
    bankName: "DBBL",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "Square Hospital Dhaka",
    discountDetails: "20% discount on all diagnostic tests at Square Hospital Dhaka with DBBL Nexus-Visa Platinum & Signature credit cards.",
    discountDetailsBn: "ডিবিবিএল নেক্সাস-ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে স্কয়ার হাসপাতালে সব ডায়াগনস্টিক পরীক্ষায় ২০% ছাড়।",
    city: "DHAKA",
    location: "18/F Bir Uttam Qazi Nuruzzaman Sarak, Dhaka",
    bannerBadge: "20% OFF",
    terms: "Excludes specialist consultation fees. Valid on weekdays.",
    termsBn: "বিশেষজ্ঞ পরামর্শ ফি বাদে। সপ্তাহের দিনে প্রযোজ্য।",
    popularity: 85,
  },

  // EBL
  {
    slug: "labaid-hospital-ebl",
    title: "Labaid Hospital: 15% Cashback",
    titleBn: "ল্যাবএইড হাসপাতাল: ১৫% ক্যাশব্যাক",
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank (EBL)",
    cardTier: "SIGNATURE",
    category: "HEALTHCARE",
    merchantName: "Labaid Hospital & Diagnostic (All Branches)",
    discountDetails: "15% discount on diagnostic, pathology and radiology tests at Labaid Hospital with EBL Visa Signature & Titanium credit cards.",
    discountDetailsBn: "ইবিএল ভিসা সিগনেচার ও টাইটানিয়াম কার্ডে ল্যাবএইড হাসপাতালে ডায়াগনস্টিক, প্যাথলজি ও রেডিওলজি পরীক্ষায় ১৫% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "15% OFF",
    terms: "Valid at all Labaid Hospital & Diagnostic branches nationwide.",
    termsBn: "সারাদেশে ল্যাবএইড হাসপাতাল ও ডায়াগনস্টিকের সব শাখায় প্রযোজ্য।",
    popularity: 82,
  },

  // Prime Bank
  {
    slug: "popular-diagnostic-prime",
    title: "Popular Diagnostic Centre: 20% Discount",
    titleBn: "পপুলার ডায়াগনস্টিক সেন্টার: ২০% ছাড়",
    bankSlug: "prime-bank",
    bankName: "Prime Bank",
    cardTier: "GOLD",
    category: "HEALTHCARE",
    merchantName: "Popular Diagnostic Centre (All Branches)",
    discountDetails: "20% discount on all diagnostic, laboratory and imaging services at Popular Diagnostic Centre with Prime Bank Visa Gold & Platinum cards.",
    discountDetailsBn: "প্রাইম ব্যাংক ভিসা গোল্ড ও প্ল্যাটিনাম কার্ডে পপুলার ডায়াগনস্টিক সেন্টারে সব ডায়াগনস্টিক, ল্যাবরেটরি ও ইমেজিং সেবায় ২০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "20% OFF",
    terms: "Valid at all Popular branches. Emergency service excluded.",
    termsBn: "পপুলারের সব শাখায় প্রযোজ্য। জরুরি সেবা বাদে।",
    popularity: 81,
  },

  // UCB
  {
    slug: "apollo-hospitals-ucb",
    title: "Apollo Hospitals Dhaka: 20% Diagnostic",
    titleBn: "অ্যাপোলো হাসপাতাল ঢাকা: ২০% ডায়াগনস্টিক ছাড়",
    bankSlug: "united-commercial-bank",
    bankName: "UCB",
    cardTier: "SIGNATURE",
    category: "HEALTHCARE",
    merchantName: "Apollo Hospitals Dhaka",
    discountDetails: "20% discount on diagnostic tests and 10% on specialist consultations at Apollo Hospitals Dhaka with UCB Imperial Visa Signature cards.",
    discountDetailsBn: "ইউসিবি ইম্পেরিয়াল ভিসা সিগনেচার কার্ডে অ্যাপোলো হাসপাতাল ঢাকায় ডায়াগনস্টিক পরীক্ষায় ২০% ও বিশেষজ্ঞ পরামর্শে ১০% ছাড়।",
    city: "DHAKA",
    location: "Plot 81, Bashundhara R/A, Dhaka",
    bannerBadge: "Up to 20% OFF",
    terms: "Appointment required. Emergency services excluded.",
    termsBn: "অ্যাপয়েন্টমেন্ট আবশ্যক। জরুরি সেবা বাদে।",
    popularity: 87,
  },

  // Bank Asia
  {
    slug: "green-life-hospital-bank-asia",
    title: "Green Life Hospital: 15% Discount",
    titleBn: "গ্রিন লাইফ হাসপাতাল: ১৫% ছাড়",
    bankSlug: "bank-asia",
    bankName: "Bank Asia",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "Green Life Hospital (Green Road)",
    discountDetails: "15% discount on diagnostic tests at Green Life Hospital with Bank Asia Visa Platinum & Mastercard Titanium credit cards.",
    discountDetailsBn: "ব্যাংক এশিয়া ভিসা প্ল্যাটিনাম ও মাস্টারকার্ড টাইটানিয়াম কার্ডে গ্রিন লাইফ হাসপাতালে ডায়াগনস্টিক পরীক্ষায় ১৫% ছাড়।",
    city: "DHAKA",
    location: "32/A Green Road, Dhaka",
    bannerBadge: "15% OFF",
    terms: "Valid on weekdays. Doctor consultation fee excluded.",
    termsBn: "সপ্তাহের দিনে প্রযোজ্য। চিকিৎসক পরামর্শ ফি বাদে।",
    popularity: 78,
  },

  // Southeast Bank
  {
    slug: "united-hospital-southeast",
    title: "United Hospital: 18% Diagnostic Discount",
    titleBn: "ইউনাইটেড হাসপাতাল: ১৮% ডায়াগনস্টিক ছাড়",
    bankSlug: "southeast-bank",
    bankName: "Southeast Bank",
    cardTier: "SIGNATURE",
    category: "HEALTHCARE",
    merchantName: "United Hospital Gulshan",
    discountDetails: "18% discount on all diagnostic and lab tests at United Hospital Gulshan with Southeast Bank Visa Signature & Platinum cards.",
    discountDetailsBn: "সাউথইস্ট ব্যাংক ভিসা সিগনেচার ও প্ল্যাটিনাম কার্ডে ইউনাইটেড হাসপাতালে সব ডায়াগনস্টিক ও ল্যাব পরীক্ষায় ১৮% ছাড়।",
    city: "DHAKA",
    location: "Plot 15, Road 71, Gulshan-2, Dhaka",
    bannerBadge: "18% OFF",
    terms: "Appointment required. Doctor fees excluded.",
    termsBn: "অ্যাপয়েন্টমেন্ট আবশ্যক। চিকিৎসক ফি বাদে।",
    popularity: 79,
  },

  // Dhaka Bank
  {
    slug: "national-heart-dhaka-bank",
    title: "National Heart Foundation: 15% Diagnostic",
    titleBn: "ন্যাশনাল হার্ট ফাউন্ডেশন: ১৫% ডায়াগনস্টিক ছাড়",
    bankSlug: "dhaka-bank",
    bankName: "Dhaka Bank",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "National Heart Foundation Hospital",
    discountDetails: "15% discount on cardiac diagnostic tests at National Heart Foundation Hospital with Dhaka Bank Visa Platinum & Signature credit cards.",
    discountDetailsBn: "ঢাকা ব্যাংক ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে ন্যাশনাল হার্ট ফাউন্ডেশন হাসপাতালে কার্ডিয়াক ডায়াগনস্টিক পরীক্ষায় ১৫% ছাড়।",
    city: "DHAKA",
    location: "Mirpur 1, Dhaka",
    bannerBadge: "15% OFF",
    terms: "Valid on diagnostic services only. Appointment required.",
    termsBn: "শুধু ডায়াগনস্টিক সেবায় প্রযোজ্য। অ্যাপয়েন্টমেন্ট আবশ্যক।",
    popularity: 76,
  },

  // MTB
  {
    slug: "medinova-diagnostic-mtb",
    title: "Medinova Medical Services: 20% Discount",
    titleBn: "মেডিনোভা মেডিকেল সার্ভিসেস: ২০% ছাড়",
    bankSlug: "mutual-trust-bank",
    bankName: "MTB",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "Medinova Medical Services",
    discountDetails: "20% discount on all pathology, radiology and diagnostic tests at Medinova with MTB Visa Signature & Angona Mastercard Platinum.",
    discountDetailsBn: "এমটিবি ভিসা সিগনেচার ও অঙ্গনা মাস্টারকার্ড প্ল্যাটিনাম কার্ডে মেডিনোভায় সব প্যাথলজি, রেডিওলজি ও ডায়াগনস্টিক পরীক্ষায় ২০% ছাড়।",
    city: "NATIONWIDE",
    bannerBadge: "20% OFF",
    terms: "Valid at all Medinova branches. Doctor fees excluded.",
    termsBn: "মেডিনোভার সব শাখায় প্রযোজ্য। চিকিৎসক ফি বাদে।",
    popularity: 80,
  },

  // HSBC
  {
    slug: "aga-khan-dhaka-hsbc",
    title: "Aga Khan Hospital: 25% Diagnostic with HSBC",
    titleBn: "আগা খান হাসপাতাল: এইচএসবিসি কার্ডে ২৫% ডায়াগনস্টিক ছাড়",
    bankSlug: "hsbc-bangladesh",
    bankName: "HSBC Bangladesh",
    cardTier: "PLATINUM",
    category: "HEALTHCARE",
    merchantName: "Aga Khan Hospital Dhaka",
    discountDetails: "25% discount on all diagnostic services at Aga Khan Hospital Dhaka (Gulshan) with HSBC Bangladesh Visa Platinum & Signature cards.",
    discountDetailsBn: "এইচএসবিসি বাংলাদেশ ভিসা প্ল্যাটিনাম ও সিগনেচার কার্ডে ঢাকার (গুলশান) আগা খান হাসপাতালে সব ডায়াগনস্টিক সেবায় ২৫% ছাড়।",
    city: "DHAKA",
    location: "Road 2, Gulshan-1, Dhaka",
    bannerBadge: "25% OFF",
    terms: "Appointment required. Emergency and ICU services excluded.",
    termsBn: "অ্যাপয়েন্টমেন্ট আবশ্যক। জরুরি ও আইসিইউ সেবা বাদে।",
    popularity: 88,
  },
];
