import { CreditCardSeed } from "./creditSeed";

/**
 * Additional credit cards for Bangladesh banks — v2
 * Adds ~55 new cards across major banks to bring total close to 100
 */
export const MORE_CREDIT_CARDS: { bankSlug: string; cards: CreditCardSeed[] }[] = [
  // ── BRAC Bank ──────────────────────────────────────────────────────────────
  {
    bankSlug: "brac-bank",
    cards: [
      {
        slug: "brac-visa-gold",
        name: "BRAC Bank Visa Gold Credit Card",
        nameBn: "ব্র্যাক ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "Spend ৳1,20,000 in a year for 100% waiver",
        feeWaiverConditionBn: "বছরে ১,২০,০০০ টাকা খরচ করলে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#B45309",
        features: ["0% EMI on shopping", "B1G1 dining at partner restaurants", "Global acceptance"],
        featuresBn: ["শপিংয়ে ০% ইএমআই সুবিধা", "পার্টনার রেস্তোরাঁয় ১টি কিনলে ১টি ফ্রি", "বিশ্বব্যাপী গ্রহণযোগ্যতা"],
        popularity: 74,
      },
      {
        slug: "brac-mastercard-titanium",
        name: "BRAC Bank Mastercard Titanium Credit Card",
        nameBn: "ব্র্যাক ব্যাংক মাস্টারকার্ড টাইটেনিয়াম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "TITANIUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions annually for fee waiver",
        feeWaiverConditionBn: "বার্ষিক ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "2 complimentary Balaka Lounge visits per year at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে বছরে ২ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent locally, 2x overseas",
        rewardSummaryBn: "দেশীয় খরচে প্রতি ১০০ টাকায় ১.৫ পয়েন্ট, বিদেশে ২গুণ",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#374151",
        features: ["Lounge access at HSIA", "0% EMI up to 24 months", "Fuel surcharge waiver", "Travel insurance up to $50,000"],
        featuresBn: ["হযরত শাহজালাল বিমানবন্দরে লাউঞ্জ সুবিধা", "২৪ মাস পর্যন্ত ০% সুদে কিস্তি", "ফুয়েল সারচার্জ মওকুফ", "৫০,০০০ ডলার পর্যন্ত ভ্রমণ বীমা"],
        popularity: 79,
      },
    ],
  },

  // ── Dutch-Bangla Bank (DBBL) ─────────────────────────────────────────────────
  {
    bankSlug: "dutch-bangla-bank",
    cards: [
      {
        slug: "dbbl-nexus-visa-signature",
        name: "DBBL Nexus-Visa Signature Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 7000,
        feeWaiverCondition: "15 swipes annually",
        feeWaiverConditionBn: "বছরে ১৫ বার কার্ড সোয়াইপ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 80000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at HSIA with guest",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা (অতিথিসহ)",
        rewardType: "REWARDS",
        rewardSummary: "2 Reward points per ৳100 spent · Triple points overseas",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · বিদেশে তিনগুণ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1D4ED8",
        features: ["Unlimited airport lounge", "Triple reward points abroad", "Travel insurance", "25% discount at top restaurants"],
        featuresBn: ["আনলিমিটেড এয়ারপোর্ট লাউঞ্জ সুবিধা", "বিদেশে তিনগুণ পয়েন্ট", "ভ্রমণ বীমা", "শীর্ষ রেস্তোরাঁয় ২৫% ছাড়"],
        popularity: 88,
      },
      {
        slug: "dbbl-nexus-mastercard-gold",
        name: "DBBL Nexus-Mastercard Gold Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "Spend ৳1,00,000 per year for waiver",
        feeWaiverConditionBn: "বছরে ১ লাখ টাকা খরচ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#92400E",
        features: ["0% EMI facility", "Online transaction security", "Wide merchant acceptance"],
        featuresBn: ["০% ইএমআই সুবিধা", "অনলাইন লেনদেন নিরাপত্তা", "বিস্তৃত মার্চেন্ট গ্রহণযোগ্যতা"],
        popularity: 70,
      },
    ],
  },

  // ── Eastern Bank (EBL) ────────────────────────────────────────────────────────
  {
    bankSlug: "eastern-bank",
    cards: [
      {
        slug: "ebl-visa-platinum",
        name: "EBL Visa Platinum Credit Card",
        nameBn: "ইবিএল ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 4000,
        feeWaiverCondition: "Spend ৳1,80,000 in a year",
        feeWaiverConditionBn: "বছরে ১,৮০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 Reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#065F46",
        features: ["Balaka lounge access", "0% EMI on electronics and appliances", "B1G1 dining at EBL partner outlets"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "ইলেকট্রনিক্স ও আসবাবে ০% ইএমআই", "ইবিএল পার্টনারে ১টি কিনলে ১টি ফ্রি"],
        popularity: 81,
      },
      {
        slug: "ebl-mastercard-world",
        name: "EBL Mastercard World Credit Card",
        nameBn: "ইবিএল মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 12000,
        feeWaiverCondition: "18 transactions or ৳4,00,000 annual spend",
        feeWaiverConditionBn: "১৮টি লেনদেন বা বছরে ৪ লাখ টাকা খরচ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 150000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Mastercard Lounge Access + LoungeKey globally",
        loungeDetailsBn: "মাস্টারকার্ড লাউঞ্জ ও বিশ্বব্যাপী লাউঞ্জকি অ্যাক্সেস (আনলিমিটেড)",
        rewardType: "MILES",
        rewardSummary: "3 Miles per ৳100 local, 5 Miles overseas · Redeem at 50+ airlines",
        rewardSummaryBn: "দেশে প্রতি ১০০ টাকায় ৩ মাইলস, বিদেশে ৫ মাইলস · ৫০+ এয়ারলাইনে রিডিম",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#0F172A",
        features: ["Global LoungeKey access", "Air miles for 50+ airlines", "Concierge service 24/7", "Travel & medical insurance up to $1,00,000"],
        featuresBn: ["বিশ্বব্যাপী লাউঞ্জকি সুবিধা", "৫০+ এয়ারলাইনে এয়ার মাইলস", "২৪/৭ কনসিয়ার্জ সেবা", "১,০০,০০০ ডলার পর্যন্ত ভ্রমণ ও চিকিৎসা বীমা"],
        popularity: 86,
      },
    ],
  },

  // ── Standard Chartered ─────────────────────────────────────────────────────
  {
    bankSlug: "standard-chartered-bank",
    cards: [
      {
        slug: "sc-mastercard-platinum",
        name: "Standard Chartered Mastercard Platinum Credit Card",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 4500,
        feeWaiverCondition: "Spend ৳2,00,000 a year",
        feeWaiverConditionBn: "বছরে ২ লাখ টাকা খরচ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits annually",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "360° Rewards — 1 point per ৳100, redeem for flights, shopping & more",
        rewardSummaryBn: "৩৬০° রিওয়ার্ড — প্রতি ১০০ টাকায় ১ পয়েন্ট, ফ্লাইট, শপিং ও আরও অনেকে রিডিম",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#0EA5E9",
        features: ["360° Reward points", "Fuel surcharge waiver", "0% interest EMI at partner merchants", "Global ATM access"],
        featuresBn: ["৩৬০° রিওয়ার্ড পয়েন্ট", "ফুয়েল সারচার্জ মওকুফ", "পার্টনার মার্চেন্টে ০% ইএমআই", "বিশ্বব্যাপী ATM সুবিধা"],
        popularity: 85,
      },
      {
        slug: "sc-visa-gold",
        name: "Standard Chartered Visa Gold Credit Card",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "৳80,000 annual spend",
        feeWaiverConditionBn: "বার্ষিক ৮০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#D97706",
        features: ["Visa global acceptance", "0% EMI at select stores", "Reward points redemption"],
        featuresBn: ["ভিসার বৈশ্বিক গ্রহণযোগ্যতা", "নির্বাচিত দোকানে ০% ইএমআই", "রিওয়ার্ড পয়েন্ট রিডিম"],
        popularity: 71,
      },
    ],
  },

  // ── Prime Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "prime-bank",
    cards: [
      {
        slug: "prime-bank-visa-signature",
        name: "Prime Bank Visa Signature Credit Card",
        nameBn: "প্রাইম ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 75000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at Hazrat Shahjalal Airport",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 Reward points per ৳100 · Bonus points on dining & travel",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · ডাইনিং ও ভ্রমণে বোনাস পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#6D28D9",
        features: ["Unlimited lounge access", "Visa Signature privileges", "Travel insurance", "B1G1 at 5-star hotels"],
        featuresBn: ["আনলিমিটেড লাউঞ্জ সুবিধা", "ভিসা সিগনেচার সুবিধাসমূহ", "ভ্রমণ বীমা", "পাঁচতারা হোটেলে ১টি কিনলে ১টি ফ্রি"],
        popularity: 83,
      },
      {
        slug: "prime-bank-mastercard-gold",
        name: "Prime Bank Mastercard Gold Credit Card",
        nameBn: "প্রাইম ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "12 transactions in a calendar year",
        feeWaiverConditionBn: "ক্যালেন্ডার বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#78350F",
        features: ["Dual currency usage", "0% EMI facility", "Worldwide acceptance"],
        featuresBn: ["ডুয়েল কারেন্সি সুবিধা", "০% সুদে ইএমআই সুবিধা", "বিশ্বব্যাপী গ্রহণযোগ্যতা"],
        popularity: 72,
      },
    ],
  },

  // ── Bank Asia ─────────────────────────────────────────────────────────────
  {
    bankSlug: "bank-asia",
    cards: [
      {
        slug: "bank-asia-visa-platinum",
        name: "Bank Asia Visa Platinum Credit Card",
        nameBn: "ব্যাংক এশিয়া ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "Spend ৳1,20,000 per year",
        feeWaiverConditionBn: "বছরে ১,২০,০০০ টাকা খরচ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "1% cashback on all purchases, 2% on online shopping",
        rewardSummaryBn: "সব কেনাকাটায় ১% ক্যাশব্যাক, অনলাইন শপিংয়ে ২%",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#0369A1",
        features: ["Cashback on all purchases", "0% EMI up to 18 months", "Airport lounge access", "Fuel surcharge waiver"],
        featuresBn: ["সব কেনাকাটায় ক্যাশব্যাক", "১৮ মাস পর্যন্ত ০% ইএমআই", "এয়ারপোর্ট লাউঞ্জ সুবিধা", "ফুয়েল সারচার্জ মওকুফ"],
        popularity: 77,
      },
      {
        slug: "bank-asia-mastercard-world",
        name: "Bank Asia Mastercard World Credit Card",
        nameBn: "ব্যাংক এশিয়া মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 10000,
        feeWaiverCondition: "20 transactions or ৳3,50,000 annual spend",
        feeWaiverConditionBn: "২০ লেনদেন বা বছরে ৩,৫০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 120000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge + LoungeKey global access",
        loungeDetailsBn: "আনলিমিটেড বলাকা লাউঞ্জ ও বিশ্বব্যাপী লাউঞ্জকি সুবিধা",
        rewardType: "MILES",
        rewardSummary: "2 Miles per ৳100 local, 4 Miles overseas",
        rewardSummaryBn: "দেশে প্রতি ১০০ টাকায় ২ মাইলস, বিদেশে ৪ মাইলস",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#1E1B4B",
        features: ["LoungeKey global access", "Air miles program", "Concierge 24/7", "Medical & travel insurance"],
        featuresBn: ["বিশ্বব্যাপী লাউঞ্জকি সুবিধা", "এয়ার মাইলস প্রোগ্রাম", "২৪/৭ কনসিয়ার্জ সেবা", "চিকিৎসা ও ভ্রমণ বীমা"],
        popularity: 80,
      },
    ],
  },

  // ── Pubali Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "pubali-bank",
    cards: [
      {
        slug: "pubali-visa-gold",
        name: "Pubali Bank Visa Gold Credit Card",
        nameBn: "পূবালী ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 1500,
        feeWaiverCondition: "10 transactions in a year",
        feeWaiverConditionBn: "বছরে ১০ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#059669",
        features: ["Low annual fee", "0% EMI facility", "Wide local acceptance"],
        featuresBn: ["কম বার্ষিক ফি", "০% ইএমআই সুবিধা", "ব্যাপক স্থানীয় গ্রহণযোগ্যতা"],
        popularity: 65,
      },
      {
        slug: "pubali-mastercard-classic",
        name: "Pubali Bank Mastercard Classic Credit Card",
        nameBn: "পূবালী ব্যাংক মাস্টারকার্ড ক্লাসিক ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "CLASSIC",
        annualFee: 800,
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 40,
        minIncome: 15000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "Basic rewards program",
        rewardSummaryBn: "বেসিক রিওয়ার্ড প্রোগ্রাম",
        zeroPctEmiAvailable: false,
        contactless: false,
        cardColor: "#6B7280",
        features: ["Affordable entry-level card", "Mastercard global acceptance", "Simple rewards"],
        featuresBn: ["সাশ্রয়ী প্রবেশ-স্তরের কার্ড", "মাস্টারকার্ডের বৈশ্বিক গ্রহণযোগ্যতা", "সহজ রিওয়ার্ড"],
        popularity: 55,
      },
    ],
  },

  // ── Sonali Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "sonali-bank",
    cards: [
      {
        slug: "sonali-mastercard-platinum",
        name: "Sonali Bank Mastercard Platinum Credit Card",
        nameBn: "সোনালী ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 2500,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#15803D",
        features: ["Government bank reliability", "Dual currency", "0% EMI", "Nationwide acceptance"],
        featuresBn: ["সরকারি ব্যাংকের নির্ভরযোগ্যতা", "ডুয়াল কারেন্সি", "০% ইএমআই", "সারাদেশে গ্রহণযোগ্যতা"],
        popularity: 60,
      },
    ],
  },

  // ── Dhaka Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "dhaka-bank",
    cards: [
      {
        slug: "dhaka-bank-visa-platinum",
        name: "Dhaka Bank Visa Platinum Credit Card",
        nameBn: "ঢাকা ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Spend ৳1,50,000 annually",
        feeWaiverConditionBn: "বছরে ১,৫০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 free Balaka lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 · Extra points on fuel",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট · জ্বালানিতে অতিরিক্ত পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#B91C1C",
        features: ["Airport lounge access", "Fuel surcharge waiver", "0% EMI on partner merchants", "Travel insurance"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "ফুয়েল সারচার্জ মওকুফ", "পার্টনারে ০% ইএমআই", "ভ্রমণ বীমা"],
        popularity: 75,
      },
      {
        slug: "dhaka-bank-mastercard-gold",
        name: "Dhaka Bank Mastercard Gold Credit Card",
        nameBn: "ঢাকা ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "10 transactions per year",
        feeWaiverConditionBn: "বছরে ১০ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#D97706",
        features: ["0% EMI", "Reward points", "Broad merchant network"],
        featuresBn: ["০% ইএমআই", "রিওয়ার্ড পয়েন্ট", "বিস্তৃত মার্চেন্ট নেটওয়ার্ক"],
        popularity: 66,
      },
    ],
  },

  // ── Southeast Bank ────────────────────────────────────────────────────────
  {
    bankSlug: "southeast-bank",
    cards: [
      {
        slug: "southeast-visa-signature",
        name: "Southeast Bank Visa Signature Credit Card",
        nameBn: "সাউথইস্ট ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 swipes per year",
        feeWaiverConditionBn: "বছরে ১৫ সোয়াইপে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 points per ৳100 · Bonus points on overseas spend",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · বিদেশে বোনাস পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#1E40AF",
        features: ["Unlimited airport lounge", "International spend rewards", "Visa Signature perks", "0% EMI"],
        featuresBn: ["আনলিমিটেড এয়ারপোর্ট লাউঞ্জ", "আন্তর্জাতিক খরচে রিওয়ার্ড", "ভিসা সিগনেচার সুবিধা", "০% ইএমআই"],
        popularity: 76,
      },
      {
        slug: "southeast-mastercard-platinum",
        name: "Southeast Bank Mastercard Platinum Credit Card",
        nameBn: "সাউথইস্ট ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "৳1,20,000 annual spend",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#6D28D9",
        features: ["Reward points", "0% EMI", "Dual currency"],
        featuresBn: ["রিওয়ার্ড পয়েন্ট", "০% ইএমআই", "ডুয়াল কারেন্সি"],
        popularity: 69,
      },
    ],
  },

  // ── Mercantile Bank ────────────────────────────────────────────────────────
  {
    bankSlug: "mercantile-bank",
    cards: [
      {
        slug: "mercantile-visa-signature",
        name: "Mercantile Bank Visa Signature Credit Card",
        nameBn: "মার্কেন্টাইল ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions annually",
        feeWaiverConditionBn: "বছরে ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#7C3AED",
        features: ["Airport lounge access", "0% EMI", "Travel insurance", "Visa Signature benefits"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "০% ইএমআই", "ভ্রমণ বীমা", "ভিসা সিগনেচার সুবিধা"],
        popularity: 74,
      },
      {
        slug: "mercantile-mastercard-gold",
        name: "Mercantile Bank Mastercard Gold Credit Card",
        nameBn: "মার্কেন্টাইল ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "10 transactions per year",
        feeWaiverConditionBn: "বছরে ১০ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#B45309",
        features: ["Affordable fee", "0% EMI", "Broad acceptance"],
        featuresBn: ["সাশ্রয়ী ফি", "০% ইএমআই", "বিস্তৃত গ্রহণযোগ্যতা"],
        popularity: 62,
      },
    ],
  },

  // ── IFIC Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "ific-bank",
    cards: [
      {
        slug: "ific-visa-signature",
        name: "IFIC Bank Visa Signature Credit Card",
        nameBn: "আইএফআইসি ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge visits at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 Reward points per ৳100 · 3x on overseas",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট · বিদেশে ৩গুণ",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#0C4A6E",
        features: ["Unlimited airport lounge", "Triple points abroad", "B1G1 dining", "Travel insurance"],
        featuresBn: ["আনলিমিটেড এয়ারপোর্ট লাউঞ্জ", "বিদেশে তিনগুণ পয়েন্ট", "ডাইনিং-এ ১টি কিনলে ১টি ফ্রি", "ভ্রমণ বীমা"],
        popularity: 77,
      },
    ],
  },

  // ── AB Bank ───────────────────────────────────────────────────────────────
  {
    bankSlug: "ab-bank",
    cards: [
      {
        slug: "ab-bank-visa-platinum",
        name: "AB Bank Visa Platinum Credit Card",
        nameBn: "এবি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Spend ৳1,50,000 in a year",
        feeWaiverConditionBn: "বছরে ১,৫০,০০০ টাকা খরচ করলে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits annually",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#DC2626",
        features: ["Lounge access", "0% EMI", "Dual currency", "B1G1 dining"],
        featuresBn: ["লাউঞ্জ সুবিধা", "০% ইএমআই", "ডুয়াল কারেন্সি", "ডাইনিং-এ ১টি কিনলে ১টি ফ্রি"],
        popularity: 73,
      },
      {
        slug: "ab-bank-mastercard-gold",
        name: "AB Bank Mastercard Gold Credit Card",
        nameBn: "এবি ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "৳80,000 annual spend",
        feeWaiverConditionBn: "বার্ষিক ৮০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: false,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        cardColor: "#92400E",
        features: ["Affordable card", "0% EMI", "Worldwide acceptance"],
        featuresBn: ["সাশ্রয়ী কার্ড", "০% ইএমআই", "বিশ্বব্যাপী গ্রহণযোগ্যতা"],
        popularity: 63,
      },
    ],
  },

  // ── Trust Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "trust-bank",
    cards: [
      {
        slug: "trust-bank-visa-platinum",
        name: "Trust Bank Visa Platinum Credit Card",
        nameBn: "ট্রাস্ট ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#166534",
        features: ["Airport lounge", "Army bank trust", "0% EMI", "Dual currency"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ", "সেনাবাহিনীর ব্যাংক বিশ্বস্ততা", "০% ইএমআই", "ডুয়াল কারেন্সি"],
        popularity: 70,
      },
    ],
  },

  // ── Jamuna Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "jamuna-bank",
    cards: [
      {
        slug: "jamuna-visa-platinum",
        name: "Jamuna Bank Visa Platinum Credit Card",
        nameBn: "যমুনা ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 free Balaka Lounge visits per year at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#0891B2",
        features: ["Lounge access", "0% EMI up to 18 months", "Dual currency facility", "B1G1 offers"],
        featuresBn: ["লাউঞ্জ সুবিধা", "১৮ মাস পর্যন্ত ০% ইএমআই", "ডুয়াল কারেন্সি সুবিধা", "বি-ওয়ান-গেট-ওয়ান অফার"],
        popularity: 68,
      },
    ],
  },

  // ── Premier Bank ──────────────────────────────────────────────────────────
  {
    bankSlug: "premier-bank",
    cards: [
      {
        slug: "premier-mastercard-platinum",
        name: "Premier Bank Mastercard Platinum Credit Card",
        nameBn: "প্রিমিয়ার ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 complimentary Balaka Lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে বিনামূল্যে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        cardColor: "#9333EA",
        features: ["Airport lounge access", "0% EMI", "Reward points", "Dual currency"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "০% ইএমআই", "রিওয়ার্ড পয়েন্ট", "ডুয়াল কারেন্সি"],
        popularity: 71,
      },
    ],
  },

  // ── HSBC Bangladesh ───────────────────────────────────────────────────────
  {
    bankSlug: "hsbc-bangladesh",
    cards: [
      {
        slug: "hsbc-visa-signature",
        name: "HSBC Visa Signature Credit Card",
        nameBn: "এইচএসবিসি ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 10000,
        feeWaiverCondition: "Spend ৳3,60,000 annually",
        feeWaiverConditionBn: "বছরে ৩,৬০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 150000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited DragonPass lounge access globally",
        loungeDetailsBn: "বিশ্বব্যাপী আনলিমিটেড ড্র্যাগনপাস লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "3 Reward points per ৳100 · Global reward redemption",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৩ পয়েন্ট · বিশ্বব্যাপী রিডিম সুবিধা",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        cardColor: "#991B1B",
        features: ["Global DragonPass lounge", "HSBC global network", "Concierge 24/7", "Travel insurance up to $1,50,000"],
        featuresBn: ["বিশ্বব্যাপী ড্র্যাগনপাস লাউঞ্জ", "এইচএসবিসির গ্লোবাল নেটওয়ার্ক", "২৪/৭ কনসিয়ার্জ সেবা", "১,৫০,০০০ ডলার পর্যন্ত ভ্রমণ বীমা"],
        popularity: 90,
      },
      {
        slug: "hsbc-mastercard-gold",
        name: "HSBC Mastercard Gold Credit Card",
        nameBn: "এইচএসবিসি মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 3500,
        feeWaiverCondition: "Spend ৳1,50,000 annually",
        feeWaiverConditionBn: "বছরে ১,৫০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 · HSBC rewards catalog",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট · এইচএসবিসি রিওয়ার্ড ক্যাটালগ",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#DC2626",
        features: ["HSBC trust & reliability", "Global acceptance", "0% EMI on purchases", "Fuel surcharge waiver"],
        featuresBn: ["এইচএসবিসির বিশ্বাসযোগ্যতা", "বৈশ্বিক গ্রহণযোগ্যতা", "কেনাকাটায় ০% ইএমআই", "ফুয়েল সারচার্জ মওকুফ"],
        popularity: 82,
      },
    ],
  },

  // ── Midland Bank ─────────────────────────────────────────────────────────
  {
    bankSlug: "midland-bank",
    cards: [
      {
        slug: "midland-visa-signature",
        name: "Midland Bank Visa Signature Credit Card",
        nameBn: "মিডল্যান্ড ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#0F766E",
        features: ["Airport lounge access", "2x reward points", "0% EMI", "Visa Signature benefits"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "২গুণ রিওয়ার্ড পয়েন্ট", "০% ইএমআই", "ভিসা সিগনেচার সুবিধা"],
        popularity: 69,
      },
    ],
  },

  // ── Community Bank ────────────────────────────────────────────────────────
  {
    bankSlug: "community-bank",
    cards: [
      {
        slug: "community-bank-visa-signature",
        name: "Community Bank Visa Signature Credit Card",
        nameBn: "কমিউনিটি ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited Balaka Lounge access at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল বিমানবন্দরে আনলিমিটেড বলাকা লাউঞ্জ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        cardColor: "#0369A1",
        features: ["Airport lounge", "Police bank reliability", "0% EMI", "Dual currency"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ", "পুলিশ ব্যাংকের নির্ভরযোগ্যতা", "০% ইএমআই", "ডুয়াল কারেন্সি"],
        popularity: 65,
      },
    ],
  },

  // ── EXIM Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "exim-bank",
    cards: [
      {
        slug: "exim-mastercard-platinum",
        name: "EXIM Bank Mastercard Platinum Credit Card",
        nameBn: "এক্সিম ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 Balaka Lounge visits annually",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জে প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#15803D",
        features: ["Shariah-compliant (conventional option)", "Lounge access", "0% EMI", "Dual currency"],
        featuresBn: ["শরিয়াহ সম্মত (প্রচলিত বিকল্পও আছে)", "লাউঞ্জ সুবিধা", "০% ইএমআই", "ডুয়াল কারেন্সি"],
        popularity: 67,
      },
    ],
  },

  // ── Al-Arafah Islami Bank ─────────────────────────────────────────────────
  {
    bankSlug: "al-arafah-islami-bank",
    cards: [
      {
        slug: "aibl-tayyib-platinum",
        name: "AIBL Tayyib Islamic Platinum Credit Card",
        nameBn: "এআইবিএল তাইয়্যিব ইসলামিক প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 Balaka lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জ প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Shariah-compliant reward program — 1.5 points per ৳100",
        rewardSummaryBn: "শরিয়াহ-সম্মত রিওয়ার্ড প্রোগ্রাম — প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#166534",
        features: ["100% Shariah compliant", "Lounge access", "0% EMI", "Islamic banking principles"],
        featuresBn: ["সম্পূর্ণ শরিয়াহ সম্মত", "লাউঞ্জ সুবিধা", "০% ইএমআই", "ইসলামী ব্যাংকিং নীতি"],
        popularity: 72,
      },
    ],
  },

  // ── Shahjalal Islami Bank ─────────────────────────────────────────────────
  {
    bankSlug: "shahjalal-islami-bank",
    cards: [
      {
        slug: "sjibl-mastercard-platinum",
        name: "SJIBL Mastercard Platinum Credit Card",
        nameBn: "শাহজালাল ইসলামী ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 3000,
        feeWaiverCondition: "12 transactions per year",
        feeWaiverConditionBn: "বছরে ১২ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "4 Balaka Lounge visits per year",
        loungeDetailsBn: "বছরে ৪ বার বলাকা লাউঞ্জ প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "Shariah-compliant 1.5 points per ৳100",
        rewardSummaryBn: "শরিয়াহ-সম্মত প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#065F46",
        features: ["Shariah compliant", "Airport lounge", "0% EMI", "Dual currency"],
        featuresBn: ["শরিয়াহ সম্মত", "এয়ারপোর্ট লাউঞ্জ", "০% ইএমআই", "ডুয়াল কারেন্সি"],
        popularity: 70,
      },
    ],
  },
];
