import type { CreditCardSeed } from "./creditSeed";

/**
 * Credit cards for the new banks + additional banks across Bangladesh
 */
export const NEW_BANK_CREDIT_CARDS: { bankSlug: string; cards: CreditCardSeed[] }[] = [
  // ── National Bank ──────────────────────────────────────────────────────────
  {
    bankSlug: "national-bank",
    cards: [
      {
        slug: "nbl-visa-classic",
        name: "NBL Visa Classic Credit Card",
        nameBn: "এনবিএল ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "First year free; waived on 15 transactions annually",
        feeWaiverConditionBn: "প্রথম বছর ফ্রি; বার্ষিক ১৫ লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকা খরচে ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#1E40AF",
        features: ["Free for first year", "0% EMI at 500+ merchants", "Online secure payments"],
        featuresBn: ["প্রথম বছর বিনামূল্যে", "৫০০+ দোকানে ০% ইএমআই", "অনলাইন নিরাপদ লেনদেন"],
        popularity: 58,
      },
      {
        slug: "nbl-visa-gold",
        name: "NBL Visa Gold Credit Card",
        nameBn: "এনবিএল ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বছরে ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকা খরচে ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#D97706",
        features: ["1.5x reward points", "Complimentary travel insurance", "Dining discounts"],
        featuresBn: ["১.৫x রিওয়ার্ড পয়েন্ট", "বিনামূল্যে ভ্রমণ বীমা", "ডাইনিং ছাড়"],
        popularity: 63,
      },
      {
        slug: "nbl-mastercard-platinum",
        name: "NBL Mastercard Platinum Credit Card",
        nameBn: "এনবিএল মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,40,000",
        feeWaiverConditionBn: "বছরে ২,৪০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকা খরচে ২ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#334155",
        features: ["Balaka Lounge access", "2x reward points", "Zero liability protection", "Hotel dining deals"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "২ গুণ রিওয়ার্ড", "জিরো লায়াবিলিটি সুরক্ষা", "হোটেল ডাইনিং অফার"],
        popularity: 68,
      },
    ],
  },

  // ── NCC Bank ──────────────────────────────────────────────────────────────
  {
    bankSlug: "ncc-bank",
    cards: [
      {
        slug: "ncc-visa-classic",
        name: "NCC Bank Visa Classic Credit Card",
        nameBn: "এনসিসি ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 12 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#1D4ED8",
        features: ["0% EMI on electronics", "SMS banking alerts", "Nationwide branch support"],
        featuresBn: ["ইলেকট্রনিক্সে ০% ইএমআই", "এসএমএস ব্যাংকিং সতর্কবার্তা", "সারাদেশে শাখা সহায়তা"],
        popularity: 54,
      },
      {
        slug: "ncc-visa-gold",
        name: "NCC Bank Visa Gold Credit Card",
        nameBn: "এনসিসি ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#B45309",
        features: ["Up to 18-month EMI", "1.5x reward points", "Hospital discounts"],
        featuresBn: ["১৮ মাস পর্যন্ত ইএমআই", "১.৫ গুণ রিওয়ার্ড", "হাসপাতালে বিশেষ ছাড়"],
        popularity: 60,
      },
      {
        slug: "ncc-visa-platinum",
        name: "NCC Bank Visa Platinum Credit Card",
        nameBn: "এনসিসি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 4500,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Dhaka airport Balaka lounge",
        loungeDetailsBn: "ঢাকা বিমানবন্দরের বলাকা লাউঞ্জে ফ্রি প্রবেশ সুবিধা",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#0F172A",
        features: ["Airport lounge access", "2x reward points", "B1G1 dining privileges", "Travel insurance"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "২x রিওয়ার্ড পয়েন্ট", "১টি কিনলে ১টি ফ্রি ডাইনিং", "ভ্রমণ বীমা"],
        popularity: 67,
      },
    ],
  },

  // ── ONE Bank ──────────────────────────────────────────────────────────────
  {
    bankSlug: "one-bank",
    cards: [
      {
        slug: "one-bank-visa-classic",
        name: "ONE Bank Visa Classic Credit Card",
        nameBn: "ওয়ান ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 POS/E-com transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1% cashback on online grocery shopping",
        rewardSummaryBn: "অনলাইন মুদিতে ১% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#0284C7",
        features: ["Digital card onboarding", "0% Smart EMI", "Tap & Pay contactless"],
        featuresBn: ["ডিজিটাল কার্ড সুবিধা", "০% স্মার্ট ইএমআই", "ট্যাপ অ্যান্ড পে কন্ট্যাক্টলেস"],
        popularity: 58,
      },
      {
        slug: "one-bank-mastercard-gold",
        name: "ONE Bank Mastercard Gold Credit Card",
        nameBn: "ওয়ান ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1.5% cashback on supermarket & dining",
        rewardSummaryBn: "সুপারমার্কেট ও রেস্তোরাঁয় ১.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#D97706",
        features: ["1.5% cashback perks", "Emergency card replacement", "Discounts at 300+ stores"],
        featuresBn: ["১.৫% ক্যাশব্যাক", "জরুরি কার্ড প্রতিস্থাপন", "৩০০+ দোকানে ছাড়"],
        popularity: 64,
      },
      {
        slug: "one-bank-visa-platinum",
        name: "ONE Bank Visa Platinum Credit Card",
        nameBn: "ওয়ান ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,40,000",
        feeWaiverConditionBn: "বার্ষিক ২,৪০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2% cashback on lifestyle, dining & flight bookings",
        rewardSummaryBn: "লাইফস্টাইল, খাবার ও বিমানে ২% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#1E293B",
        features: ["Airport lounge access", "2% lifestyle cashback", "B1G1 buffet deals", "Travel takaful protection"],
        featuresBn: ["লাউঞ্জ সুবিধা", "২% ক্যাশব্যাক", "১টি কিনলে ১টি ফ্রি বুফে", "ভ্রমণ সুরক্ষা"],
        popularity: 71,
      },
    ],
  },

  // ── First Security Islami Bank ─────────────────────────────────────────────
  {
    bankSlug: "first-security-islami-bank",
    cards: [
      {
        slug: "fsibl-visa-classic-islamic",
        name: "FSIBL Visa Islamic Classic Credit Card",
        nameBn: "এফএসআইবিএল ভিসা ইসলামিক ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 Shariah compliant transactions/year",
        feeWaiverConditionBn: "বার্ষিক ১৫টি হালাল লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ হালাল রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#15803D",
        features: ["100% Riba-free Islamic banking", "Halal spend reward points", "0% profit-margin installment"],
        featuresBn: ["১০০% সুদহীন ইসলামী ব্যাংকিং", "হালাল কেনাকাটায় পয়েন্ট", "০% কিস্তি সুবিধা"],
        popularity: 62,
      },
      {
        slug: "fsibl-visa-gold-islamic",
        name: "FSIBL Visa Islamic Gold Credit Card",
        nameBn: "এফএসআইবিএল ভিসা ইসলামিক গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#047857",
        features: ["Umrah EMI scheme", "Islamic Takaful coverage", "Zakat auto calculation", "No compound charges"],
        featuresBn: ["ওমরাহ কিস্তি সুবিধা", "ইসলামিক তাকাফুল সুরক্ষা", "যাকাত ক্যালকুলেশন", "কোনো চক্রবৃদ্ধি চার্জ নেই"],
        popularity: 68,
      },
      {
        slug: "fsibl-visa-platinum-islamic",
        name: "FSIBL Visa Islamic Platinum Credit Card",
        nameBn: "এফএসআইবিএল ভিসা ইসলামিক প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5500,
        feeWaiverCondition: "Waived on annual spend of ৳2,40,000",
        feeWaiverConditionBn: "বার্ষিক ২,৪০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#064E3B",
        features: ["Airport lounge access", "Umrah package zero EMI", "Halal 5-star hotel B1G1", "Complimentary Takaful"],
        featuresBn: ["এয়ারপোর্ট লাউঞ্জ সুবিধা", "ওমরাহ প্যাকেজে ০% কিস্তি", "হালাল ফাইভ-স্টার হোটেলে বি১জি১", "ফ্রি তাকাফুল বীমা"],
        popularity: 76,
      },
    ],
  },

  // ── Agrani Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "agrani-bank",
    cards: [
      {
        slug: "agrani-visa-classic",
        name: "Agrani Bank Visa Classic Credit Card",
        nameBn: "অগ্রণী ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1000,
        feeWaiverCondition: "Waived for government and semi-gov employees",
        feeWaiverConditionBn: "সরকারি ও আধা-সরকারি কর্মচারীদের জন্য ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#991B1B",
        features: ["Special low 18% annual interest rate", "Salary-linked auto repayment", "Utility bill payment"],
        featuresBn: ["১৮% বিশেষ কম সুদের হার", "বেতন-সংযুক্ত অটো পরিশোধ", "বিল পরিশোধ সুবিধা"],
        popularity: 61,
      },
      {
        slug: "agrani-visa-gold",
        name: "Agrani Bank Visa Gold Credit Card",
        nameBn: "অগ্রণী ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#B91C1C",
        features: ["Low interest rate 18%", "State-backed financial security", "Emergency cash advance"],
        featuresBn: ["১৮% কম সুদের হার", "রাষ্ট্রীয় ব্যাংকের নিরাপত্তা", "জরুরি ক্যাশ অ্যাডভান্স"],
        popularity: 65,
      },
    ],
  },

  // ── Janata Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "janata-bank",
    cards: [
      {
        slug: "janata-visa-classic",
        name: "Janata Bank Visa Classic Credit Card",
        nameBn: "জনতা ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1000,
        feeWaiverCondition: "Waived for government staff & pensioners",
        feeWaiverConditionBn: "সরকারি কর্মকর্তা ও পেনশনভোগীদের ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#C2410C",
        features: ["Low 18% APR", "Nationwide 900+ branch support", "Flexible repayment"],
        featuresBn: ["১৮% কম বার্ষিক সুদ", "৯০০+ শাখায় সেবা", "সহজ পরিশোধ সুবিধা"],
        popularity: 59,
      },
      {
        slug: "janata-mastercard-gold",
        name: "Janata Bank Mastercard Gold Credit Card",
        nameBn: "জনতা ব্যাংক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#EA580C",
        features: ["1.5x points on retail", "Medical test discounts", "Dual-currency international support"],
        featuresBn: ["খুচরা ক্রয়ে ১.৫x পয়েন্ট", "মেডিকেল টেস্টে ছাড়", "দ্বৈত-মুদ্রা আন্তর্জাতিক সুবিধা"],
        popularity: 63,
      },
    ],
  },

  // ── Rupali Bank ───────────────────────────────────────────────────────────
  {
    bankSlug: "rupali-bank",
    cards: [
      {
        slug: "rupali-visa-classic",
        name: "Rupali Bank Visa Classic Credit Card",
        nameBn: "রূপালী ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1000,
        feeWaiverCondition: "Waived for public sector employees",
        feeWaiverConditionBn: "সরকারি খাতের কর্মীদের ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#831843",
        features: ["18% low rate", "Government backed", "Convenient ATM cash withdrawal"],
        featuresBn: ["১৮% কম সুদের হার", "রাষ্ট্রীয় নিরাপত্তা", "সহজ এটিএম উত্তোলন"],
        popularity: 55,
      },
      {
        slug: "rupali-visa-gold",
        name: "Rupali Bank Visa Gold Credit Card",
        nameBn: "রূপালী ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#9D174D",
        features: ["1.5x rewards", "Travel accident insurance", "Discounts at selected hotels"],
        featuresBn: ["১.৫x রিওয়ার্ড", "ভ্রমণ দুর্ঘটনা বীমা", "নির্বাচিত হোটেলে ডিসকাউন্ট"],
        popularity: 61,
      },
    ],
  },

  // ── Modhumoti Bank ────────────────────────────────────────────────────────
  {
    bankSlug: "modhumoti-bank",
    cards: [
      {
        slug: "modhumoti-visa-gold",
        name: "Modhumoti Bank Visa Gold Credit Card",
        nameBn: "মধুমতি ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1.5% cashback on retail transactions",
        rewardSummaryBn: "খুচরা কেনাকাটায় ১.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#0D9488",
        features: ["1.5% cashback", "Instant digital statements", "EMI at 400+ merchants"],
        featuresBn: ["১.৫% ক্যাশব্যাক", "তাৎক্ষণিক ডিজিটাল বিবরণী", "৪০০+ আউটলেটে ইএমআই"],
        popularity: 62,
      },
      {
        slug: "modhumoti-visa-platinum",
        name: "Modhumoti Bank Visa Platinum Credit Card",
        nameBn: "মধুমতি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,40,000",
        feeWaiverConditionBn: "বার্ষিক ২,৪০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2.5% cashback on dining & travel bookings",
        rewardSummaryBn: "ডাইনিং ও ভ্রমণে ২.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#0F766E",
        features: ["2.5% dining cashback", "Airport lounge access", "Hotel buffet B1G1 deals", "Travel insurance"],
        featuresBn: ["২.৫% খাবার ক্যাশব্যাক", "লাউঞ্জ সুবিধা", "হোটেল বুফে বি১জি১", "ভ্রমণ বীমা"],
        popularity: 69,
      },
    ],
  },

  // ── NRBC Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "nrbc-bank",
    cards: [
      {
        slug: "nrbc-visa-gold",
        name: "NRBC Bank Visa Gold Credit Card",
        nameBn: "এনআরবিসি ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Free for active NRBs; waived on ৳1,20,000 spend",
        feeWaiverConditionBn: "সক্রিয় প্রবাসীদের জন্য ফ্রি; বছরে ১,২০,০০০ টাকা ব্যয়ে মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "MILES",
        rewardSummary: "2 airline miles per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ এয়ারলাইন মাইলস",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#0369A1",
        features: ["2 Airline miles per ৳100", "Remittance fee waiver", "Zero mark-up on foreign spend"],
        featuresBn: ["প্রতি ১০০ টাকায় ২ এয়ার মাইলস", "রেমিট্যান্স ফি মওকুফ", "বৈদেশিক ব্যয়ে শূন্য মার্ক-আপ"],
        popularity: 67,
      },
      {
        slug: "nrbc-visa-platinum",
        name: "NRBC Bank Visa Platinum Credit Card",
        nameBn: "এনআরবিসি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Free for NRBs with $5,000 remittance/yr; waived on ৳2,40,000 spend",
        feeWaiverConditionBn: "বছরে $৫,০০০ রেমিট্যান্সে ফ্রি; বার্ষিক ২,৪০,০০০ টাকা ব্যয়ে মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA and regional lounges",
        loungeDetailsBn: "শাহজালাল বিমানবন্দরে বলাকা লাউঞ্জে এবং আঞ্চলিক লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "MILES",
        rewardSummary: "3 airline miles per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৩ এয়ারলাইন মাইলস",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#075985",
        features: ["3 Miles per ৳100", "Airport lounge access", "Airline ticket discounts", "Global travel protection"],
        featuresBn: ["৩ মাইলস প্রতি ১০০ টাকায়", "লাউঞ্জ সুবিধা", "বিমান টিকিটে ছাড়", "বৈশ্বিক ভ্রমণ বীমা"],
        popularity: 75,
      },
      {
        slug: "nrbc-mastercard-world",
        name: "NRBC Bank Mastercard World Credit Card",
        nameBn: "এনআরবিসি ব্যাংক মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 8000,
        feeWaiverCondition: "Free for priority NRB customers",
        feeWaiverConditionBn: "অগ্রাধিকার প্রবাসী গ্রাহকদের জন্য বিনামূল্যে",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 75000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited international airport lounge access via Mastercard LoungeKey",
        loungeDetailsBn: "মাস্টারকার্ড লাউঞ্জকি-এর মাধ্যমে বিশ্বব্যাপী আনলিমিটেড লাউঞ্জ প্রবেশ",
        rewardType: "MILES",
        rewardSummary: "4 airline miles per ৳100 spent locally and globally",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৪ এয়ারলাইন মাইলস",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        isShariah: false,
        cardColor: "#0F172A",
        features: ["Unlimited global lounge access", "4 Miles per ৳100", "24/7 World Concierge", "Luxury hotel upgrades"],
        featuresBn: ["সীমাহীন গ্লোবাল লাউঞ্জ", "৪ মাইলস প্রতি ১০০ টাকায়", "২৪/৭ কনসিয়ার্জ সেবা", "লাক্সারি হোটেল সুবিধা"],
        popularity: 82,
      },
    ],
  },

  // ── Bengal Commercial Bank ────────────────────────────────────────────────
  {
    bankSlug: "bengal-commercial-bank",
    cards: [
      {
        slug: "bengal-visa-classic",
        name: "Bengal Bank Visa Classic Credit Card",
        nameBn: "বেঙ্গল ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "First year free; 15 transactions for renewal waiver",
        feeWaiverConditionBn: "প্রথম বছর ফ্রি; ১৫ লেনদেনে পরবর্তী বছর মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1% flat cashback on all domestic retail spend",
        rewardSummaryBn: "সব দেশীয় খুচরা ক্রয়ে ১% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#312E81",
        features: ["1% flat cashback", "Instant digital issuance", "0% EMI on electronics"],
        featuresBn: ["১% ফ্ল্যাট ক্যাশব্যাক", "তাৎক্ষণিক ডিজিটাল ইস্যু", "০% কিস্তিতে গ্যাজেট ক্রয়"],
        popularity: 57,
      },
      {
        slug: "bengal-mastercard-platinum",
        name: "Bengal Bank Mastercard Platinum Credit Card",
        nameBn: "বেঙ্গল ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2.5% cashback on dining, hotels and travel",
        rewardSummaryBn: "খাবার, হোটেল ও ভ্রমণে ২.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#1E1B4B",
        features: ["2.5% premium cashback", "Airport lounge access", "B1G1 buffet dining", "Comprehensive travel cover"],
        featuresBn: ["২.৫% প্রিমিয়াম ক্যাশব্যাক", "লাউঞ্জ সুবিধা", "বি১জি১ বুফে ডাইনিং", "ভ্রমণ বীমা সুরক্ষা"],
        popularity: 66,
      },
    ],
  },

  // ── SBAC Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "south-bangla-bank",
    cards: [
      {
        slug: "sbac-visa-gold",
        name: "SBAC Bank Visa Gold Credit Card",
        nameBn: "এসবিএসি ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#166534",
        features: ["Agro-merchant discounts", "1.5x reward points", "0% EMI options"],
        featuresBn: ["কৃষি আউটলেটে ছাড়", "১.৫x পয়েন্ট", "০% কিস্তি সুবিধা"],
        popularity: 59,
      },
      {
        slug: "sbac-visa-platinum",
        name: "SBAC Bank Visa Platinum Credit Card",
        nameBn: "এসবিএসি ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#14532D",
        features: ["Airport lounge access", "2x reward points", "Hotel & dining deals", "Travel accident cover"],
        featuresBn: ["লাউঞ্জ সুবিধা", "২x রিওয়ার্ড পয়েন্ট", "হোটেল ও ডাইনিং অফার", "ভ্রমণ দুর্ঘটনা বীমা"],
        popularity: 65,
      },
    ],
  },

  // ── Global Islami Bank ────────────────────────────────────────────────────
  {
    bankSlug: "global-islami-bank",
    cards: [
      {
        slug: "gibl-visa-classic-islamic",
        name: "GIBL Islamic Visa Classic Credit Card",
        nameBn: "জিআইবিএল ইসলামিক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 Shariah compliant transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি হালাল লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#0E7490",
        features: ["100% Shariah compliant", "No interest or late penalty", "Halal spend perks"],
        featuresBn: ["১০০% শরিয়াহ সম্মত", "সুদ বা বিলম্ব জরিমানা নেই", "হালাল কেনাকাটায় সুবিধা"],
        popularity: 58,
      },
      {
        slug: "gibl-mastercard-gold-islamic",
        name: "GIBL Islamic Mastercard Gold Credit Card",
        nameBn: "জিআইবিএল ইসলামিক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#155E75",
        features: ["1.5x Halal rewards", "Umrah installment scheme", "Islamic Takaful cover", "Zakat payment integration"],
        featuresBn: ["১.৫x হালাল রিওয়ার্ড", "ওমরাহ কিস্তি ব্যবস্থা", "তাকাফুল বীমা", "যাকাত পেমেন্ট সুবিধা"],
        popularity: 66,
      },
      {
        slug: "gibl-visa-platinum-islamic",
        name: "GIBL Islamic Visa Platinum Credit Card",
        nameBn: "জিআইবিএল ইসলামিক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 6000,
        feeWaiverCondition: "Waived on annual spend of ৳2,40,000",
        feeWaiverConditionBn: "বার্ষিক ২,৪০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#164E63",
        features: ["Balaka Lounge access", "Halal 5-star dining B1G1", "Complimentary travel Takaful", "Global dual-currency acceptance"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "হালাল ৫-স্টার ডাইনিং বি১জি১", "বিনামূল্যে ভ্রমণ তাকাফুল", "বিশ্বব্যাপী দ্বৈত-মুদ্রা ব্যবহার"],
        popularity: 72,
      },
    ],
  },

  // ── ICB Islamic Bank ──────────────────────────────────────────────────────
  {
    bankSlug: "icb-islamic-bank",
    cards: [
      {
        slug: "icb-islamic-visa-classic",
        name: "ICB Islamic Bank Visa Classic Credit Card",
        nameBn: "আইসিবি ইসলামিক ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 12 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#166534",
        features: ["100% Shariah compliant", "Riba-free financing", "0% installment purchase"],
        featuresBn: ["১০০% শরিয়াহ সম্মত", "সুদহীন অর্থায়ন", "০% কিস্তিতে কেনাকাটা"],
        popularity: 52,
      },
      {
        slug: "icb-islamic-visa-gold",
        name: "ICB Islamic Bank Visa Gold Credit Card",
        nameBn: "আইসিবি ইসলামিক ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#14532D",
        features: ["1.5x Halal points", "Umrah travel installment", "Takaful insurance cover"],
        featuresBn: ["১.৫ গুণ হালাল পয়েন্ট", "ওমরাহ ভ্রমণ কিস্তি", "তাকাফুল বীমা সুবিধা"],
        popularity: 58,
      },
    ],
  },

  // ── Bangladesh Krishi Bank ────────────────────────────────────────────────
  {
    bankSlug: "bangladesh-krishi-bank",
    cards: [
      {
        slug: "bkb-visa-classic",
        name: "BKB Visa Classic Credit Card",
        nameBn: "বিকেবি ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 800,
        feeWaiverCondition: "Waived for registered farmers and agro-entrepreneurs",
        feeWaiverConditionBn: "নিবন্ধিত কৃষক ও কৃষি উদ্যোক্তাদের ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 12000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#3F6212",
        features: ["Low 18% interest rate", "Lowest income requirement in BD", "Accepted at 1000+ agro-dealers"],
        featuresBn: ["১৮% বিশেষ কম সুদের হার", "বাংলাদেশের সবচেয়ে কম আয়ের শর্ত", "১০০০+ কৃষি ডিলারে গ্রহণযোগ্য"],
        popularity: 55,
      },
      {
        slug: "bkb-visa-gold",
        name: "BKB Visa Gold Credit Card",
        nameBn: "বিকেবি ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2000,
        feeWaiverCondition: "Waived on annual spend of ৳80,000",
        feeWaiverConditionBn: "বার্ষিক ৮০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#365314",
        features: ["Agri-machinery 0% EMI", "Emergency overdraft facility", "Government security guarantee"],
        featuresBn: ["কৃষি যন্ত্রপাতি ০% কিস্তি", "জরুরি ওভারড্রাফট সুবিধা", "সরকারি নিরাপত্তা নিশ্চয়তা"],
        popularity: 61,
      },
    ],
  },

  // ── Padma Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "padma-bank",
    cards: [
      {
        slug: "padma-visa-gold",
        name: "Padma Bank Visa Gold Credit Card",
        nameBn: "পদ্মা ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#991B1B",
        features: ["1.5x reward points", "0% EMI at electronic stores", "Complimentary SMS banking"],
        featuresBn: ["১.৫x রিওয়ার্ড পয়েন্ট", "ইলেকট্রনিক্সে ০% কিস্তি", "বিনামূল্যে এসএমএস ব্যাংকিং"],
        popularity: 54,
      },
      {
        slug: "padma-mastercard-platinum",
        name: "Padma Bank Mastercard Platinum Credit Card",
        nameBn: "পদ্মা ব্যাংক মাস্টারকার্ড প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 40000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#7F1D1D",
        features: ["Airport lounge access", "2x reward points", "Hotel discounts", "Dining privileges"],
        featuresBn: ["লাউঞ্জ সুবিধা", "২x রিওয়ার্ড", "হোটেল ডিসকাউন্ট", "ডাইনিং বিশেষ সুবিধা"],
        popularity: 62,
      },
    ],
  },

  // ── Union Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "union-bank",
    cards: [
      {
        slug: "union-visa-classic-islamic",
        name: "Union Bank Islamic Visa Classic Credit Card",
        nameBn: "ইউনিয়ন ব্যাংক ইসলামিক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 15 retail transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#15803D",
        features: ["100% Shariah compliant", "Riba-free financing", "Convenient digital app"],
        featuresBn: ["১০০% শরিয়াহ সম্মত", "সুদহীন অর্থায়ন", "সুবিধাজনক ডিজিটাল অ্যাপ"],
        popularity: 53,
      },
      {
        slug: "union-mastercard-gold-islamic",
        name: "Union Bank Islamic Mastercard Gold Credit Card",
        nameBn: "ইউনিয়ন ব্যাংক ইসলামিক মাস্টারকার্ড গোল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "GOLD",
        annualFee: 3000,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#166534",
        features: ["1.5x Halal points", "Umrah package EMI", "Zakat computation", "Islamic Takaful"],
        featuresBn: ["১.৫x হালাল পয়েন্ট", "ওমরাহ প্যাকেজ কিস্তি", "যাকাত হিসাব", "ইসলামিক তাকাফুল সুরক্ষা"],
        popularity: 59,
      },
    ],
  },
];
