import type { AdditionalBankSeed } from "./extendedBanks";

/**
 * New Bangladesh banks — v3
 * Adds 18 more scheduled commercial banks covering all major missing institutions
 */
export const NEW_BANKS: AdditionalBankSeed[] = [
  // ── National Bank ──────────────────────────────────────────────────────────
  {
    slug: "national-bank",
    name: "National Bank PLC",
    nameBn: "ন্যাশনাল ব্যাংক পিএলসি",
    shortName: "National Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1983,
    headquarters: "18 Dilkusha C/A, Dhaka",
    branchCount: 220,
    atmCount: 180,
    website: "https://www.nblbd.com",
    swiftCode: "NATBBDDH",
    brandColor: "#0D47A1",
    logoInitials: "NB",
    rating: 3.5,
    reviewCount: 1850,
    mobileAppName: "NBL Mobile Banking",
    description:
      "National Bank Limited is one of the first private sector banks in Bangladesh, offering a full range of commercial banking services with a focus on trade finance.",
    descriptionBn:
      "ন্যাশনাল ব্যাংক লিমিটেড বাংলাদেশের প্রথম বেসরকারি ব্যাংকগুলোর একটি, বাণিজ্যিক ব্যাংকিং সেবার পূর্ণ পরিসরসহ বিশেষত ট্রেড ফাইন্যান্সে।",
    savings: [
      {
        slug: "nbl-savings-account",
        name: "NBL Savings Account",
        nameBn: "এনবিএল সঞ্চয়ী হিসাব",
        interestRate: 3.75,
        minOpeningBalance: 1000,
        maintenanceFee: 300,
        debitCardAnnualFee: 400,
        features: ["Free internet banking", "SMS alerts", "Nationwide branches"],
        featuresBn: ["ফ্রি ইন্টারনেট ব্যাংকিং", "এসএমএস অ্যালার্ট", "সারাদেশে শাখা"],
        popularity: 62,
      },
      {
        slug: "nbl-special-savings",
        name: "NBL Special Savings Account",
        nameBn: "এনবিএল বিশেষ সঞ্চয়ী হিসাব",
        interestRate: 4.5,
        interestRateMax: 5.0,
        minOpeningBalance: 10000,
        maintenanceFee: 0,
        debitCardAnnualFee: 400,
        features: ["Higher interest rate", "Free chequebook", "Priority service"],
        featuresBn: ["উচ্চতর সুদের হার", "ফ্রি চেকবই", "অগ্রাধিকার সেবা"],
        popularity: 65,
      },
    ],
    fdr: [
      {
        slug: "nbl-fixed-deposit",
        name: "NBL Fixed Deposit",
        nameBn: "এনবিএল ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Loan facility up to 90% of FDR", "Auto renewal", "Flexible tenures"],
        featuresBn: ["FDR-এর ৯০% পর্যন্ত লোন সুবিধা", "স্বয়ংক্রিয় নবায়ন", "নমনীয় মেয়াদ"],
        rates: [[3,5.5],[6,6.5],[12,7.25],[24,7.0],[36,6.75]],
      },
    ],
  },

  // ── NCC Bank ──────────────────────────────────────────────────────────────
  {
    slug: "ncc-bank",
    name: "NCC Bank PLC",
    nameBn: "এনসিসি ব্যাংক পিএলসি",
    shortName: "NCC Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1993,
    headquarters: "13/1 Toyenbee Circular Road, Dhaka",
    branchCount: 135,
    atmCount: 100,
    website: "https://www.nccbank.com.bd",
    swiftCode: "NCCLBDDH",
    brandColor: "#1565C0",
    logoInitials: "NCC",
    rating: 3.6,
    reviewCount: 1100,
    mobileAppName: "NCC Mobile Banking",
    description:
      "NCC Bank offers comprehensive banking services with a strong focus on SME lending and retail banking across Bangladesh.",
    descriptionBn:
      "এনসিসি ব্যাংক বাংলাদেশে এসএমই ঋণ ও খুচরা ব্যাংকিংয়ে দৃঢ় মনোযোগ দিয়ে ব্যাপক ব্যাংকিং সেবা প্রদান করে।",
    savings: [
      {
        slug: "ncc-savings-account",
        name: "NCC Bank Savings Account",
        nameBn: "এনসিসি ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 3.5,
        minOpeningBalance: 1000,
        maintenanceFee: 300,
        debitCardAnnualFee: 345,
        features: ["Mobile banking", "ATM access", "Debit card"],
        featuresBn: ["মোবাইল ব্যাংকিং", "এটিএম সুবিধা", "ডেবিট কার্ড"],
        popularity: 58,
      },
    ],
    fdr: [
      {
        slug: "ncc-fixed-deposit",
        name: "NCC Bank Fixed Deposit",
        nameBn: "এনসিসি ব্যাংক ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Up to 90% loan against FDR", "Automatic renewal", "Multiple tenures"],
        featuresBn: ["FDR-এর বিপরীতে ৯০% পর্যন্ত ঋণ", "স্বয়ংক্রিয় নবায়ন", "বিভিন্ন মেয়াদ"],
        rates: [[3,5.5],[6,6.25],[12,7.0],[24,6.75],[36,6.5]],
      },
    ],
  },

  // ── ONE Bank ──────────────────────────────────────────────────────────────
  {
    slug: "one-bank",
    name: "ONE Bank PLC",
    nameBn: "ওয়ান ব্যাংক পিএলসি",
    shortName: "ONE Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 1999,
    headquarters: "167 Dilkusha C/A, Dhaka",
    branchCount: 110,
    atmCount: 90,
    website: "https://www.onebankbd.com",
    swiftCode: "ONEBBDDH",
    brandColor: "#2196F3",
    logoInitials: "ONE",
    rating: 3.7,
    reviewCount: 950,
    mobileAppName: "ONE Mobile Banking",
    description:
      "ONE Bank provides modern banking solutions with digital-first services and a growing network of branches across Bangladesh.",
    descriptionBn:
      "ওয়ান ব্যাংক ডিজিটাল-ফার্স্ট সেবা ও সারাদেশে শাখার ক্রমবর্ধমান নেটওয়ার্ক নিয়ে আধুনিক ব্যাংকিং সমাধান প্রদান করে।",
    savings: [
      {
        slug: "one-bank-savings-account",
        name: "ONE Bank Savings Account",
        nameBn: "ওয়ান ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        debitCardAnnualFee: 345,
        onlineAccountOpening: true,
        features: ["Digital account opening", "Contactless debit card", "Mobile banking"],
        featuresBn: ["ডিজিটাল অ্যাকাউন্ট খোলা", "কন্ট্যাক্টলেস ডেবিট কার্ড", "মোবাইল ব্যাংকিং"],
        popularity: 64,
      },
    ],
    fdr: [
      {
        slug: "one-bank-fdr",
        name: "ONE Bank Fixed Deposit",
        nameBn: "ওয়ান ব্যাংক ফিক্সড ডিপোজিট",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["90% loan against FDR", "Auto renewal", "Online management"],
        featuresBn: ["FDR-এর বিপরীতে ৯০% লোন", "স্বয়ংক্রিয় নবায়ন", "অনলাইন ব্যবস্থাপনা"],
        rates: [[3,5.75],[6,6.5],[12,7.25],[24,7.0],[36,6.75]],
      },
    ],
  },

  // ── First Security Islami Bank ──────────────────────────────────────────
  {
    slug: "first-security-islami-bank",
    name: "First Security Islami Bank PLC",
    nameBn: "ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক পিএলসি",
    shortName: "FSIBL",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 1999,
    headquarters: "23 Dilkusha C/A, Dhaka",
    branchCount: 205,
    atmCount: 140,
    website: "https://www.fsiblbd.com",
    swiftCode: "FSEBBDDH",
    brandColor: "#1B5E20",
    logoInitials: "FSIB",
    rating: 3.6,
    reviewCount: 1350,
    mobileAppName: "FSIBL Mobile Banking",
    description:
      "First Security Islami Bank operates on Shariah principles, offering comprehensive Islamic banking products including Mudaraba savings and Musharaka financing.",
    descriptionBn:
      "ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক শরিয়াহ নীতিতে পরিচালিত হয়, মুদারাবা সঞ্চয় ও মুশারাকা ফাইন্যান্সিংসহ ব্যাপক ইসলামী ব্যাংকিং পণ্য প্রদান করে।",
    savings: [
      {
        slug: "fsibl-mudaraba-savings",
        name: "FSIBL Mudaraba Savings Account",
        nameBn: "এফএসআইবিএল মুদারাবা সঞ্চয়ী হিসাব",
        interestRate: 3.5,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        debitCardAnnualFee: 345,
        isShariah: true,
        features: ["Shariah compliant", "Profit sharing", "Free debit card"],
        featuresBn: ["শরিয়াহ সম্মত", "মুনাফা বণ্টন", "ফ্রি ডেবিট কার্ড"],
        popularity: 63,
      },
    ],
    fdr: [
      {
        slug: "fsibl-mudaraba-term-deposit",
        name: "FSIBL Mudaraba Term Deposit",
        nameBn: "এফএসআইবিএল মুদারাবা মেয়াদি আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Halal profit", "Auto renewal", "Flexible periods"],
        featuresBn: ["হালাল মুনাফা", "স্বয়ংক্রিয় নবায়ন", "নমনীয় মেয়াদ"],
        rates: [[3,5.0],[6,5.75],[12,6.5],[24,6.25],[36,6.0]],
      },
    ],
  },

  // ── Union Bank ────────────────────────────────────────────────────────────
  {
    slug: "union-bank",
    name: "Union Bank PLC",
    nameBn: "ইউনিয়ন ব্যাংক পিএলসি",
    shortName: "Union Bank",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 2013,
    headquarters: "58 Dilkusha C/A, Dhaka",
    branchCount: 70,
    atmCount: 50,
    website: "https://www.unionbank.com.bd",
    swiftCode: "UNBLBDDH",
    brandColor: "#4CAF50",
    logoInitials: "UB",
    rating: 3.4,
    reviewCount: 620,
    mobileAppName: "Union Mobile Banking",
    description:
      "Union Bank is a Shariah-based commercial bank offering Islamic banking products with a customer-centric approach.",
    descriptionBn:
      "ইউনিয়ন ব্যাংক একটি শরিয়াহ-ভিত্তিক বাণিজ্যিক ব্যাংক যা গ্রাহককেন্দ্রিক পদ্ধতিতে ইসলামী ব্যাংকিং পণ্য প্রদান করে।",
    savings: [
      {
        slug: "union-mudaraba-savings",
        name: "Union Bank Mudaraba Savings",
        nameBn: "ইউনিয়ন ব্যাংক মুদারাবা সঞ্চয়",
        interestRate: 3.25,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        isShariah: true,
        features: ["Shariah compliant", "Mobile banking", "ATM access"],
        featuresBn: ["শরিয়াহ সম্মত", "মোবাইল ব্যাংকিং", "এটিএম সুবিধা"],
        popularity: 52,
      },
    ],
    fdr: [
      {
        slug: "union-mudaraba-term",
        name: "Union Bank Mudaraba Term Deposit",
        nameBn: "ইউনিয়ন ব্যাংক মুদারাবা মেয়াদি আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Halal profit", "Various tenures", "Loan against deposit"],
        featuresBn: ["হালাল মুনাফা", "বিভিন্ন মেয়াদ", "আমানতের বিপরীতে ঋণ"],
        rates: [[3,4.75],[6,5.5],[12,6.25],[24,6.0]],
      },
    ],
  },

  // ── Global Islami Bank ────────────────────────────────────────────────────
  {
    slug: "global-islami-bank",
    name: "Global Islami Bank PLC",
    nameBn: "গ্লোবাল ইসলামী ব্যাংক পিএলসি",
    shortName: "GIBL",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 2013,
    headquarters: "Uday Tower, 57 Gulshan Ave, Dhaka",
    branchCount: 80,
    atmCount: 55,
    website: "https://www.gibl.com.bd",
    swiftCode: "GIBLBDDH",
    brandColor: "#006064",
    logoInitials: "GIB",
    rating: 3.5,
    reviewCount: 710,
    mobileAppName: "GIBL Mobile App",
    description:
      "Global Islami Bank offers modern Islamic banking solutions with a focus on digital services and corporate banking.",
    descriptionBn:
      "গ্লোবাল ইসলামী ব্যাংক ডিজিটাল সেবা ও কর্পোরেট ব্যাংকিংয়ে মনোযোগ দিয়ে আধুনিক ইসলামী ব্যাংকিং সমাধান প্রদান করে।",
    savings: [
      {
        slug: "gibl-mudaraba-savings",
        name: "GIBL Mudaraba Savings Account",
        nameBn: "জিআইবিএল মুদারাবা সঞ্চয়ী হিসাব",
        interestRate: 3.5,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        isShariah: true,
        onlineAccountOpening: true,
        features: ["Digital account opening", "Shariah compliant", "Mobile banking"],
        featuresBn: ["ডিজিটাল অ্যাকাউন্ট খোলা", "শরিয়াহ সম্মত", "মোবাইল ব্যাংকিং"],
        popularity: 55,
      },
    ],
    fdr: [
      {
        slug: "gibl-mudaraba-term",
        name: "GIBL Mudaraba Term Deposit",
        nameBn: "জিআইবিএল মুদারাবা মেয়াদি আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Halal profit sharing", "Auto renewal", "Flexible tenure"],
        featuresBn: ["হালাল মুনাফা বণ্টন", "স্বয়ংক্রিয় নবায়ন", "নমনীয় মেয়াদ"],
        rates: [[3,5.0],[6,5.75],[12,6.5],[24,6.25],[36,6.0]],
      },
    ],
  },

  // ── Agrani Bank ──────────────────────────────────────────────────────────
  {
    slug: "agrani-bank",
    name: "Agrani Bank PLC",
    nameBn: "অগ্রণী ব্যাংক পিএলসি",
    shortName: "Agrani Bank",
    category: "STATE_OWNED",
    isShariah: false,
    establishedYear: 1972,
    headquarters: "9/DIT Avenue, Motijheel, Dhaka",
    branchCount: 970,
    atmCount: 400,
    website: "https://www.agranibank.org",
    swiftCode: "AGBKBDDH",
    brandColor: "#BF360C",
    logoInitials: "AB",
    rating: 3.3,
    reviewCount: 2100,
    mobileAppName: "Agrani Bank Mobile",
    description:
      "Agrani Bank is a state-owned commercial bank with one of the largest branch networks in Bangladesh, serving millions of customers including government employees and rural communities.",
    descriptionBn:
      "অগ্রণী ব্যাংক বাংলাদেশের বৃহত্তম শাখা নেটওয়ার্কগুলোর একটি রাষ্ট্রায়ত্ত বাণিজ্যিক ব্যাংক, সরকারি কর্মচারী ও গ্রামীণ জনগোষ্ঠীসহ লক্ষ লক্ষ গ্রাহককে সেবা দেয়।",
    savings: [
      {
        slug: "agrani-savings-account",
        name: "Agrani Bank Savings Account",
        nameBn: "অগ্রণী ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        debitCardAnnualFee: 300,
        features: ["Government salary disbursement", "Pension payments", "Nationwide branches"],
        featuresBn: ["সরকারি বেতন প্রদান", "পেনশন প্রদান", "সারাদেশে শাখা"],
        popularity: 65,
      },
      {
        slug: "agrani-school-savings",
        name: "Agrani Bank School Savings Account",
        nameBn: "অগ্রণী ব্যাংক স্কুল সঞ্চয়ী হিসাব",
        interestRate: 5.0,
        minOpeningBalance: 100,
        maintenanceFee: 0,
        segment: "STUDENT",
        features: ["Zero maintenance fee", "Higher interest for students", "Financial literacy"],
        featuresBn: ["শূন্য রক্ষণাবেক্ষণ ফি", "শিক্ষার্থীদের জন্য উচ্চতর সুদ", "আর্থিক সাক্ষরতা"],
        popularity: 60,
      },
    ],
    fdr: [
      {
        slug: "agrani-fixed-deposit",
        name: "Agrani Bank Fixed Deposit",
        nameBn: "অগ্রণী ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 80,
        features: ["Government backed", "80% loan against FDR", "Senior citizen bonus rate"],
        featuresBn: ["সরকার সমর্থিত", "FDR-এর বিপরীতে ৮০% ঋণ", "প্রবীণ নাগরিকের বোনাস হার"],
        rates: [[3,5.5],[6,6.25],[12,7.0],[24,6.75],[36,6.5]],
      },
    ],
  },

  // ── Janata Bank ──────────────────────────────────────────────────────────
  {
    slug: "janata-bank",
    name: "Janata Bank PLC",
    nameBn: "জনতা ব্যাংক পিএলসি",
    shortName: "Janata Bank",
    category: "STATE_OWNED",
    isShariah: false,
    establishedYear: 1972,
    headquarters: "110 Motijheel C/A, Dhaka",
    branchCount: 910,
    atmCount: 350,
    website: "https://www.janatabank-bd.com",
    swiftCode: "JANBBDDH",
    brandColor: "#E65100",
    logoInitials: "JB",
    rating: 3.2,
    reviewCount: 1980,
    mobileAppName: "Janata Bank Mobile",
    description:
      "Janata Bank is one of the largest state-owned banks in Bangladesh, with an extensive branch network serving individuals, businesses, and the public sector.",
    descriptionBn:
      "জনতা ব্যাংক বাংলাদেশের বৃহত্তম রাষ্ট্রায়ত্ত ব্যাংকগুলোর একটি, ব্যক্তি, ব্যবসায়ী ও সরকারি খাতকে সেবা দেওয়ার জন্য বিস্তৃত শাখা নেটওয়ার্ক রয়েছে।",
    savings: [
      {
        slug: "janata-savings-account",
        name: "Janata Bank Savings Account",
        nameBn: "জনতা ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        debitCardAnnualFee: 300,
        features: ["Pension disbursements", "Wide ATM network", "Remittance services"],
        featuresBn: ["পেনশন প্রদান", "বিস্তৃত এটিএম নেটওয়ার্ক", "রেমিট্যান্স সেবা"],
        popularity: 63,
      },
    ],
    fdr: [
      {
        slug: "janata-fixed-deposit",
        name: "Janata Bank Fixed Deposit",
        nameBn: "জনতা ব্যাংক মেয়াদি আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 80,
        features: ["Government guaranteed", "Pensioner preferred rate", "Loan against FDR"],
        featuresBn: ["সরকার নিশ্চিত", "পেনশনারদের অগ্রাধিকার হার", "FDR-এর বিপরীতে ঋণ"],
        rates: [[3,5.5],[6,6.0],[12,6.75],[24,6.5],[36,6.25]],
      },
    ],
  },

  // ── Rupali Bank ──────────────────────────────────────────────────────────
  {
    slug: "rupali-bank",
    name: "Rupali Bank PLC",
    nameBn: "রূপালী ব্যাংক পিএলসি",
    shortName: "Rupali Bank",
    category: "STATE_OWNED",
    isShariah: false,
    establishedYear: 1972,
    headquarters: "34 Dilkusha C/A, Dhaka",
    branchCount: 583,
    atmCount: 180,
    website: "https://www.rupalibank.com.bd",
    swiftCode: "RUPBBDDH",
    brandColor: "#880E4F",
    logoInitials: "RB",
    rating: 3.3,
    reviewCount: 1450,
    mobileAppName: "Rupali Bank Mobile",
    description:
      "Rupali Bank is a state-owned commercial bank providing banking services to individuals, SMEs, and corporates across Bangladesh with strong government linkages.",
    descriptionBn:
      "রূপালী ব্যাংক একটি রাষ্ট্রায়ত্ত বাণিজ্যিক ব্যাংক যা বাংলাদেশে ব্যক্তি, এসএমই ও কর্পোরেট প্রতিষ্ঠানকে শক্তিশালী সরকারি সংযোগের মাধ্যমে ব্যাংকিং সেবা প্রদান করে।",
    savings: [
      {
        slug: "rupali-savings-account",
        name: "Rupali Bank Savings Account",
        nameBn: "রূপালী ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        debitCardAnnualFee: 300,
        features: ["Remittance services", "Government salary", "National savings certificates"],
        featuresBn: ["রেমিট্যান্স সেবা", "সরকারি বেতন", "জাতীয় সঞ্চয়পত্র"],
        popularity: 60,
      },
    ],
    fdr: [
      {
        slug: "rupali-fixed-deposit",
        name: "Rupali Bank Fixed Deposit",
        nameBn: "রূপালী ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 80,
        features: ["State-owned security", "Competitive rates", "Auto renewal"],
        featuresBn: ["রাষ্ট্রায়ত্ত নিরাপত্তা", "প্রতিযোগিতামূলক হার", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3,5.5],[6,6.0],[12,7.0],[24,6.75],[36,6.5]],
      },
    ],
  },

  // ── Modhumoti Bank ────────────────────────────────────────────────────────
  {
    slug: "modhumoti-bank",
    name: "Modhumoti Bank PLC",
    nameBn: "মধুমতি ব্যাংক পিএলসি",
    shortName: "Modhumoti",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2013,
    headquarters: "Madhumoti Tower, 8 Rajuk Avenue, Dhaka",
    branchCount: 75,
    atmCount: 50,
    website: "https://www.modhumotibank.com",
    swiftCode: "MMBLBDDH",
    brandColor: "#00796B",
    logoInitials: "MMB",
    rating: 3.6,
    reviewCount: 680,
    mobileAppName: "Modhumoti Mobile Banking",
    description:
      "Modhumoti Bank is a new-generation private bank focused on digital innovation, SME financing, and quality retail banking services.",
    descriptionBn:
      "মধুমতি ব্যাংক একটি নতুন প্রজন্মের বেসরকারি ব্যাংক যা ডিজিটাল উদ্ভাবন, এসএমই অর্থায়ন ও মানসম্পন্ন খুচরা ব্যাংকিং সেবায় মনোযোগী।",
    savings: [
      {
        slug: "modhumoti-savings",
        name: "Modhumoti Savings Account",
        nameBn: "মধুমতি সঞ্চয়ী হিসাব",
        interestRate: 4.25,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        onlineAccountOpening: true,
        features: ["Digital account opening", "Contactless card", "Mobile banking"],
        featuresBn: ["ডিজিটাল অ্যাকাউন্ট খোলা", "কন্ট্যাক্টলেস কার্ড", "মোবাইল ব্যাংকিং"],
        popularity: 60,
      },
    ],
    fdr: [
      {
        slug: "modhumoti-fdr",
        name: "Modhumoti Fixed Deposit",
        nameBn: "মধুমতি স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Higher interest rates", "Online FDR", "90% loan facility"],
        featuresBn: ["উচ্চতর সুদের হার", "অনলাইন এফডিআর", "৯০% ঋণ সুবিধা"],
        rates: [[3,5.75],[6,6.5],[12,7.5],[24,7.25],[36,7.0]],
      },
    ],
  },

  // ── South Bangla Agriculture & Commerce Bank ───────────────────────────
  {
    slug: "south-bangla-bank",
    name: "South Bangla Agriculture & Commerce Bank PLC",
    nameBn: "সাউথ বাংলা এগ্রিকালচার এন্ড কমার্স ব্যাংক পিএলসি",
    shortName: "SBAC Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2013,
    headquarters: "47 Dilkusha C/A, Dhaka",
    branchCount: 100,
    atmCount: 70,
    website: "https://www.sbacbank.com",
    swiftCode: "SBACBDDH",
    brandColor: "#33691E",
    logoInitials: "SBAC",
    rating: 3.5,
    reviewCount: 560,
    mobileAppName: "SBAC Mobile Banking",
    description:
      "South Bangla Agriculture & Commerce Bank specializes in agricultural financing and rural banking, serving farmers and agro-entrepreneurs across Bangladesh.",
    descriptionBn:
      "সাউথ বাংলা এগ্রিকালচার এন্ড কমার্স ব্যাংক কৃষি অর্থায়ন ও গ্রামীণ ব্যাংকিংয়ে বিশেষজ্ঞ, বাংলাদেশে কৃষক ও কৃষি-উদ্যোক্তাদের সেবা দেয়।",
    savings: [
      {
        slug: "sbac-savings",
        name: "SBAC Bank Savings Account",
        nameBn: "এসবিএসি ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        features: ["Agriculture focus", "Rural banking", "Mobile banking"],
        featuresBn: ["কৃষি কেন্দ্রিক", "গ্রামীণ ব্যাংকিং", "মোবাইল ব্যাংকিং"],
        popularity: 55,
      },
    ],
    fdr: [
      {
        slug: "sbac-fdr",
        name: "SBAC Bank Fixed Deposit",
        nameBn: "এসবিএসি ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Agriculture-linked rates", "Flexible tenure", "Loan against FDR"],
        featuresBn: ["কৃষি-সংযুক্ত হার", "নমনীয় মেয়াদ", "FDR-এর বিপরীতে ঋণ"],
        rates: [[3,5.5],[6,6.25],[12,7.25],[24,7.0]],
      },
    ],
  },

  // ── Bengal Commercial Bank ────────────────────────────────────────────────
  {
    slug: "bengal-commercial-bank",
    name: "Bengal Commercial Bank PLC",
    nameBn: "বেঙ্গল কমার্শিয়াল ব্যাংক পিএলসি",
    shortName: "Bengal Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2020,
    headquarters: "26 Motijheel C/A, Dhaka",
    branchCount: 50,
    atmCount: 30,
    website: "https://www.bengalbank.com.bd",
    swiftCode: "BNGBBDDH",
    brandColor: "#1A237E",
    logoInitials: "BCB",
    rating: 3.5,
    reviewCount: 320,
    mobileAppName: "Bengal Bank Mobile",
    description:
      "Bengal Commercial Bank is a new generation bank providing modern banking solutions with digital-first services and competitive rates.",
    descriptionBn:
      "বেঙ্গল কমার্শিয়াল ব্যাংক একটি নতুন প্রজন্মের ব্যাংক যা ডিজিটাল-ফার্স্ট সেবা ও প্রতিযোগিতামূলক হার নিয়ে আধুনিক ব্যাংকিং সমাধান প্রদান করে।",
    savings: [
      {
        slug: "bengal-savings",
        name: "Bengal Bank Savings Account",
        nameBn: "বেঙ্গল ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.5,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        onlineAccountOpening: true,
        features: ["New generation bank", "Digital first", "Competitive rates"],
        featuresBn: ["নতুন প্রজন্মের ব্যাংক", "ডিজিটাল ফার্স্ট", "প্রতিযোগিতামূলক হার"],
        popularity: 52,
      },
    ],
    fdr: [
      {
        slug: "bengal-fdr",
        name: "Bengal Bank Fixed Deposit",
        nameBn: "বেঙ্গল ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Attractive rates", "Online management", "Auto renewal"],
        featuresBn: ["আকর্ষণীয় হার", "অনলাইন ব্যবস্থাপনা", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3,5.75],[6,6.5],[12,7.5],[24,7.25]],
      },
    ],
  },

  // ── Padma Bank ────────────────────────────────────────────────────────────
  {
    slug: "padma-bank",
    name: "Padma Bank PLC",
    nameBn: "পদ্মা ব্যাংক পিএলসি",
    shortName: "Padma Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2015,
    headquarters: "2nd Floor, Selinabad Tower, Dhaka",
    branchCount: 80,
    atmCount: 60,
    website: "https://www.padmabank.com",
    swiftCode: "PDMBBDDH",
    brandColor: "#B71C1C",
    logoInitials: "PDB",
    rating: 3.3,
    reviewCount: 490,
    mobileAppName: "Padma Bank Mobile",
    description:
      "Padma Bank provides retail and corporate banking services with a focus on inclusive banking and digital transformation.",
    descriptionBn:
      "পদ্মা ব্যাংক অন্তর্ভুক্তিমূলক ব্যাংকিং ও ডিজিটাল রূপান্তরে মনোযোগ দিয়ে খুচরা ও কর্পোরেট ব্যাংকিং সেবা প্রদান করে।",
    savings: [
      {
        slug: "padma-savings",
        name: "Padma Bank Savings Account",
        nameBn: "পদ্মা ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 3.75,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        features: ["Mobile banking", "ATM access", "Debit card"],
        featuresBn: ["মোবাইল ব্যাংকিং", "এটিএম সুবিধা", "ডেবিট কার্ড"],
        popularity: 50,
      },
    ],
    fdr: [
      {
        slug: "padma-fdr",
        name: "Padma Bank Fixed Deposit",
        nameBn: "পদ্মা ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Competitive rates", "Auto renewal", "Loan against FDR"],
        featuresBn: ["প্রতিযোগিতামূলক হার", "স্বয়ংক্রিয় নবায়ন", "FDR-এর বিপরীতে ঋণ"],
        rates: [[3,5.5],[6,6.25],[12,7.0],[24,6.75]],
      },
    ],
  },

  // ── NRBC Bank ─────────────────────────────────────────────────────────────
  {
    slug: "nrbc-bank",
    name: "NRBC Bank PLC",
    nameBn: "এনআরবিসি ব্যাংক পিএলসি",
    shortName: "NRBC Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2013,
    headquarters: "73 Mohakhali C/A, Dhaka",
    branchCount: 85,
    atmCount: 60,
    website: "https://www.nrbcbank.com",
    swiftCode: "NRBCBDDH",
    brandColor: "#0288D1",
    logoInitials: "NRBC",
    rating: 3.7,
    reviewCount: 730,
    mobileAppName: "NRBC Mobile Banking",
    description:
      "NRBC Bank, originally established for Non-Resident Bangladeshis, now serves all segments offering competitive deposit and lending products.",
    descriptionBn:
      "এনআরবিসি ব্যাংক মূলত প্রবাসী বাংলাদেশিদের জন্য প্রতিষ্ঠিত হলেও এখন প্রতিযোগিতামূলক আমানত ও ঋণ পণ্য নিয়ে সব শ্রেণির গ্রাহকদের সেবা দেয়।",
    savings: [
      {
        slug: "nrbc-savings",
        name: "NRBC Bank Savings Account",
        nameBn: "এনআরবিসি ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.25,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        features: ["NRB remittance", "Mobile banking", "Digital services"],
        featuresBn: ["প্রবাসী রেমিট্যান্স", "মোবাইল ব্যাংকিং", "ডিজিটাল সেবা"],
        popularity: 63,
      },
      {
        slug: "nrbc-nrb-savings",
        name: "NRBC NRB Savings Account",
        nameBn: "এনআরবিসি প্রবাসী সঞ্চয়ী হিসাব",
        interestRate: 5.0,
        minOpeningBalance: 0,
        maintenanceFee: 0,
        segment: "NRB",
        features: ["Zero minimum balance", "Free remittance", "Higher interest for NRBs"],
        featuresBn: ["শূন্য ন্যূনতম ব্যালেন্স", "ফ্রি রেমিট্যান্স", "প্রবাসীদের জন্য উচ্চতর সুদ"],
        popularity: 70,
      },
    ],
    fdr: [
      {
        slug: "nrbc-fdr",
        name: "NRBC Bank Fixed Deposit",
        nameBn: "এনআরবিসি ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["NRB preferred rates", "Auto renewal", "Online FDR"],
        featuresBn: ["প্রবাসীদের অগ্রাধিকার হার", "স্বয়ংক্রিয় নবায়ন", "অনলাইন FDR"],
        rates: [[3,5.75],[6,6.5],[12,7.5],[24,7.25],[36,7.0]],
      },
    ],
  },

  // ── Shimanto Bank ─────────────────────────────────────────────────────────
  {
    slug: "shimanto-bank",
    name: "Shimanto Bank PLC",
    nameBn: "শিমান্তো ব্যাংক পিএলসি",
    shortName: "Shimanto Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2016,
    headquarters: "Dhaka",
    branchCount: 50,
    atmCount: 30,
    website: "https://www.shimantobank.com",
    swiftCode: "SHBLBDDH",
    brandColor: "#37474F",
    logoInitials: "SHB",
    rating: 3.4,
    reviewCount: 280,
    mobileAppName: "Shimanto Mobile Banking",
    description:
      "Shimanto Bank is a border-trade focused bank serving traders and businesses in border districts of Bangladesh.",
    descriptionBn:
      "শিমান্তো ব্যাংক সীমান্ত-বাণিজ্যে মনোযোগী একটি ব্যাংক, বাংলাদেশের সীমান্তবর্তী জেলাগুলোর ব্যবসায়ী ও উদ্যোক্তাদের সেবা দেয়।",
    savings: [
      {
        slug: "shimanto-savings",
        name: "Shimanto Bank Savings Account",
        nameBn: "শিমান্তো ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        features: ["Border trade support", "Mobile banking", "ATM access"],
        featuresBn: ["সীমান্ত বাণিজ্য সহায়তা", "মোবাইল ব্যাংকিং", "এটিএম সুবিধা"],
        popularity: 48,
      },
    ],
    fdr: [
      {
        slug: "shimanto-fdr",
        name: "Shimanto Bank Fixed Deposit",
        nameBn: "শিমান্তো ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["Competitive rates", "Auto renewal", "Flexible tenures"],
        featuresBn: ["প্রতিযোগিতামূলক হার", "স্বয়ংক্রিয় নবায়ন", "নমনীয় মেয়াদ"],
        rates: [[3,5.5],[6,6.25],[12,7.0],[24,6.75]],
      },
    ],
  },

  // ── Citizens Bank ─────────────────────────────────────────────────────────
  {
    slug: "citizens-bank",
    name: "Citizens Bank PLC",
    nameBn: "সিটিজেন্স ব্যাংক পিএলসি",
    shortName: "Citizens Bank",
    category: "PRIVATE",
    isShariah: false,
    establishedYear: 2022,
    headquarters: "Dhaka",
    branchCount: 30,
    atmCount: 20,
    website: "https://www.citizensbank.com.bd",
    swiftCode: "CTZNBDDH",
    brandColor: "#4527A0",
    logoInitials: "CB",
    rating: 3.5,
    reviewCount: 180,
    mobileAppName: "Citizens Bank Mobile",
    description:
      "Citizens Bank is a new-generation bank focused on delivering smart digital banking solutions to retail and business customers.",
    descriptionBn:
      "সিটিজেন্স ব্যাংক একটি নতুন প্রজন্মের ব্যাংক যা খুচরা ও ব্যবসায়িক গ্রাহকদের কাছে স্মার্ট ডিজিটাল ব্যাংকিং সমাধান পৌঁছে দিতে মনোযোগী।",
    savings: [
      {
        slug: "citizens-savings",
        name: "Citizens Bank Savings Account",
        nameBn: "সিটিজেন্স ব্যাংক সঞ্চয়ী হিসাব",
        interestRate: 4.5,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        onlineAccountOpening: true,
        features: ["Digital-first banking", "Instant account opening", "Zero fee transactions"],
        featuresBn: ["ডিজিটাল ব্যাংকিং", "তাৎক্ষণিক অ্যাকাউন্ট খোলা", "শূন্য ফি লেনদেন"],
        popularity: 55,
      },
    ],
    fdr: [
      {
        slug: "citizens-fdr",
        name: "Citizens Bank Fixed Deposit",
        nameBn: "সিটিজেন্স ব্যাংক স্থায়ী আমানত",
        minDeposit: 10000,
        loanAgainstFdrPct: 90,
        features: ["High interest rates", "Online FDR", "Auto renewal"],
        featuresBn: ["উচ্চ সুদের হার", "অনলাইন FDR", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3,6.0],[6,6.75],[12,7.75],[24,7.5]],
      },
    ],
  },

  // ── ICB Islamic Bank ──────────────────────────────────────────────────────
  {
    slug: "icb-islamic-bank",
    name: "ICB Islamic Bank PLC",
    nameBn: "আইসিবি ইসলামিক ব্যাংক পিএলসি",
    shortName: "ICB Islamic",
    category: "ISLAMIC",
    isShariah: true,
    establishedYear: 1987,
    headquarters: "19 Motijheel C/A, Dhaka",
    branchCount: 38,
    atmCount: 25,
    website: "https://www.icbislamic-bd.com",
    swiftCode: "BORIBIRD",
    brandColor: "#1B5E20",
    logoInitials: "ICB",
    rating: 3.3,
    reviewCount: 380,
    mobileAppName: "ICB Islamic Mobile",
    description:
      "ICB Islamic Bank operates on full Shariah principles, providing Islamic banking products including Mudaraba deposits and Musharaka financing.",
    descriptionBn:
      "আইসিবি ইসলামিক ব্যাংক সম্পূর্ণ শরিয়াহ নীতিতে পরিচালিত হয়, মুদারাবা আমানত ও মুশারাকা অর্থায়নসহ ইসলামী ব্যাংকিং পণ্য প্রদান করে।",
    savings: [
      {
        slug: "icb-mudaraba-savings",
        name: "ICB Islamic Mudaraba Savings",
        nameBn: "আইসিবি ইসলামিক মুদারাবা সঞ্চয়",
        interestRate: 3.25,
        minOpeningBalance: 500,
        maintenanceFee: 200,
        isShariah: true,
        features: ["Shariah compliant", "Profit sharing model", "ATM card"],
        featuresBn: ["শরিয়াহ সম্মত", "মুনাফা বণ্টন মডেল", "এটিএম কার্ড"],
        popularity: 50,
      },
    ],
    fdr: [
      {
        slug: "icb-mudaraba-term",
        name: "ICB Islamic Mudaraba Term Deposit",
        nameBn: "আইসিবি ইসলামিক মুদারাবা মেয়াদি আমানত",
        minDeposit: 10000,
        isShariah: true,
        features: ["Full Shariah compliance", "Halal profit", "Auto renewal"],
        featuresBn: ["সম্পূর্ণ শরিয়াহ সম্মত", "হালাল মুনাফা", "স্বয়ংক্রিয় নবায়ন"],
        rates: [[3,4.75],[6,5.5],[12,6.0],[24,5.75]],
      },
    ],
  },

  // ── Bangladesh Krishi Bank ────────────────────────────────────────────────
  {
    slug: "bangladesh-krishi-bank",
    name: "Bangladesh Krishi Bank",
    nameBn: "বাংলাদেশ কৃষি ব্যাংক",
    shortName: "BKB",
    category: "STATE_OWNED",
    isShariah: false,
    establishedYear: 1973,
    headquarters: "Krishi Bhaban, 83-85 Motijheel C/A, Dhaka",
    branchCount: 1036,
    atmCount: 150,
    website: "https://www.krishibank.org.bd",
    swiftCode: "BKABBDDH",
    brandColor: "#33691E",
    logoInitials: "BKB",
    rating: 3.2,
    reviewCount: 1820,
    mobileAppName: "BKB Mobile Banking",
    description:
      "Bangladesh Krishi Bank is the largest agricultural development bank, providing credit to farmers, agro-entrepreneurs and rural communities across Bangladesh.",
    descriptionBn:
      "বাংলাদেশ কৃষি ব্যাংক বৃহত্তম কৃষি উন্নয়ন ব্যাংক, সারাদেশে কৃষক, কৃষি-উদ্যোক্তা ও গ্রামীণ জনগোষ্ঠীকে ঋণ প্রদান করে।",
    savings: [
      {
        slug: "bkb-savings",
        name: "BKB Savings Account",
        nameBn: "বিকেবি সঞ্চয়ী হিসাব",
        interestRate: 4.0,
        minOpeningBalance: 200,
        maintenanceFee: 100,
        features: ["Agriculture-linked savings", "Rural branch network", "Low minimum balance"],
        featuresBn: ["কৃষি-সংযুক্ত সঞ্চয়", "গ্রামীণ শাখা নেটওয়ার্ক", "কম ন্যূনতম ব্যালেন্স"],
        popularity: 58,
      },
    ],
    fdr: [
      {
        slug: "bkb-fdr",
        name: "BKB Fixed Deposit",
        nameBn: "বিকেবি স্থায়ী আমানত",
        minDeposit: 5000,
        loanAgainstFdrPct: 80,
        features: ["Low minimum deposit", "Government guaranteed", "Agriculture loans"],
        featuresBn: ["কম ন্যূনতম আমানত", "সরকার নিশ্চিত", "কৃষি ঋণ"],
        rates: [[3,5.25],[6,5.75],[12,6.5],[24,6.25],[36,6.0]],
      },
    ],
  },
];
