export type RoutingSeed = {
  bankSlug: string;
  bankName: string;
  bankNameBn: string;
  branchName: string;
  branchNameBn: string;
  district: string;
  districtBn: string;
  routingNumber: string;
  swiftCode?: string;
  address?: string;
};

export const ROUTING_NUMBERS_DATA: RoutingSeed[] = [
  // BRAC Bank
  {
    bankSlug: "brac-bank",
    bankName: "BRAC Bank PLC",
    bankNameBn: "ব্র্যাক ব্যাংক পিএলসি",
    branchName: "Gulshan Branch",
    branchNameBn: "গুলশান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "060261726",
    swiftCode: "BRAKBDDH",
    address: "1 Gulshan Avenue, Gulshan-1, Dhaka-1212",
  },
  {
    bankSlug: "brac-bank",
    bankName: "BRAC Bank PLC",
    bankNameBn: "ব্র্যাক ব্যাংক পিএলসি",
    branchName: "Agrabad Branch",
    branchNameBn: "আগ্রাবাদ শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "060150244",
    swiftCode: "BRAKBDDH",
    address: "Agrabad C/A, Chattogram",
  },
  {
    bankSlug: "brac-bank",
    bankName: "BRAC Bank PLC",
    bankNameBn: "ব্র্যাক ব্যাংক পিএলসি",
    branchName: "Zindabazar Branch",
    branchNameBn: "জিন্দাবাজার শাখা",
    district: "Sylhet",
    districtBn: "সিলেট",
    routingNumber: "060912108",
    swiftCode: "BRAKBDDH",
    address: "Zindabazar, Sylhet",
  },
  {
    bankSlug: "brac-bank",
    bankName: "BRAC Bank PLC",
    bankNameBn: "ব্র্যাক ব্যাংক পিএলসি",
    branchName: "Uttara Branch",
    branchNameBn: "উত্তরা শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "060264789",
    swiftCode: "BRAKBDDH",
    address: "Sector 3, Uttara, Dhaka",
  },

  // The City Bank
  {
    bankSlug: "the-city-bank",
    bankName: "The City Bank PLC",
    bankNameBn: "দি সিটি ব্যাংক পিএলসি",
    branchName: "Principal Branch (Dilkusha)",
    branchNameBn: "প্রধান শাখা (দিলকুশা)",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "225260428",
    swiftCode: "CIBLBDDH",
    address: "City Bank Center, 136 Dilkusha C/A, Dhaka",
  },
  {
    bankSlug: "the-city-bank",
    bankName: "The City Bank PLC",
    bankNameBn: "দি সিটি ব্যাংক পিএলসি",
    branchName: "Gulshan Branch",
    branchNameBn: "গুলশান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "225261456",
    swiftCode: "CIBLBDDH",
    address: "Gulshan-2, Dhaka",
  },
  {
    bankSlug: "the-city-bank",
    bankName: "The City Bank PLC",
    bankNameBn: "দি সিটি ব্যাংক পিএলসি",
    branchName: "Khatunganj Branch",
    branchNameBn: "খাতুনগঞ্জ শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "225152890",
    swiftCode: "CIBLBDDH",
    address: "Khatunganj, Chattogram",
  },

  // Eastern Bank Limited (EBL)
  {
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank PLC (EBL)",
    bankNameBn: "ইস্টার্ন ব্যাংক পিএলসি",
    branchName: "Principal Branch",
    branchNameBn: "প্রধান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "095260178",
    swiftCode: "EBLBBDDH",
    address: "10 Dilkusha C/A, Dhaka-1000",
  },
  {
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank PLC (EBL)",
    bankNameBn: "ইস্টার্ন ব্যাংক পিএলসি",
    branchName: "Banani Branch",
    branchNameBn: "বনানী শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "095260592",
    swiftCode: "EBLBBDDH",
    address: "Road 11, Block D, Banani, Dhaka",
  },
  {
    bankSlug: "eastern-bank",
    bankName: "Eastern Bank PLC (EBL)",
    bankNameBn: "ইস্টার্ন ব্যাংক পিএলসি",
    branchName: "GEC Circle Branch",
    branchNameBn: "জিইসি সার্কেল শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "095150821",
    swiftCode: "EBLBBDDH",
    address: "GEC Circle, Chattogram",
  },

  // Islami Bank Bangladesh PLC
  {
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh PLC",
    bankNameBn: "ইসলামী ব্যাংক বাংলাদেশ পিএলসি",
    branchName: "Local Office (Dilkusha)",
    branchNameBn: "লোকাল অফিস (দিলকুশা)",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "125262708",
    swiftCode: "IBBLBDDH",
    address: "40 Dilkusha C/A, Dhaka",
  },
  {
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh PLC",
    bankNameBn: "ইসলামী ব্যাংক বাংলাদেশ পিএলসি",
    branchName: "Agrabad Corporate Branch",
    branchNameBn: "আগ্রাবাদ কর্পোরেট শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "125150124",
    swiftCode: "IBBLBDDH",
    address: "Agrabad C/A, Chattogram",
  },
  {
    bankSlug: "islami-bank-bangladesh",
    bankName: "Islami Bank Bangladesh PLC",
    bankNameBn: "ইসলামী ব্যাংক বাংলাদেশ পিএলসি",
    branchName: "Sylhet Branch",
    branchNameBn: "সিলেট শাখা",
    district: "Sylhet",
    districtBn: "সিলেট",
    routingNumber: "125910345",
    swiftCode: "IBBLBDDH",
    address: "Laldighirpar, Sylhet",
  },

  // Dutch-Bangla Bank PLC
  {
    bankSlug: "dutch-bangla-bank",
    bankName: "Dutch-Bangla Bank PLC",
    bankNameBn: "ডাচ্-বাংলা ব্যাংক পিএলসি",
    branchName: "Motijheel Foreign Exchange Branch",
    branchNameBn: "মতিঝিল বৈদেশিক বিনিময় শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "090262629",
    swiftCode: "DBBLBDDH",
    address: "Sena Kalyan Bhaban, 195 Motijheel C/A, Dhaka",
  },
  {
    bankSlug: "dutch-bangla-bank",
    bankName: "Dutch-Bangla Bank PLC",
    bankNameBn: "ডাচ্-বাংলা ব্যাংক পিএলসি",
    branchName: "Dhanmondi Branch",
    branchNameBn: "ধানমন্ডি শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "090261316",
    swiftCode: "DBBLBDDH",
    address: "Road 27, Dhanmondi, Dhaka",
  },
  {
    bankSlug: "dutch-bangla-bank",
    bankName: "Dutch-Bangla Bank PLC",
    bankNameBn: "ডাচ্-বাংলা ব্যাংক পিএলসি",
    branchName: "Muradpur Branch",
    branchNameBn: "মুরাদপুর শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "090151874",
    swiftCode: "DBBLBDDH",
    address: "Muradpur, Chattogram",
  },

  // Standard Chartered Bangladesh
  {
    bankSlug: "standard-chartered-bangladesh",
    bankName: "Standard Chartered Bank Bangladesh",
    bankNameBn: "স্ট্যান্ডার্ড চার্টার্ড ব্যাংক বাংলাদেশ",
    branchName: "Main Branch (North End Gulshan)",
    branchNameBn: "মেইন শাখা (গুলশান)",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "215261899",
    swiftCode: "SCBLBDDX",
    address: "67 Gulshan Avenue, Dhaka",
  },
  {
    bankSlug: "standard-chartered-bangladesh",
    bankName: "Standard Chartered Bank Bangladesh",
    bankNameBn: "স্ট্যান্ডার্ড চার্টার্ড ব্যাংক বাংলাদেশ",
    branchName: "Agrabad Branch",
    branchNameBn: "আগ্রাবাদ শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "215150532",
    swiftCode: "SCBLBDDX",
    address: "Sheikh Mujib Road, Agrabad, Chattogram",
  },

  // United Commercial Bank (UCB)
  {
    bankSlug: "united-commercial-bank",
    bankName: "United Commercial Bank PLC (UCB)",
    bankNameBn: "ইউনাইটেড কমার্শিয়াল ব্যাংক পিএলসি",
    branchName: "Corporate Branch",
    branchNameBn: "কর্পোরেট শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "245260123",
    swiftCode: "UCBLBDDH",
    address: "Plot CWS(A)-1, Road 34, Gulshan-1, Dhaka",
  },
  {
    bankSlug: "united-commercial-bank",
    bankName: "United Commercial Bank PLC (UCB)",
    bankNameBn: "ইউনাইটেড কমার্শিয়াল ব্যাংক পিএলসি",
    branchName: "Dampara Branch",
    branchNameBn: "দাম্পাড়া শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "245150882",
    swiftCode: "UCBLBDDH",
    address: "Dampara, Chattogram",
  },

  // Mutual Trust Bank (MTB)
  {
    bankSlug: "mutual-trust-bank",
    bankName: "Mutual Trust Bank PLC (MTB)",
    bankNameBn: "মিউচুয়াল ট্রাস্ট ব্যাংক পিএলসি",
    branchName: "Principal Branch (Gulshan)",
    branchNameBn: "প্রধান শাখা (গুলশান)",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "145261450",
    swiftCode: "MTBLBDDH",
    address: "MTB Centre, 26 Gulshan Avenue, Dhaka",
  },
  {
    bankSlug: "mutual-trust-bank",
    bankName: "Mutual Trust Bank PLC (MTB)",
    bankNameBn: "মিউচুয়াল ট্রাস্ট ব্যাংক পিএলসি",
    branchName: "Jubilee Road Branch",
    branchNameBn: "জুবিলি রোড শাখা",
    district: "Chattogram",
    districtBn: "চট্টগ্রাম",
    routingNumber: "145150774",
    swiftCode: "MTBLBDDH",
    address: "Jubilee Road, Chattogram",
  },

  // Dhaka Bank
  {
    bankSlug: "dhaka-bank",
    bankName: "Dhaka Bank PLC",
    bankNameBn: "ঢাকা ব্যাংক পিএলসি",
    branchName: "Main Branch (Dilkusha)",
    branchNameBn: "প্রধান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "085260421",
    swiftCode: "DHBLBDDH",
    address: "71 Dilkusha C/A, Dhaka",
  },

  // Trust Bank
  {
    bankSlug: "trust-bank",
    bankName: "Trust Bank PLC",
    bankNameBn: "ট্রাস্ট ব্যাংক পিএলসি",
    branchName: "Principal Branch",
    branchNameBn: "প্রধান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "240260233",
    swiftCode: "TRBLBDDH",
    address: "Shadhinata Tower, Bir Shreshtha Shaheed Jahangir Gate, Dhaka",
  },

  // Prime Bank
  {
    bankSlug: "prime-bank",
    bankName: "Prime Bank PLC",
    bankNameBn: "প্রাইম ব্যাংক পিএলসি",
    branchName: "Motijheel Branch",
    branchNameBn: "মতিঝিল শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "170260655",
    swiftCode: "PRBLBDDH",
    address: "119-120 Motijheel C/A, Dhaka",
  },

  // Sonali Bank
  {
    bankSlug: "sonali-bank",
    bankName: "Sonali Bank PLC",
    bankNameBn: "সোনালী ব্যাংক পিএলসি",
    branchName: "Local Office",
    branchNameBn: "লোকাল অফিস",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "200262334",
    swiftCode: "BSONBDDH",
    address: "Motijheel C/A, Dhaka-1000",
  },

  // Pubali Bank
  {
    bankSlug: "pubali-bank",
    bankName: "Pubali Bank PLC",
    bankNameBn: "পূবালী ব্যাংক পিএলসি",
    branchName: "Principal Branch",
    branchNameBn: "প্রধান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "175260782",
    swiftCode: "PUBLBDDH",
    address: "26 Dilkusha C/A, Dhaka",
  },

  // Bank Asia
  {
    bankSlug: "bank-asia",
    bankName: "Bank Asia PLC",
    bankNameBn: "ব্যাংক এশিয়া পিএলসি",
    branchName: "Principal Branch",
    branchNameBn: "প্রধান শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "030260334",
    swiftCode: "BALBBDDH",
    address: "Rangs Tower, 68 Purana Paltan, Dhaka",
  },

  // Al-Arafah Islami Bank
  {
    bankSlug: "al-arafah-islami-bank",
    bankName: "Al-Arafah Islami Bank PLC",
    bankNameBn: "আল-আরাফাহ্ ইসলামী ব্যাংক পিএলসি",
    branchName: "Motijheel Corporate Branch",
    branchNameBn: "মতিঝিল কর্পোরেট শাখা",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "015260212",
    swiftCode: "ALIBBDDH",
    address: "63 Purana Paltan, Dhaka",
  },

  // HSBC Bangladesh
  {
    bankSlug: "hsbc-bangladesh",
    bankName: "HSBC Bangladesh",
    bankNameBn: "এইচএসবিসি বাংলাদেশ",
    branchName: "Dhaka Main Office",
    branchNameBn: "ঢাকা মেইন অফিস",
    district: "Dhaka",
    districtBn: "ঢাকা",
    routingNumber: "115260111",
    swiftCode: "HSBCBDDH",
    address: "Level 4, Shanta Western Tower, Bir Uttam Mir Shawkat Sarak, Tejgaon, Dhaka",
  },
];
