import type { CreditCardSeed } from "./creditSeed";

/**
 * Ultimate Credit Cards dataset for Bangladesh banks — v4
 * Adds 65+ specialized, co-branded, premium and women-centric credit cards
 * bringing total credit cards in the database to 175+.
 */
export const ULTIMATE_CREDIT_CARDS: { bankSlug: string; cards: CreditCardSeed[] }[] = [
  // ── The City Bank (AMEX & Visa) ──────────────────────────────────────────
  {
    bankSlug: "the-city-bank",
    cards: [
      {
        slug: "city-amex-green",
        name: "City Bank American Express Green Card",
        nameBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস গ্রিন কার্ড",
        network: "AMEX",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 POS transactions in a calendar year",
        feeWaiverConditionBn: "এক ক্যালেন্ডার বছরে ১৫টি পিওএস লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Membership Rewards point for every ৳50 spent",
        rewardSummaryBn: "প্রতি ৫০ টাকা খরচে ১ মেম্বারশিপ রিওয়ার্ডস পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#059669",
        features: ["Worldwide Amex acceptance", "City Bank FlexiBuy 0% interest", "Emergency card replacement worldwide"],
        featuresBn: ["বিশ্বব্যাপী অ্যামেক্স সুবিধা", "সিটি ব্যাংক ফ্লেক্সিবাই ০% সুদ", "বিশ্বব্যাপী জরুরি কার্ড প্রতিস্থাপন"],
        popularity: 80,
      },
      {
        slug: "city-amex-blue",
        name: "City Bank American Express Blue Card",
        nameBn: "সিটি ব্যাংক আমেরিকান এক্সপ্রেস ব্লু কার্ড",
        network: "AMEX",
        tier: "CLASSIC",
        annualFee: 1000,
        feeWaiverCondition: "Waived on 12 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি খুচরা লেনদেনে বার্ষিক ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1% automatic cashback on all POS & online spending",
        rewardSummaryBn: "সব পিওএস ও অনলাইন কেনাকাটায় ১% স্বয়ংক্রিয় ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#0284C7",
        features: ["1% automatic cashback credited monthly", "Low income eligibility for young professionals", "Contactless Tap & Pay"],
        featuresBn: ["মাসে ১% ক্যাশব্যাক সরাসরি জমা", "তরুণ পেশাজীবীদের জন্য সহজ আয়ের শর্ত", "কন্ট্যাক্টলেস ট্যাপ অ্যান্ড পে"],
        popularity: 78,
      },
      {
        slug: "city-alo-amex",
        name: "City Alo American Express Credit Card (Women)",
        nameBn: "সিটি আলো আমেরিকান এক্সপ্রেস ক্রেডিট কার্ড (নারী বিশেষ)",
        network: "AMEX",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Waived on annual spend of ৳1,50,000",
        feeWaiverConditionBn: "বার্ষিক ১,৫০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to City Bank American Express Lounge at HSIA",
        loungeDetailsBn: "শাহজালাল আন্তর্জাতিক বিমানবন্দরে সিটি ব্যাংক অ্যামেক্স লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2x rewards and up to 5% cashback on beauty, wellness & education",
        rewardSummaryBn: "বিউটি, পার্লার ও শিক্ষায় ২ গুণ রিওয়ার্ড ও ৫% পর্যন্ত ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#DB2777",
        features: ["Dedicated banking for women", "Exclusive parlor & spa discounts", "Airport lounge access", "Health checkup vouchers"],
        featuresBn: ["নারীদের জন্য নিবেদিত সুবিধা", "পার্লার ও স্পায়ে বিশেষ ছাড়", "বিমানবন্দর লাউঞ্জ সুবিধা", "স্বাস্থ্য পরীক্ষার ভাউচার"],
        popularity: 88,
      },
      {
        slug: "city-agora-amex",
        name: "Agora American Express Card (Co-branded)",
        nameBn: "আগোরা আমেরিকান এক্সপ্রেস কো-ব্র্যান্ডেড কার্ড",
        network: "AMEX",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "10x points on grocery purchases at all Agora superstores",
        rewardSummaryBn: "আগোরা সুপারস্টোরে মুদি কেনাকাটায় ১০ গুণ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#E11D48",
        features: ["10x Agora grocery reward points", "Exclusive weekly grocery discounts", "Free home delivery from Agora"],
        featuresBn: ["আগোরায় ১০ গুণ পয়েন্ট", "সাপ্তাহিক বিশেষ মুদি ছাড়", "আগোরা থেকে ফ্রি হোম ডেলিভারি"],
        popularity: 82,
      },
      {
        slug: "city-mastercard-world",
        name: "City Bank Mastercard World Credit Card",
        nameBn: "সিটি ব্যাংক মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 10000,
        feeWaiverCondition: "Waived on annual spend of ৳5,00,000",
        feeWaiverConditionBn: "বার্ষিক ৫,০০,০০০ টাকা খরচে সম্পূর্ণ ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 100000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited international airport lounge visits via LoungeKey + HSIA City Bank Lounge",
        loungeDetailsBn: "লাউঞ্জকি এর মাধ্যমে বিশ্বব্যাপী আনলিমিটেড লাউঞ্জ ও শাহজালালে সিটি ব্যাংক লাউঞ্জ",
        rewardType: "MILES",
        rewardSummary: "4 air miles or 3 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৪ এয়ার মাইলস অথবা ৩ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        isShariah: false,
        cardColor: "#0F172A",
        features: ["Unlimited global lounge access", "Complimentary golf privileges", "Comprehensive international travel insurance", "24/7 global concierge"],
        featuresBn: ["বিশ্বব্যাপী আনলিমিটেড লাউঞ্জ", "ফ্রি গলফ সুবিধা", "আন্তর্জাতিক ভ্রমণ বীমা", "২৪/৭ গ্লোবাল কনসিয়ার্জ"],
        popularity: 94,
      },
    ],
  },

  // ── Standard Chartered Bangladesh ──────────────────────────────────────────
  {
    bankSlug: "standard-chartered-bangladesh",
    cards: [
      {
        slug: "scb-saadiq-visa-platinum",
        name: "Standard Chartered Saadiq Visa Platinum Card (Islamic)",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড সাদিক ভিসা প্ল্যাটিনাম কার্ড (ইসলামিক)",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on 18 retail transactions per annum",
        feeWaiverConditionBn: "বার্ষিক ১৮টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA and Saadiq Lounges",
        loungeDetailsBn: "শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 Halal 360° Rewards points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ হালাল ৩৬০° রিওয়ার্ডস পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#047857",
        features: ["100% Shariah compliant under SCB Saadiq board", "Ujrah pricing with zero compounding", "Balaka Lounge access", "Umrah package EMI"],
        featuresBn: ["১০০% শরিয়াহ সম্মত সাদিক বোর্ড অনুমোদিত", "সুদমুক্ত উজরহ ফি কাঠামো", "বলাকা লাউঞ্জ সুবিধা", "ওমরাহ প্যাকেজে কিস্তি"],
        popularity: 91,
      },
      {
        slug: "scb-saadiq-visa-gold",
        name: "Standard Chartered Saadiq Visa Gold Card (Islamic)",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড সাদিক ভিসা গোল্ড কার্ড (ইসলামিক)",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 15 retail transactions per annum",
        feeWaiverConditionBn: "বার্ষিক ১৫টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal 360° Rewards points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#059669",
        features: ["Islamic Banking principle of Ujrah", "Global emergency assistance", "Zero EMI at 600+ partner outlets"],
        featuresBn: ["উজরহ নীতির ইসলামিক ব্যাংকিং", "গ্লোবাল ইমার্জেন্সি সহায়তা", "৬০০+ পার্টনার শপে ০% ইএমআই"],
        popularity: 84,
      },
      {
        slug: "scb-priority-visa-infinite",
        name: "Standard Chartered Priority Visa Infinite Credit Card",
        nameBn: "স্ট্যান্ডার্ড চার্টার্ড প্রায়োরিটি ভিসা ইনফিনিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 15000,
        feeWaiverCondition: "Complimentary for SCB Priority Banking clients",
        feeWaiverConditionBn: "এসসিবি প্রায়োরিটি ব্যাংকিং গ্রাহকদের জন্য সম্পূর্ণ বিনামূল্যে",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 150000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited international airport lounge access worldwide for cardholder + guest",
        loungeDetailsBn: "কার্ডহোল্ডার ও সঙ্গীর জন্য বিশ্বব্যাপী সীমাহীন আন্তর্জাতিক লাউঞ্জ প্রবেশ",
        rewardType: "MILES",
        rewardSummary: "5 air miles or 4 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৫ এয়ার মাইলস অথবা ৪ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        isShariah: false,
        cardColor: "#020617",
        features: ["Unlimited global lounge access + 1 guest", "Complimentary green fees at world golf courses", "$1,000,000 travel insurance", "Dedicated Priority Relationship Manager"],
        featuresBn: ["বিশ্বব্যাপী সীমাহীন লাউঞ্জ + ১ জন সঙ্গী", "বিশ্বমানের গলফ কোর্সে ফ্রি প্রবেশ", "১০ লক্ষ ডলারের আন্তর্জাতিক ভ্রমণ বীমা", "ডেডিকেটেড প্রায়োরিটি ম্যানেজার"],
        popularity: 97,
      },
    ],
  },

  // ── BRAC Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "brac-bank",
    cards: [
      {
        slug: "brac-tara-platinum",
        name: "BRAC Bank TARA Visa Platinum Card (Women)",
        nameBn: "ব্র্যাক ব্যাংক তারা ভিসা প্ল্যাটিনাম কার্ড (নারী বিশেষ)",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Waived on 15 transactions in a year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 30000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "5% cashback on fashion, beauty, wellness & lifestyle stores",
        rewardSummaryBn: "ফ্যাশন, বিউটি, পার্লার ও লাইফস্টাইলে ৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#9333EA",
        features: ["Special women lifestyle privileges", "5% cashback on lifestyle brands", "Health screening vouchers", "Balaka Lounge access"],
        featuresBn: ["নারীদের জন্য বিশেষ লাইফস্টাইল সুবিধা", "ব্র্যান্ডে ৫% ক্যাশব্যাক", "স্বাস্থ্য পরীক্ষার ভাউচার", "বলাকা লাউঞ্জ সুবিধা"],
        popularity: 90,
      },
      {
        slug: "brac-visa-classic",
        name: "BRAC Bank Visa Classic Credit Card",
        nameBn: "ব্র্যাক ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 12 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#2563EB",
        features: ["0% PayFlex installment facility", "Wide ATM and branch network", "SMS banking alerts"],
        featuresBn: ["০% পে-ফ্লেক্স কিস্তি সুবিধা", "বিস্তৃত এটিএম নেটওয়ার্ক", "এসএমএস ব্যাংকিং সতর্কবার্তা"],
        popularity: 70,
      },
    ],
  },

  // ── Eastern Bank (EBL) ───────────────────────────────────────────────────
  {
    bankSlug: "eastern-bank",
    cards: [
      {
        slug: "ebl-shwapno-cobrand",
        name: "EBL Shwapno Visa Co-branded Credit Card",
        nameBn: "ইবিএল স্বপ্ন ভিসা কো-ব্র্যান্ডেড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "5% cashback on all grocery purchases at Shwapno",
        rewardSummaryBn: "স্বপ্নের সব সুপারস্টোরে মুদি কেনাকাটায় ৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#EAB308",
        features: ["5% grocery cashback at all Shwapno outlets", "Priority checkout counter at Shwapno", "EBL ZIP 0% EMI"],
        featuresBn: ["স্বপ্নে কেনাকাটায় ৫% ক্যাশব্যাক", "স্বপ্নে প্রায়োরিটি বিলিং কাউন্টার", "ইবিএল জিপ ০% ইএমআই"],
        popularity: 86,
      },
      {
        slug: "ebl-visa-gold",
        name: "EBL Visa Gold Credit Card",
        nameBn: "ইবিএল ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 18 transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৮টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#D97706",
        features: ["EBL ZIP 0% EMI up to 24 months", "B1G1 dining offers", "Complimentary companion insurance"],
        featuresBn: ["২৪ মাস পর্যন্ত ইবিএল জিপ ০% কিস্তি", "বি১জি১ খাবার অফার", "বিনামূল্যে ভ্রমণ বীমা"],
        popularity: 79,
      },
      {
        slug: "ebl-visa-classic",
        name: "EBL Visa Classic Credit Card",
        nameBn: "ইবিএল ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#1E3A8A",
        features: ["Low entry income threshold", "EBL ZIP installment", "Zero liability on lost card"],
        featuresBn: ["কম আয়ের যোগ্যতা", "ইবিএল জিপ কিস্তি", "হারিয়ে যাওয়া কার্ডে শূন্য দায়"],
        popularity: 72,
      },
    ],
  },

  // ── Mutual Trust Bank (MTB) ──────────────────────────────────────────────
  {
    bankSlug: "mutual-trust-bank",
    cards: [
      {
        slug: "mtb-angona-platinum",
        name: "MTB Angona Mastercard Platinum (Women)",
        nameBn: "এমটিবি অঙ্গনা মাস্টারকার্ড প্ল্যাটিনাম (নারী বিশেষ)",
        network: "MASTERCARD",
        tier: "PLATINUM",
        annualFee: 3500,
        feeWaiverCondition: "Waived on annual spend of ৳1,20,000",
        feeWaiverConditionBn: "বার্ষিক ১,২০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to MTB Air Lounge at HSIA, Shah Amanat & Osmani airports",
        loungeDetailsBn: "শাহজালাল, শাহ আমানত ও ওসমানী বিমানবন্দরে এমটিবি এয়ার লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "Up to 5% cashback on beauty parlors, jewellery & lifestyle retail",
        rewardSummaryBn: "পার্লার, গহনা ও লাইফস্টাইলে ৫% পর্যন্ত ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#BE185D",
        features: ["Free access to all 3 MTB Air Lounges in BD", "5% wellness & parlor cashback", "Free health checkup coupon", "B1G1 buffet dining"],
        featuresBn: ["দেশের ৩টি এমটিবি এয়ার লাউঞ্জেই ফ্রি প্রবেশ", "পার্লারে ৫% ক্যাশব্যাক", "ফ্রি স্বাস্থ্য পরীক্ষা", "বি১জি১ বুফে খাবার"],
        popularity: 89,
      },
      {
        slug: "mtb-visa-gold",
        name: "MTB Visa Gold Credit Card",
        nameBn: "এমটিবি ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 15 transactions in a year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#B45309",
        features: ["MTB FlexiPay 0% interest", "Emergency cash advance", "Discounts at 500+ merchants"],
        featuresBn: ["এমটিবি ফ্লেক্সিপে ০% সুদ", "জরুরি ক্যাশ অগ্রিম", "৫০০+ দোকানে ডিসকাউন্ট"],
        popularity: 76,
      },
      {
        slug: "mtb-visa-classic",
        name: "MTB Visa Classic Credit Card",
        nameBn: "এমটিবি ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 12 transactions annually",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#0284C7",
        features: ["Affordable annual fee", "FlexiPay 0% installment", "24/7 contact center"],
        featuresBn: ["সাশ্রয়ী বার্ষিক ফি", "ফ্লেক্সিপে ০% কিস্তি", "২৪/৭ কন্টাক্ট সেন্টার"],
        popularity: 71,
      },
    ],
  },

  // ── United Commercial Bank (UCB) ──────────────────────────────────────────
  {
    bankSlug: "united-commercial-bank",
    cards: [
      {
        slug: "ucb-imperial-world-mastercard",
        name: "UCB Imperial World Mastercard",
        nameBn: "ইউসিবি ইম্পেরিয়াল ওয়ার্ল্ড মাস্টারকার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 8000,
        feeWaiverCondition: "Waived on annual spend of ৳4,00,000",
        feeWaiverConditionBn: "বার্ষিক ৪,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 80000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Unlimited access to UCB Imperial Lounge at HSIA + LoungeKey global access",
        loungeDetailsBn: "শাহজালাল বিমানবন্দরে ইউসিবি ইম্পেরিয়াল লাউঞ্জে আনলিমিটেড প্রবেশ ও লাউঞ্জকি",
        rewardType: "MILES",
        rewardSummary: "4 airline miles or 3.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৪ এয়ার মাইলস অথবা ৩.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        isShariah: false,
        cardColor: "#0F172A",
        features: ["Unlimited UCB Imperial Lounge access", "B1G1 5-star hotel buffet dining", "Worldwide travel medical protection", "Mastercard golf privileges"],
        featuresBn: ["ইউসিবি ইম্পেরিয়াল লাউঞ্জে ফ্রি প্রবেশ", "৫-স্টার হোটেল বুফে বি১জি১", "আন্তর্জাতিক চিকিৎসা ভ্রমণ বীমা", "মাস্টারকার্ড গলফ সুবিধা"],
        popularity: 93,
      },
      {
        slug: "ucb-visa-gold",
        name: "UCB Visa Gold Credit Card",
        nameBn: "ইউসিবি ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 15 retail transactions in a year",
        feeWaiverConditionBn: "এক বছরে ১৫টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#D97706",
        features: ["UCB U-Plan 0% EMI", "Discounts at 450+ merchant partner outlets", "Free SMS alerts"],
        featuresBn: ["ইউসিবি ইউ-প্ল্যান ০% কিস্তি", "৪৫০+ দোকানে বিশেষ ছাড়", "বিনামূল্যে এসএমএস সতর্কতা"],
        popularity: 77,
      },
      {
        slug: "ucb-visa-classic",
        name: "UCB Visa Classic Credit Card",
        nameBn: "ইউসিবি ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 12 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১২টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#2563EB",
        features: ["Convenient installment purchase", "Accepted nationwide & globally", "Easy bill pay"],
        featuresBn: ["সহজ কিস্তিতে ক্রয়", "দেশ ও বিদেশে সার্বজনীন গ্রহণযোগ্যতা", "ইউটিলিটি বিল পরিশোধ"],
        popularity: 72,
      },
    ],
  },

  // ── Trust Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "trust-bank",
    cards: [
      {
        slug: "trust-visa-signature",
        name: "Trust Bank Visa Signature Credit Card",
        nameBn: "ট্রাস্ট ব্যাংক ভিসা সিগনেচার ক্রেডিট কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 6000,
        feeWaiverCondition: "Waived on annual spend of ৳2,50,000",
        feeWaiverConditionBn: "বার্ষিক ২,৫০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#065F46",
        features: ["Balaka Lounge access", "2.5x rewards", "B1G1 dining privileges", "Golf club benefits"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "২.৫x পয়েন্ট", "বি১জি১ ডাইনিং অফার", "গলফ ক্লাব সুবিধা"],
        popularity: 85,
      },
      {
        slug: "trust-defence-credit-card",
        name: "Trust Bank Defence Personnel Platinum Card",
        nameBn: "ট্রাস্ট ব্যাংক ডিফেন্স পার্সোনেল প্ল্যাটিনাম কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 1500,
        feeWaiverCondition: "Lifetime free for serving & retired armed forces officers",
        feeWaiverConditionBn: "সশস্ত্র বাহিনীর কর্মরত ও অবসরপ্রাপ্ত কর্মকর্তাদের জন্য আজীবন ফ্রি",
        interestRateMonthly: 1.5,
        interestRateAnnual: 18.0,
        interestFreeDays: 50,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge and Armed Forces Officers Mess Lounges",
        loungeDetailsBn: "বলাকা লাউঞ্জ ও অফিসার্স মেস লাউঞ্জে বিশেষ প্রবেশাধিকার",
        rewardType: "CASHBACK",
        rewardSummary: "2% cashback on CSD stores and cantonment facilities",
        rewardSummaryBn: "সিএসডি স্টোর ও ক্যান্টনমেন্ট কেনাকাটায় ২% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#1E3A8A",
        features: ["Special 18% low APR for armed forces", "Lifetime free for defence personnel", "2% CSD canteen cashback", "Balaka Lounge access"],
        featuresBn: ["সেনাবাহিনীর জন্য বিশেষ ১৮% কম সুদ", "সামরিক কর্মকর্তাদের জন্য আজীবন ফ্রি", "সিএসডিতে ২% ক্যাশব্যাক", "বলাকা লাউঞ্জ সুবিধা"],
        popularity: 92,
      },
      {
        slug: "trust-visa-gold",
        name: "Trust Bank Visa Gold Credit Card",
        nameBn: "ট্রাস্ট ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 15 transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#D97706",
        features: ["Trust EasyPay 0% EMI", "Special hospital discounts", "Dual currency travel quota"],
        featuresBn: ["ট্রাস্ট ইজিপে ০% কিস্তি", "হাসপাতালে বিশেষ ছাড়", "দ্বৈত-মুদ্রা ভ্রমণ কোটা"],
        popularity: 74,
      },
    ],
  },

  // ── Dhaka Bank ────────────────────────────────────────────────────────────
  {
    bankSlug: "dhaka-bank",
    cards: [
      {
        slug: "dhaka-bank-mastercard-world",
        name: "Dhaka Bank Mastercard World Credit Card",
        nameBn: "ঢাকা ব্যাংক মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 8000,
        feeWaiverCondition: "Waived on annual spend of ৳3,50,000",
        feeWaiverConditionBn: "বার্ষিক ৩,৫০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 75000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Dhaka Bank Lounge at HSIA + Mastercard LoungeKey worldwide",
        loungeDetailsBn: "শাহজালাল বিমানবন্দরে ঢাকা ব্যাংক লাউঞ্জে এবং বিশ্বব্যাপী লাউঞ্জকিতে ফ্রি প্রবেশ",
        rewardType: "MILES",
        rewardSummary: "4 air miles or 3.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ৪ এয়ার মাইলস অথবা ৩.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 36,
        contactless: true,
        isShariah: false,
        cardColor: "#0F172A",
        features: ["Dhaka Bank HSIA lounge access", "B1G1 buffet dining at 5-star hotels", "Comprehensive international travel takaful", "0% Swipe-It installment"],
        featuresBn: ["ঢাকা ব্যাংক এয়ারপোর্ট লাউঞ্জ সুবিধা", "ফাইভ-স্টার হোটেলে বি১জি১ বুফে", "আন্তর্জাতিক ভ্রমণ বীমা", "০% সোয়াইপ-ইট কিস্তি"],
        popularity: 88,
      },
      {
        slug: "dhaka-bank-visa-classic",
        name: "Dhaka Bank Visa Classic Credit Card",
        nameBn: "ঢাকা ব্যাংক ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1500,
        feeWaiverCondition: "Waived on 15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#1E3A8A",
        features: ["Swipe-It 0% EMI", "Convenient digital banking", "Nationwide merchant discounts"],
        featuresBn: ["সোয়াইপ-ইট ০% কিস্তি", "সহজ ডিজিটাল ব্যাংকিং", "সারাদেশে বিভিন্ন দোকানে ছাড়"],
        popularity: 70,
      },
    ],
  },

  // ── Dutch-Bangla Bank (DBBL) ──────────────────────────────────────────────
  {
    bankSlug: "dutch-bangla-bank",
    cards: [
      {
        slug: "dbbl-nexus-mastercard-world",
        name: "DBBL Nexus-Mastercard World Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-মাস্টারকার্ড ওয়ার্ল্ড ক্রেডিট কার্ড",
        network: "MASTERCARD",
        tier: "WORLD",
        annualFee: 7000,
        feeWaiverCondition: "Waived on annual spend of ৳3,00,000",
        feeWaiverConditionBn: "বার্ষিক ৩,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 55,
        minIncome: 70000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA + global LoungeKey",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে এবং বিশ্বব্যাপী লাউঞ্জকিতে প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2% cashback on international & supermarket transactions",
        rewardSummaryBn: "আন্তর্জাতিক ও সুপারমার্কেট লেনদেনে ২% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#1E293B",
        features: ["Access to Bangladesh largest 5000+ ATM network", "Balaka Lounge + LoungeKey access", "2% cashback on supermarkets", "NexusPay QR payment integration"],
        featuresBn: ["দেশের বৃহত্তম ৫০০০+ এটিএম সুবিধা", "বলাকা ও লাউঞ্জকি সুবিধা", "সুপারমার্কেটে ২% ক্যাশব্যাক", "নেক্সাসপে কিউআর ইন্টিগ্রেশন"],
        popularity: 91,
      },
      {
        slug: "dbbl-nexus-visa-classic",
        name: "DBBL Nexus-Visa Classic Credit Card",
        nameBn: "ডিবিবিএল নেক্সাস-ভিসা ক্লাসিক ক্রেডিট কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: false,
        cardColor: "#0284C7",
        features: ["Lowest annual fee among top private banks", "Seamless NexusPay integration", "Zero ATM withdrawal charges at 5000+ DBBL ATMs"],
        featuresBn: ["শীর্ষ ব্যাংকের মধ্যে সর্বনিম্ন বার্ষিক ফি", "নেক্সাসপে এর সাথে যুক্ত", "ডিবিবিএল এটিএমে শূন্য চার্জে উত্তোলন"],
        popularity: 81,
      },
    ],
  },

  // ── Islami Bank Bangladesh (IBBL) ─────────────────────────────────────────
  {
    bankSlug: "islami-bank-bangladesh",
    cards: [
      {
        slug: "ibbl-khidmah-classic",
        name: "IBBL Khidmah Visa Classic Card",
        nameBn: "আইবিবিএল খিদমাহ ভিসা ক্লাসিক কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1000,
        feeWaiverCondition: "Waived on 15 Shariah compliant transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি হালাল লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#15803D",
        features: ["100% Shariah compliant Riba-free", "Fixed Ujrah fee structure", "Zero interest and zero late compounding penalty"],
        featuresBn: ["১০০% শরিয়াহ সম্মত সুদহীন", "নির্দিষ্ট উজরহ ফি কাঠামো", "কোনো সুদ বা চক্রবৃদ্ধি বিলম্ব চার্জ নেই"],
        popularity: 82,
      },
      {
        slug: "ibbl-khidmah-signature",
        name: "IBBL Khidmah Visa Signature Card",
        nameBn: "আইবিবিএল খিদমাহ ভিসা সিগনেচার কার্ড",
        network: "VISA",
        tier: "SIGNATURE",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা খরচে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 50,
        minIncome: 50000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2.5 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২.৫ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: true,
        cardColor: "#064E3B",
        features: ["Balaka Lounge access", "Umrah package 0% installment", "Halal 5-star buffet privileges", "Islamic travel Takaful"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "ওমরাহ প্যাকেজে ০% কিস্তি", "হালাল ৫-স্টার বুফে অফার", "ইসলামিক ভ্রমণ তাকাফুল বীমা"],
        popularity: 90,
      },
    ],
  },

  // ── Shimanto Bank ─────────────────────────────────────────────────────────
  {
    bankSlug: "shimanto-bank",
    cards: [
      {
        slug: "shimanto-visa-gold",
        name: "Shimanto Bank Visa Gold Credit Card",
        nameBn: "শিমান্তো ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on 15 retail transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ রিওয়ার্ড পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#334155",
        features: ["Border-trade merchant discounts", "1.5x reward points", "0% EasyPay installment"],
        featuresBn: ["সীমান্ত বাণিজ্যে বিশেষ ছাড়", "১.৫x পয়েন্ট", "০% ইজিপে কিস্তি"],
        popularity: 61,
      },
      {
        slug: "shimanto-visa-platinum",
        name: "Shimanto Bank Visa Platinum Credit Card",
        nameBn: "শিমান্তো ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 4500,
        feeWaiverCondition: "Waived on annual spend of ৳1,80,000",
        feeWaiverConditionBn: "বার্ষিক ১,৮০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "REWARDS",
        rewardSummary: "2 reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ২ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#1E293B",
        features: ["Balaka Lounge access", "2x reward points", "Hotel & dining deals", "Travel insurance protection"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "২x রিওয়ার্ড", "হোটেল ও ডাইনিং ছাড়", "ভ্রমণ বীমা সুরক্ষা"],
        popularity: 67,
      },
    ],
  },

  // ── Citizens Bank ─────────────────────────────────────────────────────────
  {
    bankSlug: "citizens-bank",
    cards: [
      {
        slug: "citizens-visa-gold",
        name: "Citizens Bank Visa Gold Credit Card",
        nameBn: "সিটিজেন্স ব্যাংক ভিসা গোল্ড ক্রেডিট কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "First year free; waived on 15 transactions annually",
        feeWaiverConditionBn: "প্রথম বছর ফ্রি; বার্ষিক ১৫ লেনদেনে পরবর্তী বছর মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 45,
        minIncome: 20000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "CASHBACK",
        rewardSummary: "1.5% cashback on all e-commerce and retail transactions",
        rewardSummaryBn: "ই-কমার্স ও খুচরা ক্রয়ে ১.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: false,
        cardColor: "#4F46E5",
        features: ["1.5% cashback perks", "Modern digital mobile app management", "Instant card block/unblock via app"],
        featuresBn: ["১.৫% ক্যাশব্যাক", "আধুনিক ডিজিটাল অ্যাপ ব্যবস্থাপনা", "অ্যাপ দিয়ে তাৎক্ষণিক কার্ড লক সুবিধা"],
        popularity: 64,
      },
      {
        slug: "citizens-visa-platinum",
        name: "Citizens Bank Visa Platinum Credit Card",
        nameBn: "সিটিজেন্স ব্যাংক ভিসা প্ল্যাটিনাম ক্রেডিট কার্ড",
        network: "VISA",
        tier: "PLATINUM",
        annualFee: 5000,
        feeWaiverCondition: "Waived on annual spend of ৳2,00,000",
        feeWaiverConditionBn: "বার্ষিক ২,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 1.67,
        interestRateAnnual: 20.0,
        interestFreeDays: 50,
        minIncome: 35000,
        isDualCurrency: true,
        airportLoungeAccess: true,
        loungeDetails: "Complimentary access to Balaka Lounge at HSIA",
        loungeDetailsBn: "হযরত শাহজালাল আন্তর্জাতিক বিমানবন্দরে বলাকা লাউঞ্জে ফ্রি প্রবেশ",
        rewardType: "CASHBACK",
        rewardSummary: "2.5% cashback on travel, airlines & 5-star hotels",
        rewardSummaryBn: "ভ্রমণ, বিমান টিকিট ও ফাইভ-স্টার হোটেলে ২.৫% ক্যাশব্যাক",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 24,
        contactless: true,
        isShariah: false,
        cardColor: "#3730A3",
        features: ["Balaka Lounge access", "2.5% travel cashback", "B1G1 buffet dining privileges", "Full travel medical cover"],
        featuresBn: ["বলাকা লাউঞ্জ সুবিধা", "২.৫% ভ্রমণ ক্যাশব্যাক", "বি১জি১ বুফে সুবিধা", "ভ্রমণ চিকিৎসা সুরক্ষা"],
        popularity: 70,
      },
    ],
  },

  // ── Al-Arafah Islami Bank (AIBL) ──────────────────────────────────────────
  {
    bankSlug: "al-arafah-islami-bank",
    cards: [
      {
        slug: "aibl-tayyib-classic",
        name: "AIBL Tayyib Visa Classic Card",
        nameBn: "এআইবিএল তাইয়্যিব ভিসা ক্লাসিক কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 15 Shariah compliant transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি হালাল লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#15803D",
        features: ["100% Shariah compliant", "Riba-free financing", "Halal grocery discounts"],
        featuresBn: ["১০০% শরিয়াহ সম্মত", "সুদহীন অর্থায়ন", "হালাল মুদিতে বিশেষ ছাড়"],
        popularity: 66,
      },
      {
        slug: "aibl-tayyib-gold",
        name: "AIBL Tayyib Visa Gold Card",
        nameBn: "এআইবিএল তাইয়্যিব ভিসা গোল্ড কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal reward points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ হালাল পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#166534",
        features: ["1.5x Halal rewards", "Umrah package installment", "Islamic Takaful coverage"],
        featuresBn: ["১.৫ গুণ হালাল রিওয়ার্ড", "ওমরাহ প্যাকেজে কিস্তি", "ইসলামিক তাকাফুল বীমা"],
        popularity: 72,
      },
    ],
  },

  // ── Shahjalal Islami Bank (SJIBL) ─────────────────────────────────────────
  {
    bankSlug: "shahjalal-islami-bank",
    cards: [
      {
        slug: "sjibl-souhardo-classic",
        name: "SJIBL Souhardo Visa Classic Card",
        nameBn: "এসজেআইবিএল সৌহার্দ ভিসা ক্লাসিক কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 15 transactions per year",
        feeWaiverConditionBn: "বছরে ১৫টি লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#047857",
        features: ["Fully Shariah compliant", "Riba-free financing", "0% installment at partner shops"],
        featuresBn: ["সম্পূর্ণ শরিয়াহ সম্মত", "সুদহীন অর্থায়ন", "পার্টনার দোকানে ০% কিস্তি"],
        popularity: 65,
      },
      {
        slug: "sjibl-souhardo-gold",
        name: "SJIBL Souhardo Visa Gold Card",
        nameBn: "এসজেআইবিএল সৌহার্দ ভিসা গোল্ড কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#065F46",
        features: ["1.5x Halal points", "Umrah installment scheme", "Islamic hospital diagnostic discounts"],
        featuresBn: ["১.৫x পয়েন্ট", "ওমরাহ কিস্তি ব্যবস্থা", "হাসপাতালে ডায়াগনস্টিক ছাড়"],
        popularity: 71,
      },
    ],
  },

  // ── EXIM Bank ─────────────────────────────────────────────────────────────
  {
    bankSlug: "exim-bank",
    cards: [
      {
        slug: "exim-islamic-classic",
        name: "EXIM Bank Islamic Visa Classic Card",
        nameBn: "এক্সিম ব্যাংক ইসলামিক ভিসা ক্লাসিক কার্ড",
        network: "VISA",
        tier: "CLASSIC",
        annualFee: 1200,
        feeWaiverCondition: "Waived on 15 retail transactions annually",
        feeWaiverConditionBn: "বার্ষিক ১৫টি খুচরা লেনদেনে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 15000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1 Halal reward point per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 12,
        contactless: true,
        isShariah: true,
        cardColor: "#0284C7",
        features: ["Islamic Shariah compliance", "Transparent fixed monthly charges", "Halal merchant discounts"],
        featuresBn: ["ইসলামিক শরিয়াহ সম্মত", "স্বচ্ছ নির্দিষ্ট মাসিক চার্জ", "হালাল দোকানে ছাড়"],
        popularity: 67,
      },
      {
        slug: "exim-islamic-gold",
        name: "EXIM Bank Islamic Visa Gold Card",
        nameBn: "এক্সিম ব্যাংক ইসলামিক ভিসা গোল্ড কার্ড",
        network: "VISA",
        tier: "GOLD",
        annualFee: 2500,
        feeWaiverCondition: "Waived on annual spend of ৳1,00,000",
        feeWaiverConditionBn: "বার্ষিক ১,০০,০০০ টাকা ব্যয়ে ফি মওকুফ",
        interestRateMonthly: 0,
        interestRateAnnual: 0,
        interestFreeDays: 45,
        minIncome: 25000,
        isDualCurrency: true,
        airportLoungeAccess: false,
        rewardType: "REWARDS",
        rewardSummary: "1.5 Halal points per ৳100 spent",
        rewardSummaryBn: "প্রতি ১০০ টাকায় ১.৫ পয়েন্ট",
        zeroPctEmiAvailable: true,
        maxEmiMonths: 18,
        contactless: true,
        isShariah: true,
        cardColor: "#0369A1",
        features: ["1.5x Halal points", "0% installment purchase", "Islamic travel Takaful"],
        featuresBn: ["১.৫ গুণ পয়েন্ট", "০% কিস্তিতে কেনাকাটা", "ইসলামিক ভ্রমণ তাকাফুল"],
        popularity: 73,
      },
    ],
  },
];
